sql审核增加直接提交给后端执行的功能
hhyo/archer pull request #1073
Opened 2021-04-13 03:36 UTC by zouzhicun

在sql审核时可能存在很多语句审核服务不支持，但同时又想使用审核服务。因此增加一个在审核后可以直接提交给后端数据库的功能，以最大限度支持sql语句。直接执行的工单需要由超级管理员确认执行。

2021-04-13 14:27 UTC, LeoQuote commented on sql/engines/mysql.py
> +            return self.execute(db_name=workflow.db_name, sql=workflow.sqlworkflowcontent.sql_content)
不要在这里写, 在 sql_workflow 级别写逻辑, 直接调用 execute 方法, 或者再新建一个方法叫 manual_execute , 然后在 sql_worflow 级别调用这个新方法, 这样所有的engine 都可以用到.

2021-04-14 02:43 UTC, zouzhicun commented on sql/engines/mysql.py
> +            return self.execute(db_name=workflow.db_name, sql=workflow.sqlworkflowcontent.sql_content)
你是指在
[sql/sql_worflow.py](https://github.com/zouzhicun/Archery/blob/wdg/sql/sql_workflow.py#L412) 
或者
[sql/utils/execute_sql.py](https://github.com/zouzhicun/Archery/blob/wdg/sql/utils/execute_sql.py#L35)
增加判断逻辑调用新方法么?
这样如果其它的engine不提供新的方法，不就出现报错么？而且不能复用原有的流程

2021-04-14 06:13 UTC, LeoQuote commented on sql/engines/mysql.py
> +            return self.execute(db_name=workflow.db_name, sql=workflow.sqlworkflowcontent.sql_content)
你说得对, 还有另外一个问题, is_manual 和 https://github.com/zouzhicun/Archery/blob/72789f95d8f49bc9f5bd480d41643d5909886f30/sql/sql_workflow.py#L424-L427 这里的 mode == "manual" 可能会引起混淆, 有没有可能避免这个问题, 以及有没有可能 复用这里的 mode ?

2021-04-14 06:15 UTC, LeoQuote commented on sql/utils/execute_sql.py
> +        operation_info='执行结果：{}'.format(workflow.get_status_display())
```suggestion
    try:
        operation_info = task.result.error
    except:
        operation_info = '执行结果：{}'.format(workflow.get_status_display()
```

2021-04-14 09:18 UTC, zouzhicun commented on sql/engines/mysql.py
> +            return self.execute(db_name=workflow.db_name, sql=workflow.sqlworkflowcontent.sql_content)
提交工单时能用数据库记录为强行执行处理会比较容易。
如果不在[sql.sql_workflow.py 205](https://github.com/zouzhicun/Archery/blob/wdg/sql/sql_workflow.py#L205) 记录，则查看工单时[不能给出信息需要超级管理员审批](https://github.com/zouzhicun/Archery/blob/wdg/sql/sql_workflow.py#L260)，同时[不能判断需要用户为超级用户](https://github.com/zouzhicun/Archery/blob/wdg/sql/views.py#L159)。
[通过mode值判断为强行执行](https://github.com/zouzhicun/Archery/blob/wdg/sql/sql_workflow.py#L424)处理会比较棘手，由于前面说的问题，改动会比较大。
总之，需要提交工单时能用数据库记录，而选择 is_manual 字段是已经存在且没有被使用。

2021-04-14 09:41 UTC, zouzhicun commented on sql/utils/execute_sql.py
> +        operation_info='执行结果：{}'.format(workflow.get_status_display())
这样改时，如果 task.result.error=""，不是会缺少一些信息么？

2021-04-15 07:02 UTC, LeoQuote commented on sql/utils/execute_sql.py
> +        operation_info='执行结果：{}'.format(workflow.get_status_display())
如果 task.result.error 是一个简单的静态属性, 那可以直接 if task.result.error: operation_info = task.result.error else operation_info = '执行结果：{}'.format(workflow.get_status_display() , 不用这些 try 和 except

2021-04-15 08:39 UTC, LeoQuote commented on sql/engines/mysql.py
> +            return self.execute(db_name=workflow.db_name, sql=workflow.sqlworkflowcontent.sql_content)
OK 了解

2021-04-15 08:44 UTC, LeoQuote requested changes
我觉得权限只放给超级管理员这个可以再商量, 可以再做一个 django 的permission , 然后在判断权限的时候需要这个 permission 或者是超级管理员, 这样会比较好一点. 超级管理员毕竟是比较大的权限, 而且用超级管理员有点太投巧了.

2021-04-15 09:06 UTC, zouzhicun commented on sql/utils/execute_sql.py
> +        operation_info='执行结果：{}'.format(workflow.get_status_display())
确实应该是多余的担心

2021-04-15 09:20 UTC, zouzhicun commented
确实这只是一个投巧的实现方式，只是这样改动最少。其实不应该太依赖这个功能，毕竟采取审核了就应该按照常规流程走，只是现实又确实有这种需求，所以就给出一个可以例外的操作。

2021-04-29 08:12 UTC, closed without merging