规避sql中双引号引入的对象名大小写敏感问题
hhyo/archer pull request #1217
Opened 2021-11-04 02:01 UTC by peng19832

当sql中使用双引号，显式指定大小写敏感的对象名时：sql检测时，会报对象不存在错误

2021-11-04 03:19 UTC, LeoQuote requested changes
请删除不必要的注释

2021-11-04 03:19 UTC, LeoQuote commented on sql/engines/oracle.py
> +        -- WHERE table_name = '{tb_name}' and owner = '{db_name}' order by column_id
请删除这两行sql内的注释, 每一行的代码都会有作者, 不需要这样注明

2021-11-04 03:19 UTC, LeoQuote commented on sql/engines/oracle.py
> +                            #                       errormessage='当前平台，此语法不支持审核！',
修改代码直接删除就可以, 不用写注释, 所有版本都有历史记录

2021-11-04 03:26 UTC, peng19832 commented on sql/engines/oracle.py
> +        -- WHERE table_name = '{tb_name}' and owner = '{db_name}' order by column_id
好的

2021-11-04 03:26 UTC, peng19832 commented on sql/engines/oracle.py
> +                            #                       errormessage='当前平台，此语法不支持审核！',
收到

2021-11-04 03:51 UTC, LeoQuote commented on sql/engines/oracle.py
> +                                                  errormessage='None',
这个好像更改逻辑了, 为啥要更改这个逻辑? 单元测试还失败了

2022-01-08 07:13 UTC, hhyo commented
辛苦处理一下ci问题

2022-03-31 07:07 UTC, closed without merging