增加在线查询超时时间配置，超时连接主动关闭
hhyo/archer pull request #125
Opened 2019-04-14 08:48 UTC by hhyo

相关issue : #100
- 增加在线查询超时时间配置，超时连接主动关闭
  使用django_q的async_task去执行语句，并且同步等待执行结果，执行超时的语句会关闭连接
- job模块修改为task以及部分变量调整

2019-04-14 14:12 UTC, LeoQuote requested changes
天呐你都做了，而我还在摸鱼！！！ 那个报错的提示这么写吧：

查询时间超过 XX 秒，已被主动终止，请优化语句。

另外查询的exception 是不是没有写？ 可以再加一个 if result.success 不知道success 依然前端报错，具体的traceback可以传前端，也可以只打日志。

2019-04-14 14:18 UTC, LeoQuote commented
我认为第三种可以接受，因为查询频率高实际上查询的是redis ？ 查询的效率应该可以接受。

另外如果实在频率不能接受的话可以自己实现轮询查询，自己在代码中sleep即可。（挺丑哈哈哈

2019-04-14 15:10 UTC, hhyo commented
> 我认为第三种可以接受，因为查询频率高实际上查询的是redis ？ 查询的效率应该可以接受。
> 
> 另外如果实在频率不能接受的话可以自己实现轮询查询，自己在代码中sleep即可。（挺丑哈哈哈

从debug来看查的是mysql

2019-04-14 15:29 UTC, LeoQuote commented
查到有一个cached参数，可以让djangoQ在缓存中查询结果，我觉得可以考虑这个做。

https://django-q.readthedocs.io/en/latest/tasks.html

2019-04-14 15:43 UTC, hhyo commented
> 查到有一个cached参数，可以让djangoQ在缓存中查询结果，我觉得可以考虑这个做。
> 
> https://django-q.readthedocs.io/en/latest/tasks.html

已修改，push巨慢

2019-04-14 15:59 UTC, merged

2019-04-14 16:01 UTC, hhyo commented
合了发布1.5.0

2019-04-14 16:51 UTC, LeoQuote commented
棒👍

2019-05-29 07:19 UTC, jerryhu1234 commented
这里虽然提示是主动断开了连接，我发现1.6版本，sql还是在数据库上在跑的？？

2019-05-29 08:28 UTC, LeoQuote commented
> 这里虽然提示是主动断开了连接，我发现1.6版本，sql还是在数据库上在跑的？？

因为设置了timeout参数, 会结束掉python进程, 但是sql可能确实还在服务器上跑, 这块确实有优化空间

2019-05-29 08:40 UTC, hhyo commented
这一块之前的测试逻辑是这样

- 设置超时时间为10
- 在线查询执行select sleep(30)

10s后查询会被终止，并且mysql相应的进程也会终止，不清楚@jerryhu1234 遇到的是什么样的场景