增加登录审计日志
hhyo/archer pull request #1251
Opened 2021-11-26 05:21 UTC by ningyu1

Archery版本：1.8.1
功能：增加登入、登出、登入失败 审计日志

表结构：
```
DROP TABLE IF EXISTS `audit_log`;
CREATE TABLE `audit_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `user_id` int(11) DEFAULT NULL COMMENT '用户id',
  `user_name` varchar(255) DEFAULT NULL COMMENT '用户名称',
  `ip` varchar(255) DEFAULT NULL COMMENT '登录ip',
  `action` varchar(255) DEFAULT NULL COMMENT '动作',
  `action_time` datetime(6) NOT NULL COMMENT '操作时间',
  PRIMARY KEY (`id`),
  KEY `idx_username` (`user_name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='登录审计日志表';
```

变更文件：
```
common/templates/base.html  增加菜单路由
sql/admin.py                               增加对象引入
sql/audit_log.py                          增加登录审计日志处理
sql/models.py                             增加数据库模型
sql/templates/audit.html           增加操作页面
sql/tests.py                                 增加页面测试
sql/urls.py                                   增加路由注册
sql/views.py                                增加视图注册
```

界面截屏：
![image](https://user-images.githubusercontent.com/3387548/143530863-c2af3c99-b100-4cf3-a0c8-c71b7053093a.png)

2021-11-26 05:25 UTC, ningyu1 commented
@hhyo review一下

2021-11-26 06:37 UTC, ningyu1 commented
Travis CI build failed 是因为：`MySQLdb._exceptions.ProgrammingError: (1146, "Table 'test_archery.audit_log' doesn't exist")`
测试环境没有初始化表

2021-11-26 09:42 UTC, LeoQuote commented
`python manage.py migrate`  执行一下, 会产生一些migration, 一起提上来

2021-11-29 03:07 UTC, ningyu1 commented
@LeoQuote 没有任何结果
![image](https://user-images.githubusercontent.com/3387548/143802486-85f0331f-2c38-4559-ba5b-cb21f89161e9.png)

2021-11-29 03:42 UTC, ningyu1 commented
@LeoQuote 
.gitignore中忽略sql/migrations/   migration提不上来

2021-11-29 05:06 UTC, LeoQuote commented
@hhyo 咦, 现在已经不用 migration 了吗....我弄错了?

2021-11-29 05:52 UTC, ningyu1 commented
> @hhyo 咦, 现在已经不用 migration 了吗....我弄错了?

我把migrations提交了，ci成功了

2021-12-01 15:25 UTC, hhyo reviewed
- 审计日志不错，不过是否可以扩充一些，不仅限于登录，可以额外记录一些敏感操作

- 同时建议补充SQL文件，还是有很多是不依靠migrate升级的

2021-12-02 01:40 UTC, ningyu1 commented
> * 审计日志不错，不过是否可以扩充一些，不仅限于登录，可以额外记录一些敏感操作
> * 同时建议补充SQL文件，还是有很多是不依靠migrate升级的

1. 我看过审计日志除了登录日志没有以外，其他的操作都有日志，比如说查询日志、sql升级日志、以及django自带的变更日志
2. sql文件我稍后补充提交一下

2021-12-11 01:32 UTC, hhyo requested changes

2021-12-11 01:32 UTC, hhyo commented on sql/migrations/0001_initial.py
> +# Generated by Django 3.1.13 on 2021-11-29 11:35
migrate文件和目录还是删除下，一直没用这个管理，限制有些多，也会有冲突

2021-12-11 01:32 UTC, hhyo commented on src/init_sql/audit_log.sql
> +-- 增加登录审计日志
文件名称修改为v1.8.3.sql，方便升级管理

2021-12-13 03:58 UTC, ningyu1 commented on sql/migrations/0001_initial.py
> +# Generated by Django 3.1.13 on 2021-11-29 11:35
已清理migrate文件和目录

2021-12-13 03:59 UTC, ningyu1 commented on src/init_sql/audit_log.sql
> +-- 增加登录审计日志
audit_log.sql文件名已修改为v1.8.3.sql

2021-12-13 15:29 UTC, hhyo approved these changes

2021-12-13 15:32 UTC, merged

2021-12-24 17:21 UTC, weideguo commented
将审计功能全部抽到一个菜单栏是否是个好主意？
这样能方便审计人员集中在一个地方获取审计信息。
暂时考虑到要加以下的审计：
sql查询后的下载操作（暂时没有相关数据）
sql查询（有相关数据，只是在此提供另外一个查询界面）
sql上线（有相关数据，只是在此提供另外一个查询界面）
同时添加一个权限，用于查询这些审计信息

2021-12-25 04:07 UTC, hhyo commented
管理端和用户端能够有不同的入口可能会比较好，不过当前都混一起了，单独做个审计页面的话，看怎么重新设计下，感谢你的贡献，方便的话辛苦加一下我的微信rtttte

> 将审计功能全部抽到一个菜单栏是否是个好主意？ 这样能方便审计人员集中在一个地方获取审计信息。 暂时考虑到要加以下的审计： sql查询后的下载操作（暂时没有相关数据） sql查询（有相关数据，只是在此提供另外一个查询界面） sql上线（有相关数据，只是在此提供另外一个查询界面） 同时添加一个权限，用于查询这些审计信息