New pr
hhyo/archer pull request #1303
Opened 2021-12-28 09:36 UTC by issacmark

增加一个存放 ssh 隧道秘钥的专用目录，用户在配置 ssh 隧道时填秘钥名称即可

2021-12-28 10:05 UTC, LeoQuote commented
这个好像只适用于单机部署, 多实例的时候怎么办?

2021-12-29 05:26 UTC, issacmark commented
> 这个好像只适用于单机部署, 多实例的时候怎么办?

有道理，我再改改

2022-01-05 15:10 UTC, hhyo requested changes
感谢贡献，这个还需要补充下变更sql，以及如何做到平滑升级的说明

顺便问下这个pr主要解决的问题是什么，因为这块我个人没有使用，可能不了解痛点，再次感谢

2022-01-05 15:10 UTC, hhyo commented on sql/models.py
> -class AuditEntry(models.Model):
这块应该是其他pr合并到主干的，注意冲突处理

2022-01-05 15:10 UTC, hhyo commented on sql/models.py
> +    pkey = models.TextField(verbose_name="密钥", blank=True, null=True)
是否也采取加密存储的形式

2022-01-06 01:58 UTC, issacmark commented on sql/models.py
> -class AuditEntry(models.Model):
原来的方式：将密钥上传至 archery 部署的服务器目录，如果是docker部署的还需要传到容器卷挂载的目录下，如 downloads logs这种目录里，然后在后台天上这个目录的绝对路径，当部署多实例的时候就无法使用了，而且使用起来也不是特别便捷
修改后：由后台页面的上传按钮直接上传到keys目录，然后读取pkey的内容写入数据库的pkey字段，实际上每次连接都是从数据库获取pkey来连接

2022-01-06 02:11 UTC, issacmark commented on sql/models.py
> +    pkey = models.TextField(verbose_name="密钥", blank=True, null=True)
密钥长度太长了，所以用了这个

2022-01-06 02:17 UTC, issacmark commented on sql/models.py
> -class AuditEntry(models.Model):
目前使用这个功能的用户应该都是把密钥上传到了部署 archery 服务的服务器上，升级时需要把密钥下载到本地，更新版本后编辑对应条目，重新选择文件上传即可。
变更sql：
ALTER TABLE `archery`.`ssh_tunnel` 
ADD COLUMN `pkey` longtext NULL AFTER `password`;

2022-01-11 13:42 UTC, hhyo commented on sql/models.py
> +    pkey = models.TextField(verbose_name="密钥", blank=True, null=True)
加密组件也支持text，可以调整下

2022-01-11 13:48 UTC, hhyo commented on sql/models.py
> -class AuditEntry(models.Model):
> 目前使用这个功能的用户应该都是把密钥上传到了部署 archery 服务的服务器上，升级时需要把密钥下载到本地，更新版本后编辑对应条目，重新选择文件上传即可。 变更sql： ALTER TABLE `archery`.`ssh_tunnel` ADD COLUMN `pkey` longtext NULL AFTER `password`;

辛苦增加到1.8.3的sql文件中

2022-01-12 02:06 UTC, issacmark commented on sql/models.py
> +    pkey = models.TextField(verbose_name="密钥", blank=True, null=True)
嗯嗯 改成 EncryptedTextField 了

2022-01-13 00:28 UTC, hhyo approved these changes

2022-01-13 00:29 UTC, merged

2022-01-13 00:59 UTC, hhyo commented on src/init_sql/v1.8.3.sql
> +ALTER TABLE `ssh_tunnel` ADD COLUMN pkey longtext NULL AFTER password DEFAULT CHARSET=utf8mb4 COMMENT='密钥信息';
这个语句存在语法错误，还有pkey_path变成了filefield，确认下是否需要调整字段格式