MySQL数据脱敏inception改为goinception
hhyo/archer pull request #1307
Opened 2021-12-29 03:30 UTC by unknowissue

#Inception转为goInception，将archery中数据脱敏的IP和端口指向goInception的
#不修改整体逻辑，主要修改由goInception返回的结果中关键字，比如db修改为schema
#后续再优化逻辑，似乎并没有命中*判断

2021-12-30 02:39 UTC, unknowissue commented
嘶，有点问题， select a.* from t1 a  没有脱敏效果
https://github.com/hanchuanchuan/goInception/issues/417

2022-01-04 05:04 UTC, unknowissue commented
> 嘶，有点问题， select a.* from t1 a 没有脱敏效果 [hanchuanchuan/goInception#417](https://github.com/hanchuanchuan/goInception/issues/417)

@hhyo 哈喽，请教一下，这个问题goinception解了，测试需要  【v1.2.5-10】版本https://github.com/hanchuanchuan/goInception/releases/download/v1.2.5/goInception-linux-v1.2.5-10-g92649cc.tar.gz
这个版本，请问我应该咋使用这个版本进行测试？

2022-01-04 09:30 UTC, unknowissue commented
@hhyo  哈喽，帮忙看看呗，我再最新的values.yaml和docker-compose.yml中声明了使用最新的goInception版本,但是测试时，仍然使用旧的版本，是我哪里没有写对么？
谢谢啦

2022-01-04 14:12 UTC, hhyo commented
> @hhyo 哈喽，帮忙看看呗，我再最新的values.yaml和docker-compose.yml中声明了使用最新的goInception版本,但是测试时，仍然使用旧的版本，是我哪里没有写对么？ 谢谢啦

脱敏的测试都是使用的mock，并非是真实获取inception信息，只需要修改case里面的mock数据格式即可

2022-01-05 15:12 UTC, hhyo commented
看ci还有一个错误

2022-01-07 07:53 UTC, unknowissue commented
我先喝点快乐水冷茎一下。。。有点麻。
晚点搞，，，，

2022-01-08 04:23 UTC, unknowissue commented
靠，这次学习了，心塞了
脱敏配置方法：
1、如果实例配置了inception地址，那么就使用inception来解析
2、如果**没有配置**inception地址，但是打开了脱敏开关，那么使用goinception的masking功能解析（**建议使用goinception的v1.2.5-10及以上版本，最低为v1.2.5版本**）

2022-01-08 07:43 UTC, unknowissue commented
好像这样可以了？
@hhyo 
帮忙确认一下，
尴尬。。。。

2022-01-10 13:00 UTC, hhyo requested changes
如果确认可以完全替代inception，建议直接剔除inception相关的所有代码

2022-01-11 01:07 UTC, unknowissue commented
> 



> 如果确认可以完全替代inception，建议直接剔除inception相关的所有代码

我们不考虑做个兼容版么？是不是有同学还喜欢用inception啊。

2022-01-11 13:54 UTC, hhyo commented
> > 
> 
> > 如果确认可以完全替代inception，建议直接剔除inception相关的所有代码
> 
> 我们不考虑做个兼容版么？是不是有同学还喜欢用inception啊。

没必要了，目前的版本inception只用来做语句解析，已经不支持审核执行，脱敏如果可以替代，就没有保留的必要

2022-01-11 13:57 UTC, hhyo commented
https://github.com/hhyo/Archery/issues/145#issuecomment-524551497

这个里面失效的场景可以都验证下

2022-01-12 02:50 UTC, unknowissue commented
> [#145 (comment)](https://github.com/hhyo/Archery/issues/145#issuecomment-524551497)
> 
> 这个里面失效的场景可以都验证下

我 try try

2022-01-12 10:52 UTC, unknowissue commented
改了一版，将引用inception都改为引用goinception
可以试一下了

2022-01-13 00:37 UTC, hhyo commented on sql/engines/tests.py
> +    # @patch('sql.engines.goinception.GoInceptionEngine.query')
这个注释掉是？

2022-01-13 00:56 UTC, unknowissue commented on sql/engines/tests.py
> +    # @patch('sql.engines.goinception.GoInceptionEngine.query')
> 这个注释掉是？

原是
`    @patch('sql.engines.inception.InceptionEngine.query')
    def test_query_print(self, _query):
        sql = 'update user set id=100'
        row = [1,
               'select * from sql_instance limit 100',
               0,
               '{"command":"select","select_list":[{"type":"FIELD_ITEM","field":"*"}],"table_ref":[{"db":"archery","table":"sql_instance"}],"limit":{"limit":[{"type":"INT_ITEM","value":"100"}]}}',
               'None']
        column_list = ['ID', 'statement', 'errlevel', 'query_tree', 'errmsg']
        _query.return_value = ResultSet(full_sql=sql, rows=[row], column_list=column_list)
        new_engine = InceptionEngine()
        print_result = new_engine.query_print(self.ins, db_name=None, sql=sql)
        self.assertDictEqual(print_result, json.loads(_repair_json_str(row[3])))`
1、我没读懂这个测试，update 和   'select * from sql_instance limit 100', 的关系，改写为goinception的返回值也有问题。
2、测试的是query_print这个函数，我看这个函数已经被_table_ref>query_priv_check 引用和 test_table_ref_wrong 测试了，也没啥事问题
就先注释了。

2022-01-13 01:03 UTC, hhyo commented on sql/engines/tests.py
> +    # @patch('sql.engines.goinception.GoInceptionEngine.query')
可，应该是以前mock的问题

2022-01-13 01:04 UTC, merged

2022-01-13 01:10 UTC, hhyo commented on sql/utils/go_data_masking.py
> +                if token.ttype is Keyword and token.value.upper() in ['UNION', 'UNION ALL']:
可以测试下是否已经支持这种无法的解析

2022-01-13 01:11 UTC, hhyo commented on sql/utils/go_data_masking.py
> +    masking_columns = DataMaskingColumns.objects.filter(active=True)
以前不了解，实际上懒加载这块不会真正查询，不过脱敏效率好像还行

2022-01-13 01:13 UTC, hhyo commented
已合并，docker镜像push后演示地址会自动更新，辛苦做一些测试验证，同时相关的文档也可以进行一些调整和补充，感谢~

2022-01-13 01:21 UTC, unknowissue commented
> 已合并，docker镜像push后演示地址会自动更新，辛苦做一些测试验证，同时相关的文档也可以进行一些调整和补充，感谢~

好的，我look look
辛苦啦

2022-01-13 09:59 UTC, unknowissue commented on sql/utils/go_data_masking.py
> +    masking_columns = DataMaskingColumns.objects.filter(active=True)
这个地方我也没搞懂，不过，好像没啥问题。

2022-01-13 10:03 UTC, unknowissue commented on sql/utils/go_data_masking.py
> +                if token.ttype is Keyword and token.value.upper() in ['UNION', 'UNION ALL']:
这个['UNION', 'UNION ALL'] goinception在v1.2.4-73 版本后[https://github.com/hanchuanchuan/goInception/issues/351]已经支持了，返回的是一个重复的list，archery需要增加一个去重函数，我稍后更新一下。

2022-01-14 12:06 UTC, unknowissue commented
> > 已合并，docker镜像push后演示地址会自动更新，辛苦做一些测试验证，同时相关的文档也可以进行一些调整和补充，感谢~
> 
> 好的，我look look 辛苦啦
文档：
前提条件
1、MySQL如使用脱敏功能，建议使用goinception的v1.2.5-10及以上版本（docker 部署goinception需要使用latest），最低为v1.2.5版本(1.25不支持 select * )
配置修改
1、配置基本不变，inception地址和端口不需要填写
注意事项
1、目前还不支持子查询脱敏，比如select * from (select * from tab)

2022-01-23 03:06 UTC, hhyo commented
测试发现两个问题，覆盖场景比Inception的少，需要解决一下

1. 无法识别哪些语句不能正常脱敏，导致 QUERY_CHECK 参数失效，不能脱敏的语句也能正常查询，有较大风险
       嵌套子查询： `select * from (select * from users ) t;`
       多列函数：`select concat(id,phone) from users;`
      
2. 不支持诸如 [\*,column_a]| [a.\*, column_a, b.\*]  的脱敏
`select *,phone from users;`
`select a.*,a.phone,b.* from users a join sql_users_groups b on a.id =b.users_id;`

上述例子都可以在演示环境进行测试