新增my2sql工具插件模块 #1224
hhyo/archer pull request #1314
Opened 2022-01-04 02:45 UTC by nick2wang

新增my2sql工具插件模块 #1224

对比了主流的几款闪回工具，[MyFlash](https://github.com/Meituan-Dianping/MyFlash)很快接近原生mysqlbinlog，缺点是不能生成直观可读的sql，而且非常吃内存，不支持mysql 8；[binlog2sql](https://github.com/danfengcao/binlog2sql)功能性强，但是太慢了，在生产环境的大数据量下显得无力，而且同样对于mysql 8存在兼容性问题；[my2sql](https://github.com/liuhr/my2sql)算是比较均衡的，筛选功能丰富，实测解析速度能达到binlog2sql的5倍以上
<html>
<body>

<span>

  | my2sql | binlog2sql | MyFlash | mysqlbinlog
-- | -- | -- | -- | --
1.1G binlog回滚解析 | 1分50秒 | 19分钟 | 33秒 | 31秒

</span>

</body>
</html>

2022-01-04 04:27 UTC, LeoQuote approved these changes
看了下, 是用plugin实现的, 功能都完备, 本地测试没问题的话就ok 
LGTM

2022-01-04 04:28 UTC, LeoQuote requested changes
docker 编译没过, 其他ok, 修下 docker build

2022-01-04 05:30 UTC, nick2wang commented
> docker 编译没过, 其他ok, 修下 docker build

修改了dockerfile-base，但是workflow里依赖的archery-base镜像不能自动构建？
https://github.com/hhyo/Archery/blob/f588e8b90ad6c9be51399dc1c77a6200c2d4e3bb/src/docker/Dockerfile#L1

2022-01-04 14:19 UTC, hhyo approved these changes, later dismissed

2022-01-04 14:19 UTC, hhyo commented on sql/plugins/my2sql.py
> +    def generate_args2cmd(self, args, shell):
可以测试下是否规避了注入问题
https://gitee.com/rtttte/Archery/issues/I2AVG3

2022-01-04 14:27 UTC, hhyo commented on src/docker/Dockerfile-base
> +    && cd /opt \
可以调整一下workflow重新构建base，不行这个直接放Dockerfile问题也不大

2022-01-05 03:34 UTC, nick2wang commented on sql/plugins/my2sql.py
> +    def generate_args2cmd(self, args, shell):
> 可以测试下是否规避了注入问题 https://gitee.com/rtttte/Archery/issues/I2AVG3

确实存在该问题，已修改。同时其他plugin也存在通过path注入的风险（通过脚本路径配置项注入），后面再另外提一个pr
https://github.com/hhyo/Archery/blob/af1372253204215e34099e7f7422efc6c6671f7f/sql/plugins/binglog2sql.py#L36

2022-01-05 03:35 UTC, nick2wang commented on src/docker/Dockerfile-base
> +    && cd /opt \
> 可以调整一下workflow重新构建base，不行这个直接放Dockerfile问题也不大

暂时把my2sql的依赖项加到dockerfile里了

2022-01-05 03:46 UTC, nick2wang commented
> docker 编译没过, 其他ok, 修下 docker build

dockerfile已调整

2022-01-05 08:11 UTC, LeoQuote approved these changes, later dismissed
LGTM

2022-01-05 09:06 UTC, nick2wang commented on sql/plugins/my2sql.py
> +    def generate_args2cmd(self, args, shell):
> > 可以测试下是否规避了注入问题 https://gitee.com/rtttte/Archery/issues/I2AVG3
> 
> 确实存在该问题，已修改。同时其他plugin也存在通过path注入的风险（通过脚本路径配置项注入），后面再另外提一个pr
> 
> https://github.com/hhyo/Archery/blob/af1372253204215e34099e7f7422efc6c6671f7f/sql/plugins/binglog2sql.py#L36

通过path和实例信息注入的漏洞已修复 #1316

2022-01-05 09:07 UTC, nick2wang commented
通过path和实例信息注入的漏洞已修复 #1316

2022-01-05 15:15 UTC, hhyo approved these changes

2022-01-05 15:17 UTC, merged