archery 1.50 DBA规范建表SQL脚本
hhyo/archer pull request #132
Opened 2019-04-17 07:24 UTC by flyingonthebed

按照DBA建表规范修改 1.50 版本表结构，初始化完成后，可以使用该脚本替换已有表，生成规范表结构。

2019-04-17 08:41 UTC, hhyo requested changes
仅仅补充了1.5.0版本的注释，和 [v1.4.5_v1.5.0.sql](https://github.com/hhyo/Archery/blob/master/src/init_sql/v1.4.5_v1.5.0.sql) 貌似没有什么区别？

如果需要提交完整的注释版本，可以参考 [models](https://github.com/hhyo/Archery/blob/master/sql/models.py)

2019-04-17 08:58 UTC, flyingonthebed commented
@hhyo 字段类型修改，索引名、外键名修改。
稍等我提交一份，1.38升级1.50，和1.50初始化结构更新标准结构的2个SQL脚本。

2019-04-17 08:58 UTC, LeoQuote commented
建议添加新脚本， 如 v1.5.0_v1.5.1.sql 脚本中只添加字段comment， 另外我们的最新版本是 1.5.0 不是1.50 这个是笔误吗？

2019-04-17 09:03 UTC, hhyo commented
> @hhyo 字段类型修改，索引名、外键名修改。
> 稍等我提交一份，1.38升级1.50，和1.50初始化结构更新标准结构的2个SQL脚本。

参考 @LeoQuote 的新增一份脚本，仅使用alter改注释，不要删表建表，否则可能会给后续使用者带来困扰

2019-04-18 07:33 UTC, flyingonthebed commented
标准化DDL SQL 请参考。

2019-04-18 07:54 UTC, LeoQuote commented
感谢提交， 都确实是标准化的语句， 就像上面写的，请新建一个 v1.5.1_v1.5.2.sql 对现在已有的字段加备注， 修改索引名等，其他无关文件可删除。
文件中不要有空格，中文等，不要对1.5.0 前的版本和 1.5.0 后的版本做区分处理， 只关心 v1.5.1_v1.5.2 即可。

2019-04-18 13:06 UTC, LeoQuote commented on startup.sh
> +gunicorn -w 4 --env DJANGO_SETTINGS_MODULE=${settings} --error-logfile=/tmp/archery.err -b ${ip}:${port}  archery.wsgi:application &
不要加入和本次pr无关的脚本

2019-04-18 13:07 UTC, LeoQuote commented on src/init_sql/archery 1.38升级1.50 后标准化 DDL.sql
> +
此文件请删除

2019-04-18 13:08 UTC, LeoQuote commented on src/init_sql/archery_1.50.sql
> +/*
和初始化脚本重复, 请删除

2019-04-18 13:10 UTC, LeoQuote commented on src/init_sql/archery 1.50 标准化DDL.sql
> +
建议和上面的文件整合, 并改名为  v1.5.1_v1.5.2.sql 和前面版本的升级语句保持一致

2019-04-18 13:33 UTC, flyingonthebed commented on startup.sh
> +gunicorn -w 4 --env DJANGO_SETTINGS_MODULE=${settings} --error-logfile=/tmp/archery.err -b ${ip}:${port}  archery.wsgi:application &
pr 错了吧，不知道怎么跑这来了

2019-04-22 03:30 UTC, flyingonthebed commented
以重新提交pr

2019-04-22 03:30 UTC, closed without merging