审计功能增强
hhyo/archer pull request #1342
Opened 2022-01-17 09:05 UTC by weideguo

将审计功能全部抽到一个菜单栏
关联之前的 pr #1251

2022-01-17 15:34 UTC, hhyo reviewed
如果感兴趣可以借鉴一下redash/handlers/events.py

2022-01-17 15:34 UTC, hhyo commented on sql/migrations/0001_initial.py
> +# Generated by Django 3.1.2 on 2022-01-17 14:40
移除migrate信息，

2022-01-18 01:57 UTC, weideguo commented
> 如果感兴趣可以借鉴一下https://github.com/getredash/redash/blob/d8d7c78992e44a4b6d7fdd4c39ccc1c35cd8c7a9/redash/handlers/events.py#L1

没懂要做什么？

2022-01-18 16:14 UTC, hhyo commented
> > 如果感兴趣可以借鉴一下https://github.com/getredash/redash/blob/d8d7c78992e44a4b6d7fdd4c39ccc1c35cd8c7a9/redash/handlers/events.py#L1
> 
> 没懂要做什么？

看是否需要在extra中记录设备等信息，同时关于不存在的账号登录操作是否也有必要记录到数据库中，这块因为无法锁定可能存在风险

2022-01-19 03:06 UTC, weideguo commented
> > > 如果感兴趣可以借鉴一下https://github.com/getredash/redash/blob/d8d7c78992e44a4b6d7fdd4c39ccc1c35cd8c7a9/redash/handlers/events.py#L1
> > 
> > 
> > 没懂要做什么？
> 
> 看是否需要在extra中记录设备等信息，同时关于不存在的账号登录操作是否也有必要记录到数据库中，这块因为无法锁定可能存在风险

扩展成这样？
![1642561402](https://user-images.githubusercontent.com/3381137/150056174-5f34533b-8b17-49dd-950f-d5449f3b9db2.jpg)

不存在的账号登录操作不记录会导致个信息缺失。是否是因为DDOS的考虑呢？限制登录接口的访问频率似乎更好

2022-01-19 05:53 UTC, weideguo commented
> > > 如果感兴趣可以借鉴一下https://github.com/getredash/redash/blob/d8d7c78992e44a4b6d7fdd4c39ccc1c35cd8c7a9/redash/handlers/events.py#L1
> > 
> > 
> > 没懂要做什么？
> 
> 看是否需要在extra中记录设备等信息，同时关于不存在的账号登录操作是否也有必要记录到数据库中，这块因为无法锁定可能存在风险

考虑应该都是内网环境使用，加入地理信息没有太多用

2022-01-19 13:37 UTC, hhyo requested changes
记录和agent应该差不多了

2022-01-19 13:37 UTC, hhyo commented on sql/audit_log.py
> +import geolite2
这两个包应该没用到

2022-01-19 13:41 UTC, hhyo requested changes

2022-01-19 13:41 UTC, hhyo commented on sql/audit_log.py
> +    AuditEntry.objects.create(action=u'登入', extra_info='|'.join([ip,ua]), user_id=user.id, user_name=user.username, user_display=user.display, action_time=now)
加入ua应该要扩充长度了，要不还是恢复前面的记录ip吧😂，我考虑过多了

2022-01-19 16:09 UTC, hhyo approved these changes

2022-01-19 16:10 UTC, merged

2022-01-19 16:30 UTC, hhyo commented on sql/templates/sqlquery.html
> +        function downloadAppendOpt(){
发现查询没有记录查询的语句，可以参考这个issue处理下

https://github.com/hhyo/Archery/issues/970

2022-01-20 01:44 UTC, weideguo commented on sql/templates/sqlquery.html
> +        function downloadAppendOpt(){
好的，我研究研究。