oracle-数据字典兼容
hhyo/archer pull request #1351
Opened 2022-01-22 04:01 UTC by unknowissue

增加了Oracle的数据字典展示和导出功能

2022-01-22 08:40 UTC, unknowissue commented
Oracle的字段还需要再补充一下，以及Oracle的测试ci，晚点写。

2022-01-25 07:13 UTC, unknowissue commented
我还没写 mock ，我想想。
mock好麻烦。

2022-02-10 03:12 UTC, unknowissue commented
咦，oracle_test_export_db 和 oracle_test_export_instance 这两项咋不测试呢。。。

2022-02-16 06:43 UTC, unknowissue commented
嘶， oracle_test_export_db 和 oracle_test_export_instance 不测试
唔，就这样吧。。。
谁拉取测试看看吧。

2022-02-17 01:00 UTC, hhyo requested changes

2022-02-17 01:00 UTC, hhyo commented on requirements.txt
> +pandas
指定下版本，避免出现不兼容的升级

2022-02-17 02:21 UTC, unknowissue commented on requirements.txt
> +pandas
> 指定下版本，避免出现不兼容的升级

好了

2022-02-17 04:28 UTC, merged