增加下载的权限(hhyo#1367)
hhyo/archer pull request #1369
Opened 2022-02-08 10:50 UTC by weideguo

虽然限制前端的下载功能没有什么实质的意义，但似乎有人有这要求。

2022-02-09 03:27 UTC, LeoQuote requested changes
变量名可以改一下，改成 can_download，感谢贡献

2022-02-09 03:27 UTC, LeoQuote commented on sql/views.py
> +    is_download = 1 if user.has_perm('sql.download') or user.is_superuser else 0
```suggestion
    can_download = 1 if user.has_perm('sql.download') or user.is_superuser else 0
```

变量改成 can_download 更精准一点

2022-02-09 03:27 UTC, LeoQuote commented on sql/templates/sqlquery.html
> +                        var showExport = {{is_download}}==1
三个等于号？

2022-02-09 04:57 UTC, LeoQuote commented on sql/models.py
> +            ('download', '在线查询下载权限'),
query_download ,你觉得这个名字怎么样

2022-02-10 14:54 UTC, hhyo commented on src/init_sql/v1.8.3.sql
> +insert IGNORE INTO auth_permission (name, content_type_id, codename) VALUES
建议逻辑保持一致，给默认用户组授予权限，不需要的可以主动剔除

2022-02-11 05:46 UTC, hbbdgyb commented
大佬666

2022-02-11 10:21 UTC, weideguo commented on src/init_sql/v1.8.3.sql
> +insert IGNORE INTO auth_permission (name, content_type_id, codename) VALUES
``` sql
-- 默认组拥有在线查询下载权限
insert into auth_group_permissions (group_id, permission_id) select 1,id from auth_permission where 
name='在线查询下载权限' and content_type_id=@content_type_id and codename='query_download';
```
添加这样语句？

2022-02-12 00:28 UTC, hhyo commented on src/init_sql/v1.8.3.sql
> +insert IGNORE INTO auth_permission (name, content_type_id, codename) VALUES
对，不过也不一定用户都是用的这个默认组，不好确认，后续这边在release note中说明下好了

2022-02-12 00:29 UTC, hhyo approved these changes

2022-02-12 00:29 UTC, merged

2022-03-30 04:40 UTC, hhyo commented on sql/views.py
> +    return render(request, 'sqlquery.html', {'favorites': favorites, 'can_download':can_download})
这里需要调整下，判断的download，写入的定义是query_download😬

2022-05-30 01:57 UTC, feiazifeiazi commented
很需要这个权限控制。感谢。

2024-11-19 08:40 UTC, nicholascp commented
这个下载超过1000条就大概率这种，有地方可以配置?
![image](https://github.com/user-attachments/assets/7c97de31-935d-42a0-9081-500b65a71e44)