修复union-bug-1360
hhyo/archer pull request #1371
Opened 2022-02-09 01:22 UTC by unknowissue

bug:
https://github.com/hhyo/Archery/issues/1360

2022-02-09 04:32 UTC, unknowissue commented
还有点问题，得看看
https://github.com/hanchuanchuan/goInception/issues/426

2022-02-09 04:59 UTC, LeoQuote commented on sql/utils/go_data_masking.py
> +    particular_flag=0
额, 这个变量名能不能取更直白的? 特殊标记, 怎么特殊, 到底代表的是什么?

2022-02-09 06:28 UTC, unknowissue commented on sql/utils/go_data_masking.py
> +    particular_flag=0
> 

嗷，我想想，
我主要考虑的是其中有union或者concat关键字时的特殊处理，想用1，2，3这样的代码来简要判断

2022-02-09 06:37 UTC, LeoQuote commented on sql/utils/go_data_masking.py
> +    particular_flag=0
那可以直接列表列出来他拥有的特别关键字

2022-02-09 06:37 UTC, LeoQuote commented on sql/utils/go_data_masking.py
> +    particular_flag=0
1,2,3 这样的代码不是很明显, 会忘记的

2022-02-09 06:59 UTC, unknowissue commented on sql/utils/go_data_masking.py
> +    particular_flag=0
> 1,2,3 这样的代码不是很明显, 会忘记的

好滴，后面再修改看看，
goInception那边的树有点问题，我没懂啥意思。

2022-02-10 14:59 UTC, hhyo commented
如果使用goinception的脱敏暂时不能达到inception的效果，可以和最开始的pr一样，做成可选，方便发布下一个release版本

2022-02-15 07:47 UTC, unknowissue commented
多等等吧，那边的同学没反馈呢。

2022-02-21 06:35 UTC, unknowissue commented
可以了
哪位同学拉取试一试
需要注意goInception 要使用  [v1.2.5-23](https://github.com/hanchuanchuan/goInception/releases/tag/v1.2.5).

2022-02-23 14:11 UTC, unknowissue commented on sql/utils/go_data_masking.py
>      return new_data_list
#1371 
最新的已经改了

2022-02-24 14:05 UTC, hhyo requested changes
整体使用格式化工具进行一下格式化

2022-02-24 14:05 UTC, hhyo commented on sql/utils/go_data_masking.py
> +from pickle import TRUE
这个引用下面好像没用

2022-02-24 14:05 UTC, hhyo commented on sql/utils/go_data_masking.py
> +                elif token.ttype is Keyword and token.value.upper() in ['UNION','UNION ALL']:
上面if的空无用可以去掉

2022-02-24 14:05 UTC, hhyo commented on sql/utils/go_data_masking.py
> +        if  bool([s    for s in values     if  d['field']   in  s['field'] ]) is  False:
if not 就可以

2022-03-03 10:39 UTC, unknowissue commented on sql/utils/go_data_masking.py
> +                elif token.ttype is Keyword and token.value.upper() in ['UNION','UNION ALL']:
这个地方不需要保留么？
我感觉要是后面有不支持的关键字往里填就行。。。

2022-03-03 12:28 UTC, unknowissue commented
test_go_data_masking_union_support_keyword 
这个ci我麻了，，，，

2022-03-04 01:15 UTC, nick2wang commented
> test_go_data_masking_union_support_keyword 这个ci我麻了，，，，

可以先在本地跑unit test，打印更详细的日志

2022-03-04 02:57 UTC, unknowissue commented
亲，看了一下 test_go_data_masking_union_support_keyword 到了 go_data_masking里面后
在DelRepea函数的结果是空，
但是我在自己的环境里又没有问题。
不然拉取一下我的看看？
```python
        if keywords_count.get('UNION') :
            query_tree = DelRepeat(query_tree,keywords_count)
```

2022-03-05 01:51 UTC, merged