支持redis集群模式
hhyo/archer pull request #1392
Opened 2022-02-18 09:40 UTC by nick2wang

相关issues：#720 #895 #1238

redis生产环境上了规模的基本都是使用cluster模式，当前版本只支持standalone

修改：
1.实例配置表新增运行模式字段mode，可选standalone或cluster，只有db_type选择redis时可配置，其他时候隐藏
2.redis引擎引入redis.cluster.RedisCluster作为集群连接器

2022-02-18 12:14 UTC, hhyo requested changes
很赞，感谢贡献

2022-02-18 12:14 UTC, hhyo commented on src/init_sql/v1.8.3.sql
> +alter table sql_instance add column `mode` varchar(10) DEFAULT '' after `db_type`;
虽然engine没有判断standalone的mode，这里还是建议增加下update语句，将历史数据处理为standalone，毕竟modal的choices只允许这两个值

2022-02-18 13:13 UTC, LeoQuote commented
要我看直接加个engine也不错，直接继承了重写一个方法就行

2022-02-18 16:40 UTC, nick2wang commented on src/init_sql/v1.8.3.sql
> +alter table sql_instance add column `mode` varchar(10) DEFAULT '' after `db_type`;
> 虽然engine没有判断standalone的mode，这里还是建议增加下update语句，将历史数据处理为standalone，毕竟modal的choices只允许这两个值

已修改

2022-02-18 16:45 UTC, nick2wang commented
> 要我看直接加个engine也不错，直接继承了重写一个方法就行

确实额外加个engine更方便些，而且也不用特殊处理前端；主要是考虑到engines冗余，就合并在一起了

2022-02-19 02:03 UTC, hhyo approved these changes

2022-02-19 03:18 UTC, LeoQuote commented
> 

要不加 engine 吧, 这样不用写 type, 也不用改数据结构, 啥也不用, 就是覆盖一个方法

2022-02-19 03:31 UTC, hhyo commented
> > 
> 
> 要不加 engine 吧, 这样不用写 type, 也不用改数据结构, 啥也不用, 就是覆盖一个方法

加engine也还是需要识别数据库类型，前台改的地方不少，不过核心在于非集群模式的redis和集群模式是否有必要单独区分一个类型

2022-02-21 01:44 UTC, nick2wang commented
> > > 
> > 
> > 
> > 要不加 engine 吧, 这样不用写 type, 也不用改数据结构, 啥也不用, 就是覆盖一个方法
> 
> 加engine也还是需要识别数据库类型，前台改的地方不少，不过核心在于非集群模式的redis和集群模式是否有必要单独区分一个类型

还是合并使用一个redis engine吧，配置上来说对用户更友好

2022-02-21 04:58 UTC, LeoQuote commented
前端尽量友好没问题, 后端我觉得有改进空间, 可能存 json 串就行了, 这次 这个pr LGTM, 可能后续可以再改改, 好几个字段都属于 "连接额外参数",可以收到一个字段里面去,反正不需检索

2022-02-21 04:58 UTC, LeoQuote approved these changes
LGTM

2022-02-21 05:27 UTC, nick2wang commented
> 

ok

2022-02-21 05:27 UTC, nick2wang commented
> 前端尽量友好没问题, 后端我觉得有改进空间, 可能存 json 串就行了, 这次 这个pr LGTM, 可能后续可以再改改, 好几个字段都属于 "连接额外参数",可以收到一个字段里面去,反正不需检索

ok

2022-02-21 05:53 UTC, hhyo commented
> 前端尽量友好没问题, 后端我觉得有改进空间, 可能存 json 串就行了, 这次 这个pr LGTM, 可能后续可以再改改, 好几个字段都属于 "连接额外参数",可以收到一个字段里面去,反正不需检索

提到连接参数，确实是，oracle以及字符集和数据那些都是，后续优化可以增加一个conn_kwargs，保存连接字典参数，也方便个性化配置，剔除model中的冗余字段

2022-02-22 01:11 UTC, merged

2022-07-22 01:41 UTC, fancy-lee commented
redis集群模式下执测试连接报：module 'redis' has no attribute 'cluster'  
archery版本1.8.5

2022-07-22 01:44 UTC, fancy-lee commented
redis集群模式下执测试连接报：module 'redis' has no attribute 'cluster'  
archery版本1.8.5

2022-11-15 16:42 UTC, zhaoge26 commented
> redis集群模式下执测试连接报：module 'redis' has no attribute 'cluster' archery版本1.8.5

查看了一下Python Redis库版本，3.5.4，看了[文档，需要4.1.0开始才支持](https://pypi.org/project/redis/4.1.0/)。
自己下载镜像，升了个级，目前Redis cluster能用了，配置一个节点。