oracle规避对象名大小写敏感
hhyo/archer pull request #1438
Opened 2022-03-31 07:46 UTC by peng19832

规避oracle对象名使用双引号

2022-03-31 08:06 UTC, peng19832 commented
我对代码不是很熟悉。
请问下，我是需要对新增的每段代码，都写一个测试哇？

2022-04-01 07:21 UTC, LeoQuote commented
还挺多改动的, 有空看看

2022-04-01 07:59 UTC, nick2wang requested changes

2022-04-01 07:59 UTC, nick2wang commented on sql/engines/oracle.py
> +                    object_name = object_name.upper()
关于引号"的判断可以都去掉，直接在`if '.' in object_name`前面加一句`object_name = object_name.replace('"','')`即可

2022-04-01 07:59 UTC, nick2wang commented on sql/engines/oracle.py
> +                                object_name = self.get_sql_first_object_name(sql=sql_nolower)
这里不传入小写的sql的话，get_sql_first_object_name()里的正则就可能匹配不到了

2022-04-01 07:59 UTC, nick2wang commented on sql/engines/oracle.py
> +                cursor.execute(f" ALTER SESSION SET CURRENT_SCHEMA = \"{db_name}\" ")
这里加双引号的目的是什么？切换schema应该不需要

2022-04-13 01:23 UTC, peng19832 commented on sql/engines/oracle.py
> +                cursor.execute(f" ALTER SESSION SET CURRENT_SCHEMA = \"{db_name}\" ")
db_name是取的页面的下拉列表总的库名，这里不加双引号，如果库名是个大小写敏感的库名，就会切错，切进全大写的库，比如：
![image](https://user-images.githubusercontent.com/9590209/163080561-c3d69627-d0da-4066-909f-34c2c4f88e62.png)

2022-04-13 01:31 UTC, peng19832 commented on sql/engines/oracle.py
> +                    object_name = object_name.upper()
有这几种情况，结合下拉列表里大小写敏感的库名：
我们公司，之前没有约束，有很多项目库名、对象名就是用的驼峰命名，会出现ddl里对象名用双引号的话，就发现会全部通过检测，但实际对象都是不对的。
只是针对，缺乏数据库管理，不合规的场景，但确实遇到了的。#1427
![image](https://user-images.githubusercontent.com/9590209/163080884-35b59b3c-1fe9-43bd-9883-082bcae846d3.png)

2022-04-13 01:40 UTC, peng19832 commented on sql/engines/oracle.py
> +                                object_name = self.get_sql_first_object_name(sql=sql_nolower)
这个函数，好像是取空格分隔的第二组字符串，就是原文截取，有引号也是一样的，如果ddl里用了双引号的大小写敏感对象名，一概小写，就会有问题，比如：已存在表testTable，提交create table "testTable",还是会检测通过

2022-04-13 01:43 UTC, peng19832 commented
> 还挺多改动的, 有空看看

其实没改逻辑，只是字符串截取，想适配不同场景，大小写敏感的对象名的情况

2022-04-13 03:29 UTC, nick2wang commented on sql/engines/oracle.py
> +                                object_name = self.get_sql_first_object_name(sql=sql_nolower)
如果提交的sql是大写比如CREATE...这样就匹配不到，可以给re.match加个参数来忽略大小写 flags=re.IGNORECASE

2022-04-13 03:30 UTC, nick2wang requested changes

2022-04-13 03:30 UTC, nick2wang commented on sql/utils/sql_review.py
> +    if ( workflow.instance.db_type == 'mysql' or workflow.instance.db_type == 'oracle' ) and workflow.instance.instance_tag.filter(
这里和最新代码冲突了，麻烦处理下

2022-04-20 07:13 UTC, nick2wang approved these changes

2022-04-20 07:13 UTC, nick2wang commented
没啥问题了

2022-04-20 08:10 UTC, peng19832 reviewed
finish

2022-04-20 08:10 UTC, peng19832 commented on sql/engines/oracle.py
> +                                object_name = self.get_sql_first_object_name(sql=sql_nolower)
这个已经加上ignorecase，大佬记得看一下

2022-04-26 09:25 UTC, merged