修复下载权限名字错误
hhyo/archer pull request #1440
Opened 2022-04-01 17:20 UTC by weideguo

关联 pr #1369

2022-04-02 06:37 UTC, LeoQuote approved these changes
LGTM

2022-04-07 14:13 UTC, hhyo requested changes

2022-04-07 14:13 UTC, hhyo commented on sql/views.py
>      return render(request, 'sqlquery.html', {'favorites': favorites, 'can_download':can_download})
下面应该还有一处地方用到了

2022-04-07 14:29 UTC, weideguo commented on sql/views.py
>      return render(request, 'sqlquery.html', {'favorites': favorites, 'can_download':can_download})
`grep "sql.download" *.py */*py */*/*py */*/*/*py` 看到只有这里用这个权限

2022-04-08 04:48 UTC, hhyo commented on sql/views.py
>      return render(request, 'sqlquery.html', {'favorites': favorites, 'can_download':can_download})
好的，看历史审计那边的权限取消了

2022-04-08 04:48 UTC, merged