新增批量操作工单
hhyo/archer pull request #1531
Opened 2022-05-19 11:01 UTC by cslingjun

具体功能看图  #1466 
![middle_img_v2_6f98dcd6-0eb2-410d-afd1-ee57a308338g](https://user-images.githubusercontent.com/24772668/169278729-9cc7ee49-a89e-4448-bfa9-14c0cbbd2aff.jpg)

2022-05-21 09:04 UTC, qinqi123456 commented
1.8.4 提交SQL已经支持实例配置的时候配上db_name。强烈建议支持“批量提交SQL”
（1）多租户场景需要支持“批量提交SQL”。
（2）批量时针对一个语句，希望可以插入到多个实例，多个schema。

2022-05-23 01:37 UTC, cslingjun commented
> 1.8.4 提交SQL已经支持实例配置的时候配上db_name。强烈建议支持“批量提交SQL” （1）多租户场景需要支持“批量提交SQL”。 （2）批量时针对一个语句，希望可以插入到多个实例，多个schema。

这个功能我这边已经实现了 ，只是这个需求只是极少数朋友才会有。

2022-05-23 07:25 UTC, qinqi123456 commented
> > 1.8.4 提交SQL已经支持实例配置的时候配上db_name。强烈建议支持“批量提交SQL” （1）多租户场景需要支持“批量提交SQL”。 （2）批量时针对一个语句，希望可以插入到多个实例，多个schema。
> 
> 这个功能我这边已经实现了 ，只是这个需求极少数朋友才会有。所以这块功能暂未提pr

这个功能还是有必要的，易用性会提升一大截，尽快提pr吧，谢谢。

2022-05-25 09:43 UTC, LeoQuote commented
现在工单提交已经有接口了, 这个能否做成纯前端的功能? 因为后端这边做测试有点太麻烦了

2022-05-26 02:25 UTC, cslingjun commented
> 现在工单提交已经有接口了, 这个能否做成纯前端的功能? 因为后端这边做测试有点太麻烦了

这个代码我这边线上已经跑了快小一年了，这个后端处理会比较合适一点吧 ，我这边的需求有时候要处理1000多个工单，这样要反复调用1000多次接口 。不太合理感觉

2022-05-30 08:32 UTC, LeoQuote requested changes
代码复用不够, 这些检查的代码在单个工单的审核和执行中有类似的, 希望能复用一部分, 可以考虑直接把代码挪到 model 层, 作为 workflow 的一个 方法来做

2022-10-22 10:45 UTC, bluerfish commented
> > 1.8.4 提交SQL已经支持实例配置的时候配上db_name。强烈建议支持“批量提交SQL” （1）多租户场景需要支持“批量提交SQL”。 （2）批量时针对一个语句，希望可以插入到多个实例，多个schema。
> 
> 这个功能我这边已经实现了 ，只是这个需求极少数朋友才会有。所以这块功能暂未提pr

这个对多租户和一些分库分表很有用啊，我们现在提相同语句的工单在不同实例要提很多次，也要审批很多次。能发出来么

2023-05-29 06:40 UTC, peng19832 commented
> > 现在工单提交已经有接口了, 这个能否做成纯前端的功能? 因为后端这边做测试有点太麻烦了
> 
> 这个代码我这边线上已经跑了快小一年了，这个后端处理会比较合适一点吧 ，我这边的需求有时候要处理1000多个工单，这样要反复调用1000多次接口 。不太合理感觉

@cslingjun 
大佬，这个功能，好像只考虑了审核人的批量审核相关操作，是不是应该加上提交人一侧的批量操作呢，比如：
同一个sql，需要同时提交到多个实例的多个数据库中：
这种场景，其实就是复用相同的代码和数据库结构，只是部署到不同子公司的不同部门中，当有迭代需求时，需要上线到所有这些数据库，这时候提交人，就很繁琐，需要提交好多次同一个sql

2023-07-05 10:09 UTC, cslingjun commented
> > > 现在工单提交已经有接口了, 这个能否做成纯前端的功能? 因为后端这边做测试有点太麻烦了
> > 
> > 
> > 这个代码我这边线上已经跑了快小一年了，这个后端处理会比较合适一点吧 ，我这边的需求有时候要处理1000多个工单，这样要反复调用1000多次接口 。不太合理感觉
> 
> @cslingjun 大佬，这个功能，好像只考虑了审核人的批量审核相关操作，是不是应该加上提交人一侧的批量操作呢，比如： 同一个sql，需要同时提交到多个实例的多个数据库中： 这种场景，其实就是复用相同的代码和数据库结构，只是部署到不同子公司的不同部门中，当有迭代需求时，需要上线到所有这些数据库，这时候提交人，就很繁琐，需要提交好多次同一个sql

提交SQL按钮旁边是有个批量提交SQL工单按钮的 。你看我截图 。但是这块代码好像我没提上来

2023-07-20 06:29 UTC, Codecaver commented
> 提交SQL按钮旁边是有个批量提交SQL工单按钮的 。你看我截图 。但是这块代码好像我没提上来

大佬好，可以指导一下怎么加这一块的代码吗，想要个批量提交SQL工单的功能，感谢感谢

2023-10-08 02:03 UTC, peng19832 commented
> > 提交SQL按钮旁边是有个批量提交SQL工单按钮的 。你看我截图 。但是这块代码好像我没提上来
> 
> 大佬好，可以指导一下怎么加这一块的代码吗，想要个批量提交SQL工单的功能，感谢感谢

是的大佬，感谢

2024-05-21 11:29 UTC, closed without merging