1.sql查询 新增redis帮助文档；完全禁止keys命令
hhyo/archer pull request #157
Opened 2019-04-29 02:26 UTC by yyukai

2.其他一些小东西修改

2019-04-29 03:08 UTC, hhyo approved these changes

2019-04-29 03:08 UTC, hhyo commented on archery/settings.py
> -    import ldap
这里去除验证过么有影响的吧

2019-04-29 03:08 UTC, hhyo commented on sql/models.py
> -    update_time = models.DateTimeField('修改时间', auto_now_add=True)
model定义的变更都需要提供变更语句，目前版本v1.5.3，新SQL文件定义为v1.5.3_v1.5.4.sql，放在init_sql目录下

2019-04-29 03:10 UTC, hhyo requested changes
按照上面的反馈简单调整一下~

2019-04-29 03:19 UTC, yyukai commented on archery/settings.py
> -    import ldap
import ldap 这个没用的。我们一直在用ldap的。

2019-04-29 03:21 UTC, hhyo approved these changes

2019-04-29 03:22 UTC, merged

2020-06-12 09:27 UTC, PU-101 commented
请问为什么要禁止keys，我看redis帮助文档里有：
2、keys pattern 查找所有符合给定模式的key，通常用于查找key

2020-07-30 07:08 UTC, dongqianzheng commented
是否能支持下zset相关命令呢