新增oracle查询
hhyo/archer pull request #175
Opened 2019-05-07 06:34 UTC by LeoQuote

#144 
#174 

@yyukai

2019-05-07 06:37 UTC, LeoQuote commented
需要rebase一下。

2019-05-07 09:07 UTC, LeoQuote commented
不知道 oracle 能不能把schema 和table 混起来考虑， 这样如果是两层的结构， 可以在现有的结构中混用。

我看yyukai的代码的意思是schema下面还有table，然后才是字段之类的

2019-05-07 09:25 UTC, hhyo commented
oracle其实不用处理database，在oracle中只能通过创建user来创建schema，只需要在get_all_databases方法中返回schemas的信息，前端查询和权限申请以及校验规则就完全不用改，可以直接复用

pgsql因为不同database下的schema可以同名，所以必须要区分database和schema

2019-05-07 09:39 UTC, flyingonthebed commented
> 不知道 oracle 能不能把schema 和table 混起来考虑， 这样如果是两层的结构， 可以在现有的结构中混用。
> 
> 我看yyukai的代码的意思是schema下面还有table，然后才是字段之类的

oracle 的数据库对应 mysql 的实例，表空间对应 mysql 的 database，数据库只能有一个，表空间可以有多个。
创建了用户，就等于创建了同名的 schema，并且创建用户必须指定默认表空间。
表空间里可以有多个用户，多个用户即存在多个schema。
删除用户时，如果schema中有数据，需要drop user aaa cascade; 做级联删除。
可参考下图：

![image](https://user-images.githubusercontent.com/35367394/57289741-85278d80-70ee-11e9-815f-930b156d2b1f.png)

2019-05-07 10:05 UTC, LeoQuote commented
我有一个实现的建议：

新创建两个方法，``get_first_layer_list`` , ``get_second_layer_list``（瞎取的名字， 后续可以改） , 在这两个方法中拿到两层列表。

现有的``get_all_databases`` , ``get_all_schemes`` 不变， 在上面说的两个方法中再调用现有的方法即可。

这样做的原因是统一engine的各种方法， 在工单和查询层面统一调用的方法，这样对后端的代码修改会非常小。

前端可以对不同类型数据库显示不同的名字。

2019-05-07 10:21 UTC, hhyo commented
pg有三级db->schema->tb，其实mssql也是类似吧

2019-05-07 11:55 UTC, yzypals commented
我目前 做了一个比较简单的处理，  直接把 oracle的模式 对标 mysql的数据库 来处理， 目前自己测试  在线查询，已经可以用了， 上线审核我用只读账号 测试 也能走完整个流程了

2019-05-07 12:44 UTC, LeoQuote commented
@yzypals 你的方案也是很好的，redis和sql server采用的就是这样的方案，但是实际上是schema ，后端却是db，可能会有一些误解，正在思考如何解决问题

2019-05-09 14:50 UTC, hhyo requested changes
这些点我来调整吧

2019-05-09 14:50 UTC, hhyo commented on sql/admin.py
> +    list_display = ('id', 'instance_name', 'db_type', 'type', 'host', 'port', 'user', 'password', 'service_name',
password本来就是加密的，不建议在列表展示

2019-05-09 14:50 UTC, hhyo commented on sql/engines/mssql.py
> +    def execute_check(self, db_name=None, sql=''):
mssql的上线功能？

2019-05-09 14:50 UTC, hhyo commented on sql/templates/sqlquery.html
> +                                    // TODO 实例中的筛选可以在python代码中， 使用filter实现， 这种实现可能有效率问题。
确实会有效率问题

2019-05-09 14:50 UTC, hhyo commented on src/init_sql/v1.5.0_v1.5.1.sql
> +alter table query_privileges_apply add `schema_list` longtext NOT NULL after db_list;
后面三个语句可以删除了，然后直接补充在v1.5.3_v1.5.4.sql后面

2019-05-09 15:07 UTC, hhyo approved these changes

2019-05-09 15:15 UTC, merged

2019-05-09 17:38 UTC, LeoQuote commented on sql/engines/mssql.py
> +    def execute_check(self, db_name=None, sql=''):
准备做了, 我司DBA给了我一个备份方案