添加手动执行功能
hhyo/archer pull request #178
Opened 2019-05-07 13:34 UTC by yzypals

2019-05-07 13:35 UTC, yzypals commented
重新提交的 手动执行上线语句的pr

2019-05-07 14:08 UTC, hhyo commented
@LeoQuote 增加手工执行结束状态的话，国际化文件需要增加些什么吗

2019-05-07 14:11 UTC, hhyo requested changes

2019-05-07 14:11 UTC, hhyo commented on sql/sql_workflow.py
> +    # 将流程状态修改为执行中
应该是手工执行完成？

2019-05-07 14:11 UTC, hhyo commented on sql/sql_workflow.py
> +                  operation_type=5,
状态和类型可能标记执行结束会更合理，这里应该是手工执行完成后回过来手工做个流程确认吧

2019-05-07 14:11 UTC, hhyo commented on sql/sql_workflow.py
> +                  operation_info="人工操作执行",
操作信息也可以体现这一点

2019-05-07 14:36 UTC, yzypals commented on sql/sql_workflow.py
> +                  operation_info="人工操作执行",
![手工执行当前状态1](https://user-images.githubusercontent.com/35222142/57308177-6f2ec280-7118-11e9-89bd-b2ce6fed8845.png)
![手工执行工单状态1](https://user-images.githubusercontent.com/35222142/57308197-7a81ee00-7118-11e9-872b-6f8dad75282e.png)
当前状态还需要改下css 颜色

2019-05-07 15:41 UTC, LeoQuote commented
https://github.com/hhyo/Archery/tree/master/sql/locale/zh_Hans/LC_MESSAGES 这个目录下的两个本地化文件需要添加一下新工单状态的翻译，照着添加就可以了。

2019-05-07 15:50 UTC, yzypals commented
第一次用这个git    这个 你们是怎么样合并我这和分支的呢， 我看上面都是好多都是红色XX

2019-05-07 16:32 UTC, LeoQuote commented
有红色的叉叉是因为单元测试覆盖率没达要求，最好是你也提供一下单元测试，在engines 的 tests.py里面

2019-05-08 06:07 UTC, LeoQuote commented
我仔细看了一下代码， 我发现手动执行和自动执行的逻辑非常相似， 只是少了实际执行工单的那一步， 可不可以考虑只是简单的在execute中加一个参数， 如果这个参数为真就不做实际执行？

2019-05-08 10:48 UTC, yzypals commented
按你说的 改了代码了 减少了代码量  复用一个view 来做处理

2019-05-08 14:58 UTC, LeoQuote commented on sql/sql_workflow.py
> +    if mode == "auto":
这两个if还是要分开, 我试了下如果合在一起, 因为工单是异步执行, 如果工单执行时间非常短,有可能会导致数据错误问题.

2019-05-08 15:29 UTC, hhyo approved these changes

2019-05-08 15:36 UTC, merged

2019-05-08 15:39 UTC, hhyo commented
已合并，感谢贡献，后续可以在功能开发前就提交PR，方便及时的进行review和修正

找时间补充一个贡献指南