:sparkles: 增加OIDC登入功能
hhyo/archer pull request #2028
Opened 2023-01-10 14:13 UTC by shing6326

这个pull request 增加了keycloak / oidc 登入选项, 基本上打开以下参数就可连结keycloak

ENABLE_OIDC="True"
OIDC_RP_ISSUER_URL="https://keycloak.example.com/realms/<your realm>"
OIDC_RP_CLIENT_ID="<your client id>"
OIDC_RP_CLIENT_SECRET="<your client secret>"

2023-01-10 17:31 UTC, LeoQuote commented on archery/settings.py
> +
这一部分的配置是不是太多了，一般不是这几个吗：
1. well known
2. client id 和 secret
3. scope

2023-01-11 02:25 UTC, shing6326 commented on archery/settings.py
> +
我看上游还没有支持well known呢
https://github.com/mozilla/mozilla-django-oidc/pull/309

2023-01-11 04:09 UTC, LeoQuote commented on archery/settings.py
> +
特么的.... oidc 的意义不就是自动发现么....这lib 好离谱

2023-01-11 04:18 UTC, LeoQuote requested changes
非常感谢你的贡献, 但是这个配置方式好复杂, 你能否实现一个支持 自动发现的配置, 让管理员只填:
1. discovery url
2. client id + client secret
3. kwargs (包括 scope 等)

这些需要的配置实际上都可以通过 requests 请求得到, 实现的难度应该不高

2023-01-11 04:19 UTC, LeoQuote commented
我个人也很期待这个功能, 内部 oidc 已经有了, 就等这个功能完成, 接入了

2023-01-11 04:25 UTC, shing6326 commented
好的, 我加一下

2023-01-11 05:34 UTC, shing6326 commented
除了oidc.auth.OIDCAuthenticationBackend, https://github.com/mozilla/mozilla-django-oidc/blob/main/mozilla_django_oidc/middleware.py 也要调用OIDC_OP_AUTHORIZATION_ENDPOINT, 所以那个requests 只能在settings.py 里面跑

2023-01-11 05:37 UTC, LeoQuote commented on archery/settings.py
> +    OIDC_RP_CLIENT_SECRET = env("OIDC_RP_CLIENT_SECRET", default="<your client secret>")
这三个配置都是必须要有的, 不要设置默认值, 只写注释, 如果不写默认值, 在没有配置的时候会抛错

2023-01-11 05:38 UTC, LeoQuote commented on archery/settings.py
> +    response = requests.get(OIDC_RP_WELLKNOWN_URL)
这里需要 response.raise_for_status()

2023-01-11 10:04 UTC, LeoQuote commented
等一下 #2030 这个merge , 需要把 CI 修好

2023-01-12 10:04 UTC, LeoQuote commented
lint 修一下哈, 你装一下 black 执行下就行了

2023-01-12 10:34 UTC, shing6326 commented
> lint 修一下哈, 你装一下 black 执行下就行了

完成, 謝謝了

2023-01-12 11:11 UTC, LeoQuote commented
看看测试错误, 关注一下哦

2023-01-12 13:06 UTC, shing6326 commented
> 看看测试错误, 关注一下哦

現在只有code coverage 沒過, 是不是不用管的?

2023-01-13 03:57 UTC, LeoQuote commented
嗯嗯, 现在可以了

2023-01-13 13:33 UTC, LeoQuote commented on archery/settings.py
> +    "mozilla_django_oidc",
哦对，这个是否可以在已经启用 oidc 的时候才加入？

2023-01-13 13:47 UTC, shing6326 commented on archery/settings.py
> +    "mozilla_django_oidc",
我試試, 第一次用django不太熟悉哈哈

2023-01-13 14:23 UTC, shing6326 commented on archery/settings.py
> +    "mozilla_django_oidc",
試了, 正常運作

2023-01-17 08:08 UTC, LeoQuote approved these changes
LGTM

2023-01-17 08:08 UTC, merged

2023-02-07 08:22 UTC, updogliu commented
When will this feature be released? @LeoQuote

2023-09-12 13:33 UTC, wjlsq commented
您好，我想问下，oidc怎么配置？是只需要在.env中添加如下参数就可以吗？下边参数，我应该在oidc管理员处获取到么？
ENABLE_OIDC="True"
OIDC_RP_ISSUER_URL=""
OIDC_RP_CLIENT_ID=""
OIDC_RP_CLIENT_SECRET=""

2023-09-12 13:37 UTC, wjlsq commented
@LeoQuote 
您好，我想问下，oidc怎么配置？是只需要在.env中添加如下参数就可以吗？下边参数，我应该在oidc管理员处获取到么？
ENABLE_OIDC="True"
OIDC_RP_ISSUER_URL=""
OIDC_RP_CLIENT_ID=""
OIDC_RP_CLIENT_SECRET=""

2024-03-05 09:17 UTC, zhangzhaox commented
希望有个OIDC功能开启的配置手册说明，谢谢

2024-03-08 01:58 UTC, yangguocang commented
有没有关闭OIDC_VERIFY_SSL 认证的参数呀

2024-04-15 15:55 UTC, arthas3014 commented
> 有没有关闭OIDC_VERIFY_SSL 认证的参数呀

你好我想问下您配置oidc成功了吗，回调的uri应该填什么路径呢