Songtao12 patch 2
hhyo/archer pull request #2071
Opened 2023-03-03 09:33 UTC by songtao12

自动识别Oracle SQL上线文本中的PLSQL程序块，原代码逻辑要求在PLSQL块开始和结尾处分别添加delimiter $$和$$符号，很难满足产线实际上线要求，新功能在原来基础上实现自动识别和分割PLSQL代码块。

2023-03-13 06:34 UTC, LeoQuote requested changes
这一段程序比较复杂, 单元测试和单元测试覆盖率必须达标

2023-03-13 09:36 UTC, songtao12 commented
> 这一段程序比较复杂, 单元测试和单元测试覆盖率必须达标

这部分代码需要修改和优化下，后面我会重新提交

2023-03-14 08:10 UTC, songtao12 commented
> > 这一段程序比较复杂, 单元测试和单元测试覆盖率必须达标
> 
> 这部分代码需要修改和优化下，后面我会重新提交

代码已重新修改和优化

2023-03-14 08:43 UTC, LeoQuote commented
能否增加一些单元测试?

2023-03-15 01:27 UTC, songtao12 commented
> 能否增加一些单元测试?



> 能否增加一些单元测试?

我开发完成后是在本地环境，用公司实际上线的SQL脚本做了SQL检测，检测了20个SQL文本，每个文本平均在3万行，累计60万行左右的SQL脚本，其中包括各种SQL语句以及PLSQL块，检测结果暂时没有发现分割错乱的情况。
SQL文本处理这部分比较复杂，会存在各种各样的情况，我在写代码过程中是根据Oracle执行SQL的书写规范（参照PLSQL Developer与SQL * PLUS工具），尽量覆盖到可能存在的各种情况，但也很难保证100%覆盖到所有可能的场景。
原代码逻辑我在测试过程中也发现即使在PLSQL块前后强制添加指定符号作为开始和结尾标识符，也会在特定情况下出现分割错乱（如：PLSQL块内部文本内容包含"$$"符号时，会被从中间切分开）。
目前我能想到的场景都已经测试通过，有问题的也进行了代码修复和优化，对于可能存在的其他特定场景下触发的问题，发现之后可以再单独作为一个BUG修补下。

2023-03-15 02:33 UTC, nick2wang commented
> > 能否增加一些单元测试?
> 
> > 能否增加一些单元测试?
> 
> 我开发完成后是在本地环境，用公司实际上线的SQL脚本做了SQL检测，检测了20个SQL文本，每个文本平均在3万行，累计60万行左右的SQL脚本，其中包括各种SQL语句以及PLSQL块，检测结果暂时没有发现分割错乱的情况。 SQL文本处理这部分比较复杂，会存在各种各样的情况，我在写代码过程中是根据Oracle执行SQL的书写规范（参照PLSQL Developer与SQL * PLUS工具），尽量覆盖到可能存在的各种情况，但也很难保证100%覆盖到所有可能的场景。 原代码逻辑我在测试过程中也发现即使在PLSQL块前后强制添加指定符号作为开始和结尾标识符，也会在特定情况下出现分割错乱（如：PLSQL块内部文本内容包含"$$"符号时，会被从中间切分开）。 目前我能想到的场景都已经测试通过，有问题的也进行了代码修复和优化，对于可能存在的其他特定场景下触发的问题，发现之后可以再单独作为一个BUG修补下。

单元测试的目的是防止后续其他开发者提交的代码影响到你原本正常运行的功能，可以在这里补充
https://github.com/hhyo/Archery/blob/master/sql/engines/tests.py

2023-03-15 09:28 UTC, songtao12 commented
> > > 能否增加一些单元测试?
> > 
> > 
> > > 能否增加一些单元测试?
> > 
> > 
> > 我开发完成后是在本地环境，用公司实际上线的SQL脚本做了SQL检测，检测了20个SQL文本，每个文本平均在3万行，累计60万行左右的SQL脚本，其中包括各种SQL语句以及PLSQL块，检测结果暂时没有发现分割错乱的情况。 SQL文本处理这部分比较复杂，会存在各种各样的情况，我在写代码过程中是根据Oracle执行SQL的书写规范（参照PLSQL Developer与SQL * PLUS工具），尽量覆盖到可能存在的各种情况，但也很难保证100%覆盖到所有可能的场景。 原代码逻辑我在测试过程中也发现即使在PLSQL块前后强制添加指定符号作为开始和结尾标识符，也会在特定情况下出现分割错乱（如：PLSQL块内部文本内容包含"$$"符号时，会被从中间切分开）。 目前我能想到的场景都已经测试通过，有问题的也进行了代码修复和优化，对于可能存在的其他特定场景下触发的问题，发现之后可以再单独作为一个BUG修补下。
> 
> 单元测试的目的是防止后续其他开发者提交的代码影响到你原本正常运行的功能，可以在这里补充 https://github.com/hhyo/Archery/blob/master/sql/engines/tests.py

好的，我研究下怎么写

2023-03-20 03:14 UTC, songtao12 commented
> > > > 能否增加一些单元测试?
> > > 
> > > 
> > > > 能否增加一些单元测试?
> > > 
> > > 
> > > 我开发完成后是在本地环境，用公司实际上线的SQL脚本做了SQL检测，检测了20个SQL文本，每个文本平均在3万行，累计60万行左右的SQL脚本，其中包括各种SQL语句以及PLSQL块，检测结果暂时没有发现分割错乱的情况。 SQL文本处理这部分比较复杂，会存在各种各样的情况，我在写代码过程中是根据Oracle执行SQL的书写规范（参照PLSQL Developer与SQL * PLUS工具），尽量覆盖到可能存在的各种情况，但也很难保证100%覆盖到所有可能的场景。 原代码逻辑我在测试过程中也发现即使在PLSQL块前后强制添加指定符号作为开始和结尾标识符，也会在特定情况下出现分割错乱（如：PLSQL块内部文本内容包含"$$"符号时，会被从中间切分开）。 目前我能想到的场景都已经测试通过，有问题的也进行了代码修复和优化，对于可能存在的其他特定场景下触发的问题，发现之后可以再单独作为一个BUG修补下。
> > 
> > 
> > 单元测试的目的是防止后续其他开发者提交的代码影响到你原本正常运行的功能，可以在这里补充 https://github.com/hhyo/Archery/blob/master/sql/engines/tests.py
> 
> 好的，我研究下怎么写

已补充单元测试

2023-03-20 14:14 UTC, LeoQuote approved these changes

2023-03-22 17:12 UTC, merged

2023-10-20 07:29 UTC, yangjule126 commented
这个功能是没有完成吧？