将阿里云RDB的功能抽到单独engine
hhyo/archer pull request #2087
Opened 2023-03-17 16:39 UTC by weideguo

阿里云RDS之前的处理方式不够优雅，将相关方法放到单独engine，同时方便其他RDS使用类似方式在engine定制功能。
同时修复一些拼写错误。
我没有阿里云RDS的资源，烦请有资源的同学帮忙测试功能。

2023-03-17 23:39 UTC, hhyo requested changes
处理一下lint检测，其实rds这些接口是否还存在都不是很清楚了

2023-03-17 23:39 UTC, hhyo commented on sql/db_diagnostic.py
> +# from .aliyun_rds import process_status as aliyun_process_status, create_kill_session as aliyun_create_kill_session, \
确认删除的可以不用注释直接删除

2023-03-17 23:39 UTC, hhyo commented on sql/db_diagnostic.py
> +        r = engine.kill(json.loads(thread_ids), request_params=request_params)
https://github.com/hhyo/Archery/blob/b92ac0186f1f36e5ef90877819a6e33ec81c490d/sql/templates/dbdiagnostic.html#L852-L859

看前台参数应该也只是包含thread_ids，不需要再次传入request_params

2023-03-17 23:39 UTC, hhyo commented on sql/slowlog.py
> +        result = query_engine.slowquery_review(
都做到这一步了，可以一起把slowquery相关的方法也转移到mysql engine中，这里就判断下引擎就可以了

2023-03-18 11:11 UTC, weideguo commented on sql/slowlog.py
> +        result = query_engine.slowquery_review(
现在mysql处理slowquery处理方式不是很通用，需要额外程序往表里导慢查询相关数据，而不是mysql本身的功能，所以感觉还是不要放在engine比较好。

2023-03-31 13:06 UTC, hhyo commented on sql/engines/cloud/aliyun_rds.py
> -    def kill(self, thread_ids, request_params):
request_params 确实是需要的，前面看错了，这个可以采取关键字参数，在方法内获取

2023-03-31 13:06 UTC, hhyo requested changes
lint还是需要修一下

2023-06-18 10:04 UTC, hhyo commented
相关api已经被移除，先合并，有rds管理需求的自行接入吧

2023-06-18 10:05 UTC, hhyo approved these changes

2023-06-18 10:05 UTC, merged