fix bug 2177 2168
hhyo/archer pull request #2183
Opened 2023-06-08 10:43 UTC by taijiyouxia

fix bug 2168：
explain plan for create table test (id number);
select CARDINALITY from (select CARDINALITY from PLAN_TABLE t where id = 0 order by t.timestamp desc) where rownum = 1

![image](https://github.com/hhyo/Archery/assets/30249998/e1f56560-17f8-40cf-ae3a-501175383d03)

注意上面的返回是有结果的，一行数据，但是这一行数据值为null。
所以rows[0] 为None。

此时会走到
result["rows"] = rows[0]

会报：
https://github.com/hhyo/Archery/issues/2168
[2023-05-23 16:44:22,753][Thread-2:139803802728192][task_id:default][oracle.py:1010][WARNING]- Oracle 语句执行报错，第1个SQL：create table test111(id int);，错误信息Traceback (most recent call last):
File "/backup/Archery-1.9.1/sql/engines/oracle.py", line 836, in execute_check
if result_set["rows"] > 1000:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

fix bug 2177：
11.2.0.4版本中，不支持ddl中绑定变量，故修改为                
cursor.execute(f' ALTER SESSION SET CURRENT_SCHEMA = "{db_name}" ')

2023-06-08 11:12 UTC, LeoQuote requested changes

2023-06-08 11:12 UTC, LeoQuote commented on sql/engines/oracle.py
> +            if rows[0] is None or not rows:
```suggestion
            if not rows or not isinstance(rows, list) or not rows[0]:
```

2023-06-08 11:12 UTC, LeoQuote commented on sql/engines/oracle.py
> +                cursor.execute(f' ALTER SESSION SET CURRENT_SCHEMA = "{db_name}" ')
这里是为了防止注入, 请回滚

2023-06-08 11:13 UTC, LeoQuote commented on sql/engines/oracle.py
> +                cursor.execute(f' ALTER SESSION SET CURRENT_SCHEMA = "{db_name}" ')
如果低版本的不支持,  还请麻烦提供其他防止sql注入的手段

2023-07-24 08:28 UTC, closed without merging

2023-08-24 02:47 UTC, tonyhu214 commented
@LeoQuote  我们可以使用connection.current_schema=db_name代替 cursor.execute(f' ALTER SESSION SET CURRENT_SCHEMA = "{db_name}" ') 参考https://cx-oracle.readthedocs.io/en/latest/api_manual/connection.html?highlight=CURRENT_SCHEMA#Connection.current_schema 官方文档

2023-08-24 05:18 UTC, LeoQuote commented
@tonyhu214 如果知道方案的话, 还请麻烦提个 pr, 多谢了