Update settings.py
hhyo/archer pull request #222
Opened 2019-05-27 06:35 UTC by flyingonthebed

import LDAP packet

2019-05-27 07:10 UTC, LeoQuote requested changes
ldap不用imort，请修改

2019-05-27 16:39 UTC, flyingonthebed commented
已修改

2019-05-27 23:15 UTC, hhyo approved these changes

2019-05-27 23:20 UTC, merged

2019-05-28 02:46 UTC, flyingonthebed commented
ldap 还是需要 import 的
![image](https://user-images.githubusercontent.com/35367394/58447056-bd424f00-8135-11e9-8c2a-9430629e920d.png)

2019-05-28 02:52 UTC, LeoQuote commented
🤦‍

2019-05-28 02:59 UTC, flyingonthebed commented
那我再提一个