fix #2252
hhyo/archer pull request #2266
Opened 2023-08-24 17:29 UTC by tonyhu214

使用conn.current_schema=db_name 替换ALTER SESSION SET CURRENT_SCHEMA = :db_name

2023-08-25 00:24 UTC, LeoQuote commented
lint 修一下谢谢，只需要 black . —exclude venv 就可以了

另外不需要这样反复close open，只需要往你的分支里推送新代码，pr会自动更新的

2023-08-25 06:56 UTC, tonyhu214 commented
@LeoQuote  sry，昨天晚上加班，脑子有点迷糊

2023-08-25 07:32 UTC, LeoQuote requested changes
这样改一下安全一些

2023-08-25 07:32 UTC, LeoQuote commented on sql/engines/oracle.py
> +                                        result_set["rows"] is not None
```suggestion
                                        result_set.get("rows")
```

2023-08-25 07:32 UTC, LeoQuote commented on sql/engines/oracle.py
> +                                    result_set["rows"] is not None
```suggestion
                                    result_set.get("rows")
```

2023-08-28 01:28 UTC, tonyhu214 commented
@LeoQuote 非常感谢你的建议，基于你的建议我觉得get方法应该加上缺失默认值，避免key缺失导致异常。例如get("rows“, None)

2023-08-28 03:01 UTC, LeoQuote commented
好的，不过get方法如果不指定第二个参数，返回的值就会是None

2023-08-28 03:03 UTC, LeoQuote approved these changes

2023-08-28 03:03 UTC, merged