增加系统配置项，使前端可以调整dml是否经过DBA审批
hhyo/archer pull request #2284
Opened 2023-09-01 09:56 UTC by database-on-line

作为一名DBA来说，其实对于业务并没有业务leader熟悉，所以加了这个开关控制，可以对行数较少的dml不经过DBA审批，既能增加业务审批的速度，又能减少DBA的工作量

2023-09-01 14:18 UTC, hhyo approved these changes
这个场景确实比较多，可以作为免批的补充

2023-09-01 14:20 UTC, hhyo requested changes
先把修复ci一下

2023-09-02 02:31 UTC, database-on-line commented
好的，我看下哪里出问题重新跑下吧，改动不大，不知道为啥出现了docker编译报错和测试用例没通过，我再看看

2023-10-08 02:01 UTC, peng19832 commented
![image](https://github.com/hhyo/Archery/assets/9590209/f296af46-c07f-4eb1-9f22-0c5a0e4b88af)
这个，可以通过配置项实现，也还行

2023-11-07 14:49 UTC, LeoQuote commented
你好, 感谢你的 pr, 最新的 master 分支已经支持深度审批流自定义, 在 settings 内部可以设置需要采用的审批流对象, 此时你可以指定一个你自己实现的 自定义对象, 详见 https://github.com/hhyo/Archery/pull/2348

```python
class CustomAudit(AuditV2):
    def generate_audit_setting(self):
        ...
```

2023-11-07 14:49 UTC, closed without merging