qcluster 启动方式改为supervisor启动, 增加稳定性
hhyo/archer pull request #230
Opened 2019-05-28 10:08 UTC by LeoQuote

关联issue 
#224 
#188 
#211
#218

2019-05-28 10:52 UTC, hhyo requested changes
debug.sh文件也改下？

2019-05-28 11:43 UTC, LeoQuote commented
不用吧，都debug了就直接运行呗

发自我的 iPhone

> 在 2019年5月28日，18:52，小圈圈 <notifications@github.com> 写道：
> 
> @hhyo requested changes on this pull request.
> 
> debug.sh文件也改下？
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-05-28 11:45 UTC, merged

2019-06-01 01:57 UTC, hhyo commented
通过docker-compose 启动，无法控制启动顺序，有可能Archery服务启动qcluster时redis还没有启动，会导致qcluster启动失败，但是qcluster不会去重试https://github.com/Koed00/django-q/pull/223，进程也不退出，就会有个假的进程在
```
[2019-06-01 09:37:42,726][MainThread:4656580032][task_id:django-q][cluster.py:53][INFO]- Q Cluster-18154 starting.
[2019-06-01 09:37:42,751][MainThread:4656580032][task_id:django-q][redis_broker.py:37][ERROR]- Can not connect to Redis server.
```
supervisor也只是解决了重启的问提，初次启动这个坑还在

2019-06-01 02:44 UTC, LeoQuote commented
可以考虑使用docker -compose的功能
depends_on:
      - db