Fix favicon and opt nav
hhyo/archer pull request #2316
Opened 2023-10-08 23:22 UTC by finovy

**/static/img/favicon.ico not exist,cause error：**

Traceback (most recent call last):
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 54, in get_response
    return self.serve(request)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 50, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/contrib/staticfiles/views.py", line 37, in serve
    raise Http404("'%s' could not be found" % path)
django.http.response.Http404: 'img/favicon.ico' could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/core/handlers/exception.py", line 165, in get_exception_response
    response = callback(request, exception=exception)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/mnt/Archery/common/views.py", line 33, in page_not_found
    return HttpResponseNotFound(render(request, template_name))
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/template/context.py", line 254, in bind_template
    updates.update(processor(self.request))
  File "/mnt/Archery/common/utils/global_info.py", line 10, in global_info
    user = request.user
AttributeError: 'WSGIRequest' object has no attribute 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 81, in __call__
    return super().__call__(environ, start_response)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 131, in __call__
    response = self.get_response(request)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 56, in get_response
    return response_for_exception(request, e)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/core/handlers/exception.py", line 69, in response_for_exception
    response = get_exception_response(
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/core/handlers/exception.py", line 168, in get_exception_response
    response = handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/core/handlers/exception.py", line 186, in handle_uncaught_exception
    return callback(request)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/mnt/Archery/common/views.py", line 38, in server_error
    return HttpResponseServerError(render(request, template_name))
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/root/.virtualenvs/Archery/lib/python3.8/site-packages/django/template/context.py", line 254, in bind_template
    updates.update(processor(self.request))
  File "/mnt/Archery/common/utils/global_info.py", line 10, in global_info
    user = request.user

**also optimize left nav default collapse**

2023-10-09 07:43 UTC, LeoQuote requested changes
没有看出来 collapse 修改的必要性, 能否详细说明一下

2023-10-10 06:30 UTC, finovy commented
每次切换页面都会默认展开再折叠，修改 collapse 实现默认折叠

2023-10-10 06:40 UTC, LeoQuote approved these changes

2023-10-10 06:41 UTC, LeoQuote commented
我这边试了下, 确实有这样的情况, 谢谢你的pr

2023-10-10 06:41 UTC, merged