数据库查询字段不区分大小写，脱敏失败问题
hhyo/archer pull request #2332
Opened 2023-10-13 08:08 UTC by woshiyanghai

fix https://github.com/hhyo/Archery/issues/2328

解决数据库脱敏失败问题，mysql，sqlserver，oracle 列名不区分大小写，pg区分，所以考虑在脱敏表中新添加一个字段标记是否区分大小写。

2023-10-19 16:21 UTC, LeoQuote requested changes
如果是数据库的特性的话, 在 engine 部分实现比较好

2023-10-20 00:57 UTC, woshiyanghai commented
> 如果是数据库的特性的话，在引擎部分实现比较好

2023-10-20 01:28 UTC, woshiyanghai commented
> 如果是数据库的特性的话, 在 engine 部分实现比较好
不算是一种特性，更多的和我们写sql语句的时候大小写关系更多一些。

2023-10-20 03:34 UTC, LeoQuote commented
如果你这个功能放在instance字段里, 那添加数据库实例的时候就要思考是否大小写敏感, 但实际上大小写敏感还是不敏感, 只需要确认他是什么数据库就可以, 如你所说 `mysql，sqlserver，oracle 列名不区分大小写，pg区分` , 那为什么不在各自的 engine 里写就行了呢, 还需要录入的人自己去确认是否区分大小写, 是不是没有必要了?

2023-10-20 03:42 UTC, LeoQuote commented
看一下 CI, 必须要过才能合并, 可以先 rebase 下 master 谢谢

2023-10-20 03:51 UTC, woshiyanghai commented
> 如果你这个功能放在instance字段里, 那添加数据库实例的时候就要思考是否大小写敏感, 但实际上大小写敏感还是不敏感, 只需要确认他是什么数据库就可以, 如你所说 `mysql，sqlserver，oracle 列名不区分大小写，pg区分` , 那为什么不在各自的 engine 里写就行了呢, 还需要录入的人自己去确认是否区分大小写, 是不是没有必要了?

脱敏这个功能不是很通用，有的时候不会去配置脱敏规则，如果在需要配置脱敏规则的时候，标注下当前规则是否区分大小写，更方便一些感觉。

2023-10-20 04:04 UTC, LeoQuote requested changes

2023-10-20 04:04 UTC, LeoQuote commented on src/init_sql/v1.10.0.sql
> +ALTER TABLE data_masking_columns ADD UNIQUE INDEX (instance_id,table_schema,table_name,column_name);
这里的unique索引是对的吗？ 一个字段当前不允许设置多个脱敏规则吗？

2023-10-20 04:04 UTC, LeoQuote commented on src/init_sql/v1.10.0.sql
> +ALTER TABLE data_masking_columns ADD UNIQUE INDEX (instance_id,table_schema,table_name,column_name);
如果确认的话，请在model层也加一下unique index 的定义，方便跑单元测试

2023-10-20 05:12 UTC, woshiyanghai commented on src/init_sql/v1.10.0.sql
> +ALTER TABLE data_masking_columns ADD UNIQUE INDEX (instance_id,table_schema,table_name,column_name);
这个唯一键是有必要的，同实例同db同一个列只能有一个脱敏规则也是合理的

2023-10-20 05:23 UTC, LeoQuote requested changes

2023-10-20 05:23 UTC, LeoQuote commented on src/init_sql/v1.10.0.sql
> +ALTER TABLE data_masking_columns ADD UNIQUE INDEX (instance_id,table_schema,table_name,column_name);
这里能否给index 起个名字, 以 uk 开头

2023-10-20 05:23 UTC, LeoQuote commented on src/init_sql/v1.10.0.sql
> +ALTER TABLE data_masking_columns ADD UNIQUE INDEX (instance_id,table_schema,table_name,column_name);
另外这些改表请写到 v1.11.0.sql 内, 因为下一个版本是 v.1.11.0

2023-10-20 05:24 UTC, woshiyanghai commented on src/init_sql/v1.10.0.sql
> +ALTER TABLE data_masking_columns ADD UNIQUE INDEX (instance_id,table_schema,table_name,column_name);
好的

2023-10-20 05:52 UTC, hhyo commented
这块是不是匹配时直接不区分大小写就可以了

没有太大的必要单独配置

2023-10-20 05:55 UTC, woshiyanghai commented
> 这块是不是匹配时直接不区分大小写就可以了
> 
> 没有太大的必要单独配置

直接不区分大小写的话其实大部分时候是可以的，就是对于配置规则的人来说，如果他有个字段他真的是大写或者大小写混合，最后也会被脱敏掉，可能稍微有一点点奇怪， 对于区分大小写的pg数据库，如果大写的字段被小写的规则命中脱敏掉，好像不是很合理。

2023-10-24 01:09 UTC, hhyo commented
既然除了大小写都一样，理论上存储内容也不应该有太大差别，先做最小化调整在匹配时忽略大小写吧

2023-10-24 01:28 UTC, woshiyanghai commented
重新修改代码！

2023-10-24 01:28 UTC, closed without merging