Rgr
hhyo/archer pull request #239
Opened 2019-05-30 08:52 UTC by yzypals

拆分资源关联表为2张
将标签和实例改为关联表

2019-05-31 01:13 UTC, hhyo requested changes
这几个修改后还缺数据迁移的脚本，这块我周末处理，这周末合并发版吧

2019-05-31 01:13 UTC, hhyo commented on sql/models.py
> +    instances = models.ManyToManyField(Instance,through='InstanceTagRelations',through_fields=('instance_tag','instance'))
关系表中已经使用外键，这个关联是为了处理什么？

2019-05-31 01:13 UTC, hhyo commented on sql/templates/groupmgmt.html
> +                                return "<a href=\"/admin/sql/users/" + row.object_id + "/change/\">" + row.object_id__username + "</a>";
这个描述显示中文名display

2019-05-31 01:13 UTC, hhyo commented on sql/resource_group.py
> +        rows_obj = rows_objusers
搜索可以加在每个对象获取的地方，参考上面

2019-05-31 01:20 UTC, yzypals commented on sql/models.py
> +    instances = models.ManyToManyField(Instance,through='InstanceTagRelations',through_fields=('instance_tag','instance'))
可以使用自带的mtm 查询

2019-05-31 01:22 UTC, yzypals commented on sql/templates/groupmgmt.html
> +                                return "<a href=\"/admin/sql/users/" + row.object_id + "/change/\">" + row.object_id__username + "</a>";
好的  我修改下

2019-05-31 05:01 UTC, LeoQuote commented
这个功能下次发布再合吧，先合几个bug修复，不要关pr！

2019-06-07 04:10 UTC, hhyo approved these changes

2019-06-07 04:14 UTC, merged