对前端界面进行微调优化
hhyo/archer pull request #2492
Opened 2024-01-26 12:41 UTC by finovy

- 优化顶部Logo点击默认进入/dashboard，并调整菜单名为控制台
- 调整每页显示数量为20，和表格组件一致

2024-01-27 03:14 UTC, hhyo commented
首页路径现在是可以通过参数动态配置的INDEX_PATH_URL，分页这个调整下可以，毕竟现在分辨率都高了

2024-01-29 02:05 UTC, LeoQuote requested changes
建议只改 pageSize 别的保持原样，因为已存在相关配置

2024-01-29 02:07 UTC, finovy commented
已force push

2024-01-29 03:00 UTC, LeoQuote approved these changes

2024-01-29 03:01 UTC, merged