对导航菜单进行优化
hhyo/archer pull request #2494
Opened 2024-01-29 07:06 UTC by finovy

1. 对导航菜单进行优化
2. 新增使用less用于编写css样式表
3. 合并登录login.css到style.css

2024-01-29 07:22 UTC, LeoQuote requested changes
建议不引入 less 
如果引入的话，要在构建步骤中做css 文件的生成，并在开发手册，或目录的readme 区域说明开发时的构建方法。
不接受把 dist 文件夹提交到代码库中。

2024-01-29 07:24 UTC, finovy commented
好的，已删除less

2024-01-29 07:35 UTC, LeoQuote commented on common/static/dist/css/style.css
目录改一下，不要建新目录

2024-01-29 07:35 UTC, LeoQuote commented on common/static/dist/css/style.css.map
map请勿提交

2024-02-01 10:26 UTC, finovy commented
hi 请问本次PR还有什么需要修改的地方吗

2024-02-01 11:18 UTC, LeoQuote requested changes

2024-02-01 11:18 UTC, LeoQuote commented on common/static/dist/css/style.css
请改一下这里

2024-02-02 04:48 UTC, LeoQuote approved these changes

2024-02-03 11:21 UTC, merged