新增对doris的支持
hhyo/archer pull request #2536
Opened 2024-03-15 15:14 UTC by Grain-Yu

支持doris的查询、上线审核
相关讨论：https://github.com/hhyo/Archery/discussions/2175

2024-03-16 00:35 UTC, LeoQuote commented on sql/engines/doris.py
> +class DorisEngine(EngineBase):
```suggestion
class DorisEngine(MysqlEngine):
```

试试直接继承mysql，只用覆盖一些有差别的

2024-03-16 13:22 UTC, LeoQuote reviewed
麻烦对照再检查下, 能不覆盖的方法就不要覆盖, 并不是说你直接转换了基类就行了

2024-03-16 13:22 UTC, LeoQuote commented on sql/engines/doris.py
>          self.config = SysConfig()
这方法和 mysqlengine 方法一样, 应该可以删掉

2024-03-16 13:22 UTC, LeoQuote commented on sql/engines/doris.py
> +        return "Doris engine"
这两个改成属性吧, 应该效果一样

```
name = "Doris"
info = "Doris engine"
```

2024-03-16 13:22 UTC, LeoQuote commented on sql/engines/doris.py
> +    def get_connection(self, db_name=None):
MysqlEngine 里 get_connection 用的是 MySQLdb ,应该是一样的吧, 能否说明下这里覆盖的目的?

2024-03-16 13:22 UTC, LeoQuote commented on sql/engines/doris.py
> +    def get_all_tables(self, db_name, **kwargs):
没看出来和 MysqlEngine 的区别, 能否删除?

2024-03-16 14:48 UTC, Grain-Yu commented on sql/engines/doris.py
>          self.config = SysConfig()
done

2024-03-16 14:48 UTC, Grain-Yu commented on sql/engines/doris.py
> +        return "Doris engine"
done

2024-03-16 14:50 UTC, Grain-Yu commented on sql/engines/doris.py
> +    def get_connection(self, db_name=None):
确实是一样的，那这里的就删去了

2024-03-16 14:53 UTC, Grain-Yu commented on sql/engines/doris.py
> +    def get_all_tables(self, db_name, **kwargs):
初衷是MysqlEngine 的get_all_tables有个小bug，刚提了：https://github.com/hhyo/Archery/issues/2537
那这里就删除了，新提pr修复这个问题

2024-03-16 15:16 UTC, LeoQuote requested changes
不好意思因为doris 和 mysql 的协议是完全兼容的，能否过一遍你所有的方法，能复用的就删除，无法复用的请在方法注释，或代码评论中说明需要覆盖的原因，这样能最大程度的简化代码，减轻审核的难度。

另外CI的这个检查，lint 和覆盖率是必须要过的，可以参考下 black 的使用方法，单元测试这个如果你能力有限，我有空帮你补一下也是可以的

2024-03-16 17:55 UTC, Grain-Yu commented
> 不好意思因为doris 和 mysql 的协议是完全兼容的，能否过一遍你所有的方法，能复用的就删除，无法复用的请在方法注释，或代码评论中说明需要覆盖的原因，这样能最大程度的简化代码，减轻审核的难度。
> 
> 另外CI的这个检查，lint 和覆盖率是必须要过的，可以参考下 black 的使用方法，单元测试这个如果你能力有限，我有空帮你补一下也是可以的

class DorisEngine中的改动说明

auto_backup:
回滚功能暂未做全面测试，因此改成false

server_version:
MysqlEngine通过conn.get_server_info()获取，返回的值是"5.7.20-16log"这种形式，
对于doris不适用，通过执行show frontends获取版本信息

query：
MysqlEngine中的autocommit设置对于doris无实际作用。
MysqlEngine通过set session max_execution_time={max_execution_time}设置最大执行时间，对于doris不适用
mysql的column_type列类型来自column_types_map中预定义的数据类型，对于doris不适用

get_all_databases：
MysqlEngine中屏蔽的库为("information_schema", "performance_schema", "mysql", "test", "sys")，
对于doris是("__internal_schema", "INFORMATION_SCHEMA", "information_schema")

get_all_columns_by_tb：
MysqlEngine中通过查询 information_schema.COLUMNS

query_check:
MysqlEngine中的"不应该查看mysql.user表"规则，对doris不适用

execute_check：
MysqlEngine中的“判断Inception检测结果”，对doris不适用。这一部分参考了PgSQLRngine的execute_check

execute_workflow：
MysqlEngine中的判断实例是否只读对doris不适用，改为原生执行

execute：
参考CassandraEngine的实现，将执行和获取结果的逻辑放到一起。

2024-03-16 23:39 UTC, Grain-Yu commented
单元测试实在是不会，请帮忙添加

2024-03-17 03:21 UTC, LeoQuote commented
https://github.com/Grain-Yu/Archery/pull/1 把这个合了看一下, 下次提 pr 记得新开一个分支, 主分支有保护我这边不能直接推

2024-03-17 03:55 UTC, LeoQuote approved these changes

2024-03-17 03:57 UTC, LeoQuote commented
@hhyo 我帮忙写了点测试覆盖率还是低了点, 不过没关系这是 engine 级别的, 不会危害到主程序的监控, 等有空我再归并一些重复的优化一下

2024-03-17 03:58 UTC, LeoQuote commented
@Grain-Yu 另外我这边没 doris 的环境, 还请帮忙测试下能否正常运行

2024-03-17 06:14 UTC, merged

2025-07-10 02:31 UTC, wangwenjie2500 commented
很棒。。刚好项目上用到了doris，我把这个合进来