修复doris表结构查询异常
hhyo/archer pull request #2602
Opened 2024-04-21 11:35 UTC by Grain-Yu

fix: https://github.com/hhyo/Archery/issues/2589
优化MysqlEngine与doris的兼容性：
doris中，带变量的sql语句，不支持“WHERE TABLE_SCHEMA = %(db_name)s” 的写法。

2024-04-21 14:30 UTC, LeoQuote requested changes
https://github.com/hhyo/Archery/blob/master/sql/engines/doris.py

现在有doris 专用引擎了

2024-04-21 23:56 UTC, Grain-Yu commented
> https://github.com/hhyo/Archery/blob/master/sql/engines/doris.py
> 
> 现在有doris 专用引擎了

但是get_all_columns_by_tb没去做单独的实现，是从mysql继承过来的

2024-04-22 01:39 UTC, LeoQuote commented
好吧我看错了

2024-04-22 01:39 UTC, LeoQuote approved these changes

2024-04-22 01:40 UTC, merged