修复pgsql数据库下执行计划查看
hhyo/archer pull request #2638
Opened 2024-05-12 06:47 UTC by peixubin

在pgsql模式下，在线查询功能的执行计划错误的执行了SQL，没有显示执行计划；仅在配置了disable_star下，才禁止带*查询

2024-05-13 05:09 UTC, peixubin commented
希望尽快合并，后续还有pgsql的自动审核功能

2024-05-13 05:35 UTC, LeoQuote requested changes
测试和 lint 通过, 单元测试达标是基本要求, 请核对

2024-05-13 09:00 UTC, peixubin commented
麻烦先撤销这个pr

2024-05-13 09:37 UTC, LeoQuote commented
你好, 有更新可以继续往上推送, 如非必要请不要新开 issue

2024-05-14 07:41 UTC, LeoQuote approved these changes

2024-05-14 07:42 UTC, LeoQuote approved these changes
多谢贡献👍

2024-05-14 07:42 UTC, merged