修复mongodb无法上线#2648
hhyo/archer pull request #2649
Opened 2024-05-15 10:38 UTC by lanheader

mongo实例无法上线，报错
错误信息Traceback (most recent call last):
  File "/Users/lanjx/WorkSpace/bakend/python/archery/sql/engines/mongo.py", line 482, in execute
    actual_affected_rows = r.get("nModified", 0)
AttributeError: 'str' object has no attribute 'get'
经过排查，确少文件
<img width="897" alt="image" src="https://github.com/hhyo/Archery/assets/52522047/48fce6fd-0ceb-4bf8-8dbe-f06f3b490d09">
现在给基础镜像下载openssl，编译后补充缺失文件

2024-05-15 10:42 UTC, LeoQuote commented on src/docker/setup.sh
>  mv /opt/mongodb-linux-x86_64-rhel70-3.6.20/bin/mongo /usr/local/bin/
这里下的是 redhat ( centos ) 的发行版, 你看能否替换一下上面的下载链接, 看能否解决, 之前把 base 换到了 ubuntu 还是 debian

2024-05-15 10:44 UTC, lanheader commented on src/docker/setup.sh
>  mv /opt/mongodb-linux-x86_64-rhel70-3.6.20/bin/mongo /usr/local/bin/
没有必要替换，我们只用了mongo可执行文件。替换debian，就需要安装一套mongodb。基础镜像就太大了

2024-05-15 10:46 UTC, LeoQuote commented on src/docker/setup.sh
>  mv /opt/mongodb-linux-x86_64-rhel70-3.6.20/bin/mongo /usr/local/bin/
我们基础镜像是已经调整为 debian 了 https://github.com/hhyo/Archery/pull/2389

2024-05-15 10:49 UTC, lanheader commented on src/docker/setup.sh
>  mv /opt/mongodb-linux-x86_64-rhel70-3.6.20/bin/mongo /usr/local/bin/
我尝试安装debian版本的，最低版本5.0.26，不太符合engine这边的语法

2024-05-15 10:52 UTC, LeoQuote commented on src/docker/setup.sh
>  mv /opt/mongodb-linux-x86_64-rhel70-3.6.20/bin/mongo /usr/local/bin/
好吧, 我懂了, 你有空试一下用高版本的客户端上线不? 因为当前的方案实际上是把 openssl 降级了, 这个是不太提倡的, openssl 有可能后续有安全修复, 用低版本有一些安全风险.

2024-05-15 10:53 UTC, lanheader commented on src/docker/setup.sh
>  mv /opt/mongodb-linux-x86_64-rhel70-3.6.20/bin/mongo /usr/local/bin/
没有降级，只是使用了openssl的两个二进制文件。后续看下别的方案

2024-05-15 10:55 UTC, LeoQuote commented on src/docker/setup.sh
>  mv /opt/mongodb-linux-x86_64-rhel70-3.6.20/bin/mongo /usr/local/bin/
另外当初用命令行是因为另一个 pr 就是这么实现的 https://github.com/hhyo/Archery/pull/900 如果想改下的话, 也可以把审核和上线都用 pymongo 重新实现下

2024-05-15 10:58 UTC, lanheader commented on src/docker/setup.sh
>  mv /opt/mongodb-linux-x86_64-rhel70-3.6.20/bin/mongo /usr/local/bin/
这个我后续再调整一下

2024-05-15 11:06 UTC, LeoQuote commented on src/docker/setup.sh
>  mv /opt/mongodb-linux-x86_64-rhel70-3.6.20/bin/mongo /usr/local/bin/
```
root@archery-79d655bbb6-vjgmr:/opt# ls /lib/x86_64-linux-gnu/libcrypt.so.1*
/lib/x86_64-linux-gnu/libcrypt.so.1  /lib/x86_64-linux-gnu/libcrypt.so.1.1.0
```

我看是有的, 只是文件名不一样, 对这个文件能不能做个软链试试是否可行? 编译还是相对麻烦的而且还固定了版本

2024-05-15 11:08 UTC, lanheader commented on src/docker/setup.sh
>  mv /opt/mongodb-linux-x86_64-rhel70-3.6.20/bin/mongo /usr/local/bin/
这个是有问题的，使用的版本过高，mongo识别不了
<img width="892" alt="image" src="https://github.com/hhyo/Archery/assets/52522047/68a68674-5895-4ff9-9660-73585a9915f3">

2024-05-15 11:10 UTC, LeoQuote commented on src/docker/setup.sh
>  mv /opt/mongodb-linux-x86_64-rhel70-3.6.20/bin/mongo /usr/local/bin/
总结下来的话, 几个方案麻烦你参考下:
1. 升级命令行版本至 5 , 做对应修改
2. 装包, 做软链使其可以正常执行
3. 执行使用 pymongo 重写

2024-05-20 10:13 UTC, LeoQuote requested changes
当前的修复引入了旧版本的openssl ，含有安全漏洞，因此不接受pr ，有需要的可以自行打镜像

2024-05-27 05:34 UTC, closed without merging

2025-05-12 07:57 UTC, huangsijun17 commented
升级mongo shell版本呢？