存在检测错误或警告时，拒绝提交
hhyo/archer pull request #2692
Opened 2024-06-21 08:01 UTC by peixubin

存在检测错误或警告时，拒绝提交,避免一些错误的SQL提交执行

2024-06-21 08:08 UTC, peixubin commented
"Codecov token not found. Please provide Codecov token with -t flag." 是什么意思？是不是构建脚本有问题

2024-07-02 01:05 UTC, LeoQuote commented on sql/utils/workflow_audit.py
> +        reject = False
```suggestion
        should_reject = False
```

麻烦这里名字改为 should_reject , 上方的 auto_review 不要赋值

下方的 if 条件改为 

```
if self.is_auto_review() and not should_reject:
```

这样代码的可读性会更好一点

2024-07-02 01:29 UTC, LeoQuote requested changes

2024-07-02 01:29 UTC, LeoQuote commented on sql/utils/workflow_audit.py
> +        auto_review = self.is_auto_review()
此处的赋值没有意义，直接引用这个函数即可

2024-07-02 01:31 UTC, peixubin commented on sql/utils/workflow_audit.py
> +        reject = False
is_auto_review函数中会设置一个max_errlevel，表示脚本中最高级别的错误，用于判断是否可以自动pass。所以需要先运行is_auto_review，并保存返回值。

2024-07-02 01:36 UTC, peixubin commented on sql/utils/workflow_audit.py
> +        auto_review = self.is_auto_review()
is_auto_review函数的消耗相对比价大，不适合重复运行，auto_pass的判断依赖里面的逻辑，所以做结果缓存

2024-07-03 05:59 UTC, woshiyanghai commented
我是没有开启自动审核，sql检查如果有错误，或者警告，其实我认为应该可以提交，只是在审核区域不在展示，工单日志展示sql审核不通过。个人感觉稍微好一点？ 比如有一个场景，研发写了很大一段sql准备让提工单。但是一直审核有错误，如果不让他提交，他找dba看的时候，还需要把sql发送dba，然后好像比较麻烦？

2024-07-03 06:07 UTC, LeoQuote requested changes
我认为当前的实现还是有点混乱, 不需要把自动驳回和自动通过这两个逻辑混在一起.

自动驳回和自动通过这两个功能应该是相对独立的, 自动驳回优先. 所以你应该在最一开始的时候判断能否自动驳回, 这样就没有后来的自动通过的事情了.

2024-07-03 06:14 UTC, woshiyanghai commented
对，自动驳回并不是自动审核流程这两个是独立的。    所以在提交工单时，如果发现时自动驳回的单子，就直接设置为2，后续没有自动审核逻辑了。这样这个单子系统也能看到，不同级别有权限的也能看到，也又对应的日志。

2024-07-03 07:00 UTC, LeoQuote commented
https://github.com/hhyo/Archery/blob/52ce7595d4b3b6e294b49c4d9a4ce10a0992d60f/sql/utils/workflow_audit.py#L303-L316

2024-07-03 07:15 UTC, LeoQuote commented on sql/templates/sqlsubmit.html
> +                    // 是前端拦截了还是允许进入工作流？
允许进入工作流, 有记录好讨论

2024-07-03 07:16 UTC, peixubin commented
> 这一版还是和自动通过结合了, 在这一步之前再做一个处理, 如果 workflow status 是 autoreview_wrong ,那么就提前保存, return , 你看能不能解决你的问题.
> 
> https://github.com/hhyo/Archery/blob/52ce7595d4b3b6e294b49c4d9a4ce10a0992d60f/sql/utils/workflow_audit.py#L303-L316

对于自动驳回和自动通过是否结合，我不能理解。驳回或通过本来就是审核的两个动作，在create_audit里面必定会存在驳回或通过两个场景，这有什么值得疑问的？
大部分代码是原来就有的，我还不想去大动。我只是增加了对工单状态的判断。
`
239     def generate_audit_setting(self) -> AuditSetting:
240         if self.is_auto_review():
241             if self.workflow_type in [WorkflowType.SQL_REVIEW, WorkflowType.QUERY]:
242                 if self.workflow.status != "workflow_autoreviewwrong":
243                     return AuditSetting(auto_pass=True)

`

2024-07-03 07:27 UTC, peixubin commented on sql/templates/sqlsubmit.html
> +                    // 是前端拦截了还是允许进入工作流？
其实对于系统来说，还是先拦截比较好，不然容易产生大量的驳回工单。

2024-07-03 07:45 UTC, LeoQuote commented on sql/templates/sqlsubmit.html
> +                    // 是前端拦截了还是允许进入工作流？
那可以辛苦加一个系统配置控制这里的行为

2024-07-03 07:58 UTC, peixubin commented on sql/templates/sqlsubmit.html
> +                    // 是前端拦截了还是允许进入工作流？
我也是刚进入这个项目，整体还非常不熟悉，大的改动不敢做，目前我只是关注一些比较重要的问题。增加系统配置项，需要修改的地方挺多，我留着备注就是准备作为遗留问题处理

2024-07-03 08:03 UTC, LeoQuote commented on sql/templates/sqlsubmit.html
> +                    // 是前端拦截了还是允许进入工作流？
咱们不用着急, 如果是纯粹的注释不用提上来, 后续你想继续做可以继续提 pr, 这里实现二选一:
1. 和之前的行为保持一致, 进到工作流.
2. 提供一个系统配置项 , 可以更改此处的行为.

2024-07-03 08:06 UTC, peixubin commented on sql/templates/sqlsubmit.html
> +                    // 是前端拦截了还是允许进入工作流？
目前就是实现了1，和之前的行为一致。进入工作流，对于存在错误的工单，状态为“自动审核不通过”

2024-07-03 08:09 UTC, LeoQuote commented
可能之前表达的不清晰, 我重复表达下我的建议:
1. 是否自动驳回和是否自动通过是两个逻辑, 自动驳回优先, 先判断是否自动驳回, 再判断是否自动通过, 这样逻辑清晰, 容易理解, 不要混在一起. 
2. 驳回还是不驳回, 不适宜放在 `generate_audit_settings` 内, 就如这个函数名字描述的一样, 是生成工单对应的审批流, 是否自动通过, 审核节点是哪些, 等等. 驳回还是不驳回适宜放在 `create_audit` 内. 

希望你能理解.

2024-07-03 08:43 UTC, LeoQuote requested changes

2024-07-03 08:43 UTC, LeoQuote commented on sql/utils/workflow_audit.py
> +        ):
无需判断是否 auto_pass, 逻辑更清晰

```suggestion
        if self.workflow.status == "workflow_autoreviewwrong":
```

2024-07-03 08:45 UTC, peixubin commented on sql/utils/workflow_audit.py
> +        ):
我的想法是手工确认的模式下，不执行自动驳回

2024-07-03 08:46 UTC, LeoQuote commented on sql/utils/workflow_audit.py
> +        ):
不行, 你的这个需求是 breaking change 了, 需要做系统配置控制行为

2024-07-03 08:52 UTC, LeoQuote commented on sql/utils/workflow_audit.py
> +        ):
如果你需要, 可以独立成一个函数, `should_reject` , 然后你定制开发时覆盖这个函数即可. 这样也可以控制审批流的行为.

参考:
* https://github.com/hhyo/Archery/blob/52ce7595d4b3b6e294b49c4d9a4ce10a0992d60f/archery/settings.py#L71C5-L71C20 
* https://github.com/hhyo/Archery/blob/52ce7595d4b3b6e294b49c4d9a4ce10a0992d60f/sql/utils/workflow_audit.py#L746

2024-07-03 08:55 UTC, peixubin commented on sql/utils/workflow_audit.py
> +        ):
意思是对于错误工单，提交后可以修改？
这样当然是好的，但是这个状态怎么设置，没搞清楚

2024-07-03 09:00 UTC, LeoQuote commented on sql/utils/workflow_audit.py
> +        ):
错误工单提交的情况下, 提交者可以拿着驳回的工单跟系统管理员沟通, 不用使用截图之类的方法就可以顺畅的沟通.

你说的状态设置具体指的是什么? 我没看明白

2024-07-03 09:02 UTC, peixubin commented on sql/utils/workflow_audit.py
> +        ):
没搞懂“breaking change”是什么意思。
错误工单不应该驳回，还要参数控制？

2024-07-03 09:08 UTC, LeoQuote commented on sql/utils/workflow_audit.py
> +        ):
> 我的想法是手工确认的模式下，不执行自动驳回

错误工单应该驳回, 但是你刚刚的观点是, **只有自动审核通过, 且需要驳回的时候才驳回**, 我的观点是, **需要驳回就应该驳回, 不需其他条件**

如果说你想做 **只有自动审核通过, 且需要驳回的时候才驳回** , 那这个行为和之前的版本不一致, 是需要参数控制的.

2024-07-03 10:52 UTC, peixubin commented on sql/utils/workflow_audit.py
> +        ):
我表达的意思是在自动审核模式下，需要驳回的就驳回，而不是自动审核通过；在人工确认模式下，尽管有需要驳回的，仍可通过。
is_auto_review函数表达的仅仅是是否符合自动审核的条件，generate_audit_setting函数第一行，表达的就是只要符合自动审核条件，就不管其它了（最终体现在create_audit），我要修改的是这个逻辑

2024-07-03 10:54 UTC, peixubin commented on sql/utils/workflow_audit.py
> +        ):
我表达的意思是在自动审核模式下，需要驳回的就驳回，而不是自动审核通过；在人工确认模式下，尽管有需要驳回的，仍可通过。
is_auto_review函数表达的仅仅是是否符合自动审核的条件，generate_audit_setting函数第一行，表达的就是只要符合自动审核条件，就不管其它了（最终体现在create_audit），我要修改的是这个逻辑

2024-07-03 10:55 UTC, LeoQuote commented on sql/utils/workflow_audit.py
> +        ):
好的，那就需要参数控制，辛苦实现下。

2024-07-03 10:58 UTC, LeoQuote commented on sql/utils/workflow_audit.py
> +        ):
好的，那还是一样，你的新逻辑带来了breaking change，需要系统配置项来支持自定义，或者你也可以自己二次开发实现这个功能。

2024-07-03 11:10 UTC, peixubin commented on sql/utils/workflow_audit.py
> +        ):
前面我也问了，这个“breaking change”是什么意思，没搞明白。
在自动审核模式下，存在错误的工单，不应该驳回吗？ 还需要参数进行开关？

2024-07-03 11:14 UTC, LeoQuote commented on sql/utils/workflow_audit.py
> +        ):
breaking change 就是和之前版本不一致的行为，对于你的两个问题我就不重复回答了，请参照上方粗体部分的说明。

2024-07-03 11:15 UTC, peixubin commented on sql/utils/workflow_audit.py
> +        ):
我觉得需要分析的是，是否存在其它场景，不符合我实现的逻辑。

2024-07-03 11:23 UTC, LeoQuote commented on sql/utils/workflow_audit.py
> +        ):
这里可能还是有一些矛盾在的哈，我觉得我观点都表达到位了。如果没有代码改变，新的观点或论据，我就不反复沟通了。

2024-07-07 07:32 UTC, peixubin commented on sql/utils/workflow_audit.py
> +        ):
目前的实现与原来的逻辑基本没有差别了，只是在判断是否自动通过时，增加了对存在审核错误的检查，其实和最早的实现类似。
另外增加了一个系统参数，是否要允许错误脚本提交（仅自动审核模式下），目前是在客户端脚本里进行判断。

2024-08-24 10:37 UTC, hhyo commented
#2772 已处理

2024-08-24 10:37 UTC, closed without merging