增加系统通用字符串脱敏规则01、脱敏字段支持*
hhyo/archer pull request #2698
Opened 2024-06-25 03:55 UTC by feiazifeiazi

需求背景：
1. 实例很多， 所有库的字段共计100万+，不同环境的库名不一样，有后缀。
2. 敏感长度不一样。是全球化公司，电话，身份证，卡号长度完全不一样。

增加功能：
1. 增加系统通用的脱敏规则。规则：根据字段长度自动分成3份，中间段脱敏。
3. 脱敏字段配置时，支持对库名，表名使用*，不用再关心库名和表名，只用关心新增的敏感字段名，方便配置。

使用建议：
在配置脱敏字段时，只需要找出系统中phone,moblie,passowd等敏感的的字段名，向data_masking_columns表插入数据，不用再关心库名和表名。

不同长度的敏感字段脱敏效果：
![image](https://github.com/hhyo/Archery/assets/21078128/30028c39-43bd-45ef-be78-04a7d0ebb42e)

2024-06-28 10:51 UTC, LeoQuote commented
不好意思，我没太理解这里的通用脱敏规则的含义，能否帮忙再详细说明一下使用方法？

2024-07-01 10:15 UTC, feiazifeiazi commented
> 不好意思，我没太理解这里的通用脱敏规则的含义，能否帮忙再详细说明一下使用方法？
> 
> 方便的话写到代码中去一下。

通用脱敏规则：
1. 这个规则是将所有的字符串平均分成3份， 中间那份脱敏。 不用关心是不是 手机，邮箱，证件号，不需要一个个类型配置规则。
2. 就是一个正则表达式：^([\s\S]{2,})([\s\S]{2,})([\s\S]{2,})$ ， 正则的数据2是根据字段的长度动态计算的。

2024-07-01 10:25 UTC, feiazifeiazi commented
> > 不好意思，我没太理解这里的通用脱敏规则的含义，能否帮忙再详细说明一下使用方法？
> > 方便的话写到代码中去一下。
> 
> 通用脱敏规则：
> 
> 1. 这个规则是将所有的字符串平均分成3份， 中间那份脱敏。 不用关心是不是 手机，邮箱，证件号，不需要一个个类型配置规则。
> 2. 就是一个正则表达式：^([\s\S]{2,})([\s\S]{2,})([\s\S]{2,})$ ， 正则的数据2是根据字段的长度动态计算的。


使用方式和以前一样的。只是可以选择 “通用规则”。

![image](https://github.com/hhyo/Archery/assets/21078128/6487bd53-4550-4d95-9a48-044bcfa45497)

2024-07-01 10:40 UTC, LeoQuote commented
能否将名字改为"三段式通用脱敏规则", 这样更加好理解一些, 你觉得如何? 
还有可以考虑在model里预留几个槽位, 然后让管理员可以在系统配置中配置正则规则.
三段式的可以写死没问题, 我觉得这个确实是通用性很高

2024-07-01 11:05 UTC, feiazifeiazi commented
> 能否将名字改为"三段式通用脱敏规则", 这样更加好理解一些, 你觉得如何? 还有可以考虑在model里预留几个槽位, 然后让管理员可以在系统配置中配置正则规则. 三段式的可以写死没问题, 我觉得这个确实是通用性很高

1. 恩。新名字可以。 要不要加01呢。  这个规则只处理字符类型， 并没有处理金额等数字类型。
2. 正则一开始我是放开的。  我现在放开吧。

2024-07-01 11:17 UTC, LeoQuote commented
不用加01，你预留的槽位可以再加 01，02 一直到10

2024-07-01 11:18 UTC, LeoQuote commented
可以考虑适配下数字类型？

2024-07-02 01:59 UTC, feiazifeiazi commented
> 不用加01，你预留的槽位可以再加 01，02 一直到10

懵了。“model里预留几个槽位”  这句话不明白意思了。get不到点。

如果放开正则，正则配置是在“脱敏规则配置” 菜单里面配置的。

2024-07-02 02:25 UTC, feiazifeiazi commented
> 可以考虑适配下数字类型？

数字类型，没有具体的需求哎。

可能需求：把数字 乘于一个随机数？
可能需求：把第一位数字变成*？

2024-07-02 03:51 UTC, LeoQuote commented
不好意思, 我才关注到可以使用 脱敏规则设置和 脱敏字段配置 两个配置来结合, 配置脱敏规则, 那这样的话, 你当前的这个需求, 是不是可以直接用 `其他` 这个脱敏规则来实现? 

> 脱敏字段配置时，支持对库名，表名使用*，不用再关心库名和表名，只用关心新增的敏感字段名，方便配置。

我建议本次 pr 先加这个功能, 然后你用 "其他" 这个规则进行关联.

如果你想扩展这个功能, 比如说可以设置无限个脱敏规则, 可以扩展 其中的 `rule_type`, 使其支持很多的规则, 欢迎后续再提 pr .

对于数字类型的字段, 我比较建议转换为文本然后再做实现.

2024-07-02 07:18 UTC, feiazifeiazi commented
> 不好意思, 我才关注到可以使用 脱敏规则设置和 脱敏字段配置 两个配置来结合, 配置脱敏规则, 那这样的话, 你当前的这个需求, 是不是可以直接用 `其他` 这个脱敏规则来实现?
> 
> > 脱敏字段配置时，支持对库名，表名使用*，不用再关心库名和表名，只用关心新增的敏感字段名，方便配置。
> 
> 我建议本次 pr 先加这个功能, 然后你用 "其他" 这个规则进行关联.
> 
> 如果你想扩展这个功能, 比如说可以设置无限个脱敏规则, 可以扩展 其中的 `rule_type`, 使其支持很多的规则, 欢迎后续再提 pr .
> 
> 对于数字类型的字段, 我比较建议转换为文本然后再做实现.

1. 用“其他”这个规则实现不了需求。因为正则表达式必须要动态生成。
2.   需要新加一个规则“其他2” (或者叫 三段式通用脱敏规则)，正则需配置为"^([\\s\\S]{@Length01,}?)([\\s\\S]{@Length02,}?)([\\s\\S]{@Length03,}?)$"，然后需要代码支持将正则中的@Length01,@Length02,@Length03 替换为真正的数字的。

2024-07-03 05:35 UTC, LeoQuote requested changes
经过沟通确实了解了这个功能的实际用途, 请将规则的名字改为 "三段式通用脱敏规则", 其他 LGTM

2024-07-08 06:52 UTC, LeoQuote commented on sql/models.py
> +        help_text="通用规则01：根据字段长度自动分成3份，中间段脱敏。",
这里的名字没改，麻烦改一下

2024-07-08 06:53 UTC, LeoQuote commented on sql/utils/data_masking.py
> +                # 如果是默认的通用规则01，数据库没有查询结果，则创建一个对象。
这里也是

2024-07-08 06:53 UTC, LeoQuote commented on sql/utils/data_masking.py
> +                        rule_desc="系统通用规则01，内部实现，不需要修改。",
还有这里

2024-07-31 02:33 UTC, feiazifeiazi commented
@LeoQuote 已修复，麻烦再看一下。2024-7-31

2024-07-31 02:46 UTC, LeoQuote commented
rebase下到最新版，有冲突

2024-08-07 03:33 UTC, feiazifeiazi commented
> rebase下到最新版，有冲突

已rebase。

2024-08-07 05:36 UTC, LeoQuote approved these changes

2024-08-07 05:37 UTC, merged