修复工单审核不通过依然待审核展示的问题
hhyo/archer pull request #2712
Opened 2024-07-02 09:46 UTC by woshiyanghai

https://github.com/hhyo/Archery/issues/2699

2024-07-03 05:47 UTC, LeoQuote commented
pr 来迟了, 先 close 了, 有问题可以在这里讨论, 欢迎提出你的宝贵意见 https://github.com/hhyo/Archery/pull/2692

2024-07-03 12:32 UTC, LeoQuote requested changes
如果工单是自动审核的，会在上方的 is auto review 逻辑中提前返回，所以你的逻辑需要提前到最前方才可行

可以考虑写成 is autoreview error return

2024-07-04 00:57 UTC, woshiyanghai commented
确实有这个问题，修改一下。

2024-07-04 01:37 UTC, woshiyanghai commented
[自动审核不通过的时候,不再走自动审核逻辑](https://github.com/hhyo/Archery/pull/2712/commits/13ada5c8b78eb673ac4425933655abfb0adc339c)
这里描述有点不清楚了，应该是sql检测不通过时，不再走自动审核逻辑

2024-07-04 03:55 UTC, LeoQuote requested changes
这个逻辑写得复杂了, 你就写 if status == workflow_autoreviewwrong, 就自动驳回然后 提前return, 后面的 自动通过逻辑不变即可

2024-07-04 05:21 UTC, woshiyanghai commented
> 这个逻辑写得复杂了, 你就写 if status == workflow_autoreviewwrong, 就自动驳回然后 提前return, 后面的 自动通过逻辑不变即可

直接return的话，如果不记录sql_audit的话，查看工单detail的时候有点问题，而且工单没有日志记录，所以没有直接return，还是记录了audit 和audit_log 。

2024-07-04 05:40 UTC, woshiyanghai commented
> 这个逻辑写得复杂了, 你就写 if status == workflow_autoreviewwrong, 就自动驳回然后 提前return, 后面的 自动通过逻辑不变即可

我理解大佬你的意思是直接return 就不用在记录audit 和audit_log 了是么？可能我的理解不对，感谢大佬的指导

2024-07-04 07:37 UTC, LeoQuote commented
还是正常记录 audit 的, 只是提前 return, 这样下面的逻辑就不会走了
```
if status == workflow_autoreviewwrong:
    # 记录 audit
    # 记录 audit log
    return "工单已自动驳回"
```

这样你即使后面写 if audit_setting.auto_pass: 也能正常驳回

你看看这么写是否符合预期

2024-07-04 09:45 UTC, LeoQuote commented
辛苦再写一点单元测试, 测试一下自动驳回的工单表现是否正常, 就可以了

2024-07-08 10:04 UTC, woshiyanghai commented
> 辛苦再写一点单元测试, 测试一下自动驳回的工单表现是否正常, 就可以了

单元测试不会写，我在我项目部署测试了一下，功能正常

2024-07-17 05:58 UTC, LeoQuote commented on common/templates/config.html
> +                                       class="col-sm-4 control-label">QUERY_LOW_PEAK_START</label>
不同功能请分开提交pr谢谢

2024-07-17 06:01 UTC, woshiyanghai commented on common/templates/config.html
> +                                       class="col-sm-4 control-label">QUERY_LOW_PEAK_START</label>
好的，这个pr有点乱糟糟的了，我关闭掉，都分开提可以么？

2024-07-17 06:04 UTC, LeoQuote commented on common/templates/config.html
> +                                       class="col-sm-4 control-label">QUERY_LOW_PEAK_START</label>
不要关掉这个pr，可以使用 git reset 或 git rebase 然后 force push 的方式修建commit，开新pr会损失之前的讨论

2024-08-24 10:35 UTC, closed without merging

2024-08-24 10:37 UTC, hhyo commented
#2772