在线查询 支持AI根据描述生成查询语句
hhyo/archer pull request #2726
Opened 2024-07-15 08:21 UTC by QSummerY

2024-07-15 09:31 UTC, LeoQuote commented on archery/settings.py
> +DEFAULT_CHAT_MODEL = env("DEFAULT_CHAT_MODEL")
archery 内部有套后台系统可以配置这些东西, 用后台配置吧, 不用环境变量, 另外需要探测如果三个都没配置, 那就代表 AI 功能没打开, 需要隐藏相关的 UI

2024-07-15 09:32 UTC, LeoQuote commented on archery/settings.py
> +DEFAULT_CHAT_MODEL = env("DEFAULT_CHAT_MODEL")
https://github.com/hhyo/Archery/blob/52ce7595d4b3b6e294b49c4d9a4ce10a0992d60f/common/config.py#L15

https://github.com/hhyo/Archery/blob/master/common/templates/config.html

2024-07-16 13:10 UTC, LeoQuote commented on common/utils/openai.py
> +        tips = f"你是一个熟悉 {db_type} 的工程师, 我会给你一些基本信息和要求, 你会生成一个查询语句给我使用, 不要返回任何注释和序号, 仅返回查询语句"
这部分的模板能否也开放给用户定制，用django的模版引擎

2024-07-17 02:09 UTC, nick2wang commented
建议可以自定义配置base_url，国内很多AI模型都兼容openai接口规范，这样只要配置接口地址+key就可以很方便接入其他AI
例如通义千问：
https://help.aliyun.com/zh/dashscope/developer-reference/compatibility-of-openai-with-dashscope

2024-07-17 02:29 UTC, QSummerY commented
> 建议可以自定义配置base_url，国内很多AI模型都兼容openai接口规范，这样只要配置接口地址+key就可以很方便接入其他AI 例如通义千问： https://help.aliyun.com/zh/dashscope/developer-reference/compatibility-of-openai-with-dashscope

在系统配置的配置项管理中提供了 base_url + key + default_chat_model 的自定义配置

2024-07-17 06:46 UTC, QSummerY commented on common/utils/openai.py
> +        tips = f"你是一个熟悉 {db_type} 的工程师, 我会给你一些基本信息和要求, 你会生成一个查询语句给我使用, 不要返回任何注释和序号, 仅返回查询语句"
如上图所示，数据库类型会根据右侧所选的实例类型更新，并可以自定义输入

2024-07-17 08:00 UTC, LeoQuote requested changes

2024-07-17 08:00 UTC, LeoQuote commented on sql/templates/sqlquery.html
> +                    <input id="btn-generatesql" type="button" class="btn btn-info" style="display: none" value="生成SQL"/>
麻烦这里加一个❓的 tooltip, 说明一下哪些数据会被发送至 AI, 哪些不会比如
```
我们会收集你选择表的表结构, 数据库类型, 以及你在此输入框内输入的信息, 交由 AI 进行生成SQL, 生成的 SQL 会供你使用, 之后由你进行SQL查询, 查询出来的数据不会发送至 AI
```

文案可以再润色调整下

2024-07-17 08:00 UTC, LeoQuote commented on sql/templates/sqlquery.html
> +                    <input id="generatePrompt"class="form-control" style="display: none" placeholder="AI 查询提示词" value="{{openai_prompt}}" />
不好意思, 我可能说得有些歧义, 我意思是管理员可以配置 prompt 模板, 这样如果管理员发现默认 prompt 不太满足需求的时候, 可以调整 prompt 模板.

prompt 模板开放给用户可能不算太好, 可能会被滥用, 我建议这一版只给管理员开放调整 prompt 模板的入口.

2024-07-17 10:02 UTC, QSummerY commented on sql/templates/sqlquery.html
> +                    <input id="btn-generatesql" type="button" class="btn btn-info" style="display: none" value="生成SQL"/>
> 仅此操作会与 AI 交互, 收集数据库类型、表结构以及输入框信息, 交给 AI 生成 SQL 并置于下面的语句框中
文案调整如上

2024-07-17 10:03 UTC, QSummerY commented on sql/templates/sqlquery.html
> +                    <input id="generatePrompt"class="form-control" style="display: none" placeholder="AI 查询提示词" value="{{openai_prompt}}" />
已修改增加 default_query_template 配置

2024-07-17 10:10 UTC, LeoQuote commented on common/utils/openai.py
> +        self.default_query_template = all_config.get("default_query_template", "")
辛苦在这里做一个默认值, 并将默认值也写在 config.html 内, 供需要定制的管理员参考.

2024-07-17 10:12 UTC, LeoQuote commented on common/utils/openai.py
> +        self.default_chat_model = all_config.get("default_chat_model", "")
model 也做一个默认值, 同样也写在 config.html 里的 help text 里, 默认值就 gpt-3.5-turbo 吧

2024-07-17 10:13 UTC, LeoQuote commented on common/utils/openai.py
> +            )
有默认值的话这段逻辑就不用了🤔

2024-07-18 01:55 UTC, LeoQuote approved these changes

2024-07-18 01:56 UTC, merged

2025-04-17 08:56 UTC, ocpeng commented
![image](https://github.com/user-attachments/assets/276bba0a-dde7-4687-8c9b-048efc868d1b)
![image](https://github.com/user-attachments/assets/3fc79ff3-d3b0-48b1-8ea8-ab7e62fb36f2)
这个怎么用？点了没反应？请求也成功了
每次都要选择表，这个Ai只能单表出sql么？