添加新的数据源ES(Elasticsearch)
hhyo/archer pull request #2754
Opened 2024-08-08 11:08 UTC by feiazifeiazi

待补充。

2024-08-09 03:58 UTC, LeoQuote commented
感谢贡献，关于es 支持有几个问题，可能在实现之前要仔细思考一下：
1. 和kibana 对比，archery 有什么核心优势
2. json的响应，如何友善展示
3. 脱离了kibana 后如何写查询？
4. 数据源如何管理，管理员添加集群等级的鉴权，用户自己添加索引pattern然后进行查询
5. 授权如何管理，人员如何申请授权，如何精确控制授权

2024-08-09 05:50 UTC, feiazifeiazi commented
> 感谢贡献，关于es 支持有几个问题，可能在实现之前要仔细思考一下：
> 
> 1. 和kibana 对比，archery 有什么核心优势
> 2. json的响应，如何友善展示
> 3. 脱离了kibana 后如何写查询？
> 4. 数据源如何管理，管理员添加集群等级的鉴权，用户自己添加索引pattern然后进行查询
> 5. 授权如何管理，人员如何申请授权，如何精确控制授权

1. 核心优势是archery集合了多种数据源，用一个平台可以查询。现在加多支持ES。
2. 结果展示和mongo一样的，或说和关系型数据库一样的展示。
3. 脱离kibana 后如何写查询， 查询是一样的写。只是没有智能提示。
4.  数据源如何管理? 目前是查询所有*.
5. 精确控制授权， 和其他数据库是一样的。 选择库，选择表授权，验证权限。

2024-08-09 09:42 UTC, feiazifeiazi commented
@LeoQuote 已提交初始版，麻烦审一下。

2024-08-12 04:16 UTC, LeoQuote commented on sql/engines/elasticsearch.py
> +        return "Elasticsearch 引擎"
```suggestion
    name: str = "elasticsearch"
    info: str = "Elasticsearch 引擎"
```

这么写能少写一点测试

2024-08-12 04:30 UTC, LeoQuote requested changes

2024-08-12 04:30 UTC, LeoQuote commented on sql/engines/elasticsearch.py
> +                    verify_certs=False,  # 关闭证书验证
这里能否放在选项中让用户可以更改, 证书验证可以防止中间人攻击, 是网络安全中重要的一环

2024-08-12 04:30 UTC, LeoQuote commented on sql/engines/elasticsearch.py
> +        return True
没有实际逻辑可以删除, base 里有默认方法

2024-08-13 03:48 UTC, feiazifeiazi commented on sql/engines/elasticsearch.py
> +                    verify_certs=False,  # 关闭证书验证
我先开启证书验证。  后续加是否忽略证书，加CA证书。

2024-08-13 03:48 UTC, feiazifeiazi commented on sql/engines/elasticsearch.py
> +        return True
好的。已删除。

2024-08-13 04:02 UTC, LeoQuote requested changes

2024-08-13 04:02 UTC, LeoQuote commented on sql/engines/elastic_search_engine_base.py
我猜测你是想做两个实现, 一个 es, 一个 opensearch, 但当前这个代码量不是很适合拆分, 才300多行, 即使后续加上 opensearch 的 engine, 也不到一千行

2024-08-13 04:02 UTC, LeoQuote commented on sql/engines/test_elasticsearch.py
> +        self.assertEqual(self.engine.info, "Elasticsearch 引擎")
这个测试可以删了

2024-08-13 04:06 UTC, feiazifeiazi commented on sql/engines/elastic_search_engine_base.py
对。2个实现。 opensearch代码写完了，也测试了。但代码差不多一样的，有小小区别而已。 想了想还是提取一个父类。

2024-08-13 04:08 UTC, feiazifeiazi commented on sql/engines/test_elasticsearch.py
> +        self.assertEqual(self.engine.info, "Elasticsearch 引擎")
好的。

2024-08-13 04:10 UTC, feiazifeiazi commented on sql/engines/elastic_search_engine_base.py
目前就1个区别：self.conn.cat.indices方法返回类型区别。

驱动不一样不算哈。

2024-08-13 04:19 UTC, LeoQuote commented on sql/engines/elastic_search_engine_base.py
类拆分没问题,我意思是依然可以放在一个文件里

2024-08-13 05:34 UTC, feiazifeiazi commented on sql/engines/elastic_search_engine_base.py
> 类拆分没问题,我意思是依然可以放在一个文件里

好的。我合并一下。 怪不得一个文件里面全是类。
其他语言不这样干吧。一个类一个文件，尽量简单吧。

2024-08-13 07:19 UTC, LeoQuote commented on sql/engines/elastic_search_engine_base.py
直接读的话还是放一起简单一点, 读的时候都不需要 ide, 网页上就能看明白, 不然多个文件必须上 ide

2024-08-13 07:36 UTC, LeoQuote commented on sql/engines/elasticsearch.py
> +from click import command
麻烦清理下这里的 import, command, time, os 应该都是没用到的

2024-08-13 07:38 UTC, LeoQuote commented on requirements.txt
> +elasticsearch==8.14.0
```suggestion
elasticsearch==8.14.0

```

2024-08-13 09:59 UTC, feiazifeiazi commented on requirements.txt
> +elasticsearch==8.14.0
好的。加上空行。

2024-08-13 11:36 UTC, LeoQuote approved these changes

2024-08-13 11:47 UTC, merged

2024-09-17 01:52 UTC, yangguocang commented
给个赞, 一直想把ES集成到archery, 没想到竟然已经实现了

2024-09-17 14:38 UTC, yangguocang commented
哇塞 仔细一看 竟然就是我去年底在discussion 提出的支持ES的想法   感谢 @feiazifeiazi