实例增加2个字段：是否忽略证书选项和允许显示的数据库列表
hhyo/archer pull request #2781
Opened 2024-09-02 06:54 UTC by feiazifeiazi

1. 实例表 增加字段is_ignore_certificate_error。'是否忽略证书错误。1：忽略。0：不忽略，需要验证';
2. 实例表 增加字段allow_db_name_list 。 '允许显示的数据库列表，多个以逗号隔开，支持*和~。';
 允许显示的数据库列表字段使用场景：
   一个数据库实例可以会部署多个系统，(当然了一个系统是有多个库)
    方案1： 假如部署了3个系统，需要创建3个archery实例。至少需要在数据库建立3个帐号。
    方案2：创建3个archery实例，配置显示数据库列表字段，在“SQL查询”，“SQL上线”等显示数据库列表时，将会进行筛选。

     PS：此字段对于多系统不想创建多帐号共享使用数据库实例比较友好。我这边Mongo都是配置管理员帐号，5个系统共用的。 Redis更是10多个系统使用。

2024-09-02 08:06 UTC, LeoQuote commented
这些字段都是比较正常的字段, 但是我最近是发现instance 级别的字段已经有点太多了, 有很多字段也不需要去用它来过滤什么的, 你觉得有没有可能设置一个 varchar 或者 text 字段用来存 json, 这样之后再加字段也不需要改表了.

2024-09-02 09:50 UTC, feiazifeiazi commented
> 这些字段都是比较正常的字段, 但是我最近是发现instance 级别的字段已经有点太多了, 有很多字段也不需要去用它来过滤什么的, 你觉得有没有可能设置一个 varchar 或者 text 字段用来存 json, 这样之后再加字段也不需要改表了.

instance 级别的字段多吗？sql_instance表也才20多个字段而已。
我们这是B端系统，不到190个字段，应该继续用方案1，性能不是问题。建议还是等实现了很多需求后看情况。

方案1：在现有表上继续加字段。
方案2：加多一个扩展属性表(1对1)。主键同sql_instance表。
方案3：加多一个扩展属性表(1对多)。 主键+key 是唯一的。
方案4： 用一个json存储，key value的数据。

2024-09-02 11:14 UTC, LeoQuote commented
主要还是说以后加字段不用再加改表, 往里面塞就行了, 这才是真的简单, 以后加了字段也不用写改表语句, 如你所说性能不用太考虑, 一般人也不会在这里加一些太大太长的东西

2024-09-03 02:13 UTC, feiazifeiazi commented
> 主要还是说以后加字段不用再加改表, 往里面塞就行了, 这才是真的简单, 以后加了字段也不用写改表语句, 如你所说性能不用太考虑, 一般人也不会在这里加一些太大太长的东西
> 
> 嗯, json 字段也不错


用单个字段存储后， 
那前端如何输入？是显示一个个字段？  
写代码时，可以直接引属性 使用的？
只是保存时用json格式吧。

2024-09-03 04:34 UTC, LeoQuote commented
你说的也是需要考虑的事情, 你可以尝试下看看我们能不能定制 model 或者 admin 页面, 让其可以支持 json 字段的友好修改, 体验和之前也差不多.

如果要是不行的话, 那就没办法了, 只能按你之前的方案来了.

另外, 我比较建议的是, 设置两个字段, 允许显示的数据库 pattern, 不允许显示的数据库 pattern, 都采用正则的方式输入, 这样实现起来也比较简单, 不需要做逗号分隔等等.

2024-09-03 06:06 UTC, feiazifeiazi commented
> 你说的也是需要考虑的事情, 你可以尝试下看看我们能不能定制 model 或者 admin 页面, 让其可以支持 json 字段的友好修改, 体验和之前也差不多.
> 
> 如果要是不行的话, 那就没办法了, 只能按你之前的方案来了.
> 
> 另外, 我比较建议的是, 设置两个字段, 允许显示的数据库 pattern, 不允许显示的数据库 pattern, 都采用正则的方式输入, 这样实现起来也比较简单, 不需要做逗号分隔等等.

支持 json 字段的友好修改及使用比较难。

1.我故意屏蔽了正则。只让他支持*和~。 用正则是不是对运营人员来说成本高？用逗号简单。
2. 不允许显示的字段可以加加。

2024-09-03 06:52 UTC, LeoQuote commented
正则应该不会太难, 很多现有的配置就是用的是正则, 正则可以给管理员更多发挥空间

2024-09-04 04:39 UTC, LeoQuote commented on sql/engines/__init__.py
> +            self.is_ignore_certificate_error = instance.is_ignore_certificate_error
这里不用赋值, 直接用 instance 的属性就行

2024-09-04 04:39 UTC, LeoQuote commented on sql/models.py
> +    is_ignore_certificate_error = models.BooleanField("是否忽略证书错误", default=False)
```suggestion
    verify_ssl= models.BooleanField("是否验证服务端SSL证书", default=True)
```

显示的不贴切的化你再润色下

2024-09-05 01:47 UTC, feiazifeiazi commented on sql/models.py
> +    is_ignore_certificate_error = models.BooleanField("是否忽略证书错误", default=False)
这个字段 应该以默认值为False起名的。

在insert数据，或变量的初始化，数据库字段没有映射到程序属性时， 值一般都是False的。
我们的预期是 验证SSL证书的。此时会变为不验证了。

2024-09-05 02:34 UTC, feiazifeiazi commented on sql/engines/__init__.py
> +            self.is_ignore_certificate_error = instance.is_ignore_certificate_error
不行吧？ 直接没法使用，类会没有这个属性的。

2024-09-05 03:10 UTC, LeoQuote commented on sql/models.py
> +    is_ignore_certificate_error = models.BooleanField("是否忽略证书错误", default=False)
对，你再调整下逻辑，不要表达成忽略证书错误，请求时调的参数就是verify_ssl 尽量保持一致减少沟通成本

2024-09-05 03:11 UTC, LeoQuote commented on sql/engines/__init__.py
> +            self.is_ignore_certificate_error = instance.is_ignore_certificate_error
你试试呗，报错了？

2024-09-05 03:11 UTC, LeoQuote commented on sql/engines/__init__.py
> +            self.is_ignore_certificate_error = instance.is_ignore_certificate_error
self.instance.foo

2024-09-05 03:24 UTC, feiazifeiazi commented on sql/engines/__init__.py
> +            self.is_ignore_certificate_error = instance.is_ignore_certificate_error
> 你试试呗，报错了？

我试的是 self.foo，会报错。我试试self.instance.foo

2024-09-05 04:15 UTC, LeoQuote requested changes

2024-09-05 04:15 UTC, LeoQuote commented on sql/utils/sql_utils.py
> +    return filtered_list
这两个函数可能有点重复, 可以合成一个函数, 加上参数指明是 match 还是不match 就行了

2024-09-05 04:15 UTC, LeoQuote commented on sql/utils/sql_utils.py
> +    return filtered_list
另外是加一下这个函数的测试, 谢谢

2024-09-05 04:27 UTC, LeoQuote commented on sql/engines/redis.py
> +        db_list = filter_denied_db_list(db_list, self.instance.denied_db_name_regex)
我注意到你是在 engine 层面引用这个函数, 我想这个方法有可能被很多的功能引用到, 包括如下:
1. 上线申请
2. 查询申请
3. 查询
4. 数据字典
5. 数据库进程或实例管理

按理说前三个过滤我觉得很合理, 但后两个就不是特别合理了.

而且这样加引用每个 engine 都要加, 还是相对麻烦的, 有没有可能在需要过滤的功能内部去加这个机制?

2024-09-05 05:39 UTC, feiazifeiazi commented on sql/engines/redis.py
> +        db_list = filter_denied_db_list(db_list, self.instance.denied_db_name_regex)
5个地方都合理喔。 就是要控制所有地方的数据库显示列表：要么通过帐号权限控制数据库列表，要么是通过这2个正则过滤。
如果要显示所有的数据库，使用者应该新建一个不筛选的实例。

2024-09-05 05:40 UTC, feiazifeiazi commented on sql/utils/sql_utils.py
> +    return filtered_list
合并也行。

2024-09-05 05:42 UTC, feiazifeiazi commented on sql/utils/sql_utils.py
> +    return filtered_list
> 另外是加一下这个函数的测试, 谢谢

有地方调用地方，就会有测试用例，就会覆盖到。 要单独写测试用例？

2024-09-05 12:00 UTC, LeoQuote commented on sql/engines/redis.py
> +        db_list = filter_denied_db_list(db_list, self.instance.denied_db_name_regex)
要不这样吧，把这个方法移动到base或者保持原样，然后在上层调用，主要是在每个engine 里写太麻烦了，view里也就是五六处吧，还是比较有限的，engine 里就可能有无限的地方要改

2024-09-06 01:53 UTC, feiazifeiazi commented on sql/engines/redis.py
> +        db_list = filter_denied_db_list(db_list, self.instance.denied_db_name_regex)
1. 这个方法放在EngineBase类,我没敢放。 那我改到这个地方。
2. OK，改为在上层调用。 子类get_all_databases方法就不要调用了。 我理解的上层是instance.instance_resource方法里面喔。 就是调用get_engine(instance=instance)获取实现类，调用get_all_databases的地方，对否？
![image](https://github.com/user-attachments/assets/d0c001a7-07b8-4dda-bf36-b7d8d0eb1682)

2024-09-06 02:57 UTC, LeoQuote commented on sql/engines/redis.py
> +        db_list = filter_denied_db_list(db_list, self.instance.denied_db_name_regex)
是这个区域没错👍

2024-09-06 03:05 UTC, LeoQuote commented
单元测试建议还是加一批独立测试的, 另外调用时建议使用 named argument, 不然会看起来难以理解.

需要测到各种场景, 比如 pattern 是空字符串之类的

2024-09-19 09:16 UTC, feiazifeiazi commented on sql/engines/redis.py
> +        db_list = filter_denied_db_list(db_list, self.instance.denied_db_name_regex)
过滤数据库改为 database列表统一出口的地方了。 过滤数据库放在sql_utils.py方法里了，并将sql_utils相关方法单元测试类 独立出来了。

2024-09-19 09:25 UTC, feiazifeiazi commented
@LeoQuote 已修改。

1. 过滤数据库改为 database列表统一出口的地方了。 
2. 过滤数据库放在sql_utils.py类里面，并添加了几个单元测试。sql_utils相关方法单元测试类 独立出来了。
3. 已重新测试，功能正常。

2024-09-19 09:29 UTC, LeoQuote requested changes

2024-09-19 09:29 UTC, LeoQuote commented on sql_api/api_instance.py
> +                    resource.rows, query_engine.instance.show_db_name_regex, True
```suggestion
                    resource.rows, query_engine.instance.show_db_name_regex, is_match_regex=True
```

建议这么写, 可读性会更好一点, 下面的用法也是类似

2024-09-19 09:59 UTC, LeoQuote approved these changes

2024-09-19 09:59 UTC, merged

2025-04-25 10:00 UTC, sona-yuan commented
verify_ssl 字段和is_ssl字段是否有点重复呀