删除 oracle engine 中 filter_sql 实现
hhyo/archer pull request #2797
Opened 2024-09-09 08:07 UTC by hhw007

1. oracle.py646行filter_sql函数作用是限制查询返回行数。如果查询SQL的查询字段列表包含同名列，经过filter_sql函数处理之后的SQL，
由于查询字段列表` sql_audit.* `中存在同名列，在Oracle数据库中执行会报错` ORA-00918:未明确定义列`。原查询SQL的查询字段列表虽然也包含同名列，
但因为有不同的表别名作区分，因此在数据库中执行不会报错。例如原SQL：

```
select a.*,b.* from a,b where a.custid=b.custid;

```

该SQL在Oracle数据库中可以正常执行，但在archery平台上执行会报错。

2. oracle.py中689行cursor.fetchmany(int(limit_num))已经有限制查询返回行数的作用，所以不必通过oracle.py646行的filter_sql函数来再次限制查询返回行数

2024-09-09 08:39 UTC, hhw007 commented
上面的描述信息显示有些问题，星号“*”被忽略掉了。例如原SQL：select a.星号,b.星号 from a,b where a.custid=b.custid;

2024-09-09 08:46 UTC, LeoQuote commented
不要注释，没有作用的代码直接删除即可

2024-09-09 09:05 UTC, hhw007 commented
好的，我这边重新修改，重新提交PR吧

2024-09-09 09:25 UTC, hhw007 commented
注释的代码，我已经去掉了，麻烦审阅一下

2024-09-10 01:11 UTC, hhw007 commented
代码你看下能否合并吗？这个问题出现很久了

2024-09-10 06:48 UTC, hhw007 commented
我已经删除oracle.py中filter_sql函数了

2024-09-10 06:49 UTC, LeoQuote requested changes

2024-09-10 06:49 UTC, LeoQuote commented on sql/query.py
> +        if instance.db_type != "oracle":
不用改这里，EngineBase 自带这个方法做兜底、有错误？

2024-09-10 06:57 UTC, hhw007 commented on sql/query.py
> +        if instance.db_type != "oracle":
好的，我把这个地方还原回去

2024-09-10 07:13 UTC, hhw007 commented
应该没问题了

2024-09-10 10:25 UTC, hhw007 commented on sql/query.py
> +        if instance.db_type != "oracle":
这里已经还原回去了，没有错误

2024-09-11 01:24 UTC, hhw007 commented
大佬再帮忙看下，应该没问题了

2024-09-11 03:04 UTC, LeoQuote approved these changes

2024-09-11 03:04 UTC, merged