修复mongo上线问题
hhyo/archer pull request #2803
Opened 2024-09-12 05:30 UTC by smqyisyy

在使用未开启密码认证的实例上，会出现mongo的上线报错，因为代码中强制使用了账号密码登录的方式
找到了之前的#1893，加入几个判断可以解决，我改好了提了个pr

2024-09-12 06:38 UTC, LeoQuote requested changes
这里的代码复用有点少, 能否帮忙优化一下, 渲染时先做无用户名密码的情况, 然后有用户名密码就加上对应的参数

2024-09-12 07:29 UTC, smqyisyy commented
https://github.com/hhyo/Archery/pull/2805，新的优化改好了，可以看看是否符合预期

2024-09-12 07:56 UTC, LeoQuote requested changes

2024-09-12 07:56 UTC, LeoQuote commented on sql/engines/mongo.py
> +                    "{mongo} --quiet -u {uname} -p '{password}' {host}:{port}/{auth_db} <<\\EOF\n"
你把这个参数放在最后面可行吗? 这样你就不用写 if else 这么长了

2024-09-12 08:48 UTC, smqyisyy commented on sql/engines/mongo.py
> +                    "{mongo} --quiet -u {uname} -p '{password}' {host}:{port}/{auth_db} <<\\EOF\n"
嗯，这里把公共参数提取出来了，根据不同情况判断完拼接好的参数最后再返回

2024-09-12 09:43 UTC, smqyisyy commented on sql/engines/mongo.py
> +                    "{mongo} --quiet -u {uname} -p '{password}' {host}:{port}/{auth_db} <<\\EOF\n"
有空的时候看看这里新的是不是符合预期的

2024-09-12 10:01 UTC, LeoQuote commented
lint 必须要修好哈

2024-09-13 09:01 UTC, smqyisyy commented
这里修复了lint问题了，可以看看了

2024-09-13 09:03 UTC, LeoQuote requested changes
多谢贡献, build_cmd 这块逻辑有点多容易出错, 能否帮忙加一下单元测试, 因为只是字符串操作测试加起来应该不难, 请参考历史的单元测试或者  https://github.com/hhyo/Archery/wiki/development

2024-09-14 02:00 UTC, smqyisyy commented
这里历史只看到开发环境的搭建过程，不知道这个测试具体是如何操作？没有做过测试，可否细致描述一下具体流程？

2024-09-18 02:11 UTC, smqyisyy commented
这样应该是测试加入完成了？有空可以瞅瞅

2024-09-18 02:49 UTC, LeoQuote approved these changes

2024-09-18 02:50 UTC, LeoQuote commented
看完了没问题👌🏿

2024-09-18 02:50 UTC, merged