修改debug api，完善部分系统信息
hhyo/archer pull request #396
Opened 2019-08-24 16:58 UTC by hhyo

相关PR：#385

补全inception、运行环境、系统配置、依赖包信息，最终结构如下

访问地址：http://139.199.0.191/api/info

```
system_info = {
        'archery': {
            'version': archery.display_version
        },
        'inception': {
            'enable_goinception': sys_config.get('go_inception'),
            'inception_info': inception_info,
            'goinception_info': goinception_info,
            'backup_info': backup_info
        },
        'runtime_info': {
            'python_version': platform.python_build(),
            'mysql_info': mysql_info,
            'redis_info': redis_info,
            'sys_argv': sys.argv,
            'platform': platform.uname()
        },
        'sys_config': sys_config,
        'packages': installed_packages_list
    }
```

2019-08-24 17:50 UTC, LeoQuote requested changes
那你这个info，可能要管理员权限了，不然登录用户就能看到这个也是不太好。

或者info可以普通用户看到，就是一些静态信息，渲染也很快。

debug只有管理员可以看到，可能要取一些资源。

django Q有些api可以拿状态，但是感觉不好调试，我在Windows上就老出问题，蛋疼

2019-08-25 00:52 UTC, hhyo commented
感觉这个接口就是给管理员排查问题用，普通用户也没必要看这些，是不是限制管理员访问更合理，虽然里面把密码连接信息都隐藏了，还有现在问题是sysconfig和packages信息比较多，不确定全都是有效信息

2019-08-25 04:39 UTC, LeoQuote commented
嗯管理员权限好

或者看一下我上面的评论，debug多一点，info少一点

2019-08-25 04:39 UTC, LeoQuote commented
管他有效没效都先写到debug里😂

也可以考虑输出yaml？yaml人和机器都能读

2019-08-25 04:46 UTC, hhyo commented
咋输出yaml，没用过，你有时间的话可以按你的想法调整下，或者等下版也行，准备这个合了发一版

2019-08-25 04:57 UTC, LeoQuote commented
那你把管理员权限加上，普通用户有权限看到这个不合适

2019-08-25 06:45 UTC, hhyo commented
增加了django_q的信息
```
'django_q': {
            'version': django_q_version,
            'conf': django_q.conf.Conf.conf,
            'q_cluster_stats': q_cluster_stats,
            'q_broker_stats': q_broker_stats
        },
```

2019-08-25 06:50 UTC, merged