Feature/ding2person
hhyo/archer pull request #447
Opened 2019-09-12 03:46 UTC by yyukai

2019-09-12 04:05 UTC, yyukai commented
支持发送钉钉通知到个人，包括通知审核消息，执行完毕的通知消息。

2019-09-12 04:14 UTC, LeoQuote requested changes
用django_redis ，合并1.7.0 发布

2019-09-12 04:14 UTC, LeoQuote commented on src/init_sql/v1.7.0_v1.7.1.sql
> +  add ding_user_id varchar(50) default null comment '钉钉user_id';
改到 1.7.0？ 1.7.0 还没发布

2019-09-12 04:14 UTC, LeoQuote commented on sql/utils/ding_api.py
> +rs = redis.StrictRedis(host="127.0.0.1", port=6379, password=CACHES['default']['OPTIONS']['PASSWORD'], db=2)
建议用 django_redis 拿到redis connection，不用自己选配置 ，参考 http://django-redis-chs.readthedocs.io/zh_CN/latest/

2019-09-12 04:21 UTC, hhyo commented on sql/utils/ding_api.py
> +rs = redis.StrictRedis(host="127.0.0.1", port=6379, password=CACHES['default']['OPTIONS']['PASSWORD'], db=2)
django的cache方法能执行相关命令的吧

2019-09-12 04:44 UTC, LeoQuote commented on sql/utils/ding_api.py
> +rs = redis.StrictRedis(host="127.0.0.1", port=6379, password=CACHES['default']['OPTIONS']['PASSWORD'], db=2)
嗯，能，不过这个拿到connection应该要改的代码最少

2019-09-16 14:37 UTC, LeoQuote approved these changes
LGTM

2019-09-17 00:44 UTC, hhyo approved these changes

2019-09-17 00:44 UTC, merged

2019-09-29 03:28 UTC, hhyo commented on common/templates/config.html
> +                                    <label for="ding_corp_id"
原授权方式以及无法添加新用户，参考新的授权使用AppKey和AppSecret来换取access_token
https://ding-doc.dingtalk.com/doc#/bgb96b/ok9au2

2019-09-29 03:28 UTC, hhyo commented on common/templates/config.html
> +                                               placeholder="企业的访问密钥">
修改为AppSecret

2019-09-29 03:28 UTC, hhyo commented on sql/utils/ding_api.py
> +        resp = requests.post(url, data)
post参数需要使用json，requests.post(url, json=data)，否则会报错
同时钉钉已更新新的工作通知接口https://ding-doc.dingtalk.com/doc#/serverapi2/pgoxpy

2019-09-29 03:28 UTC, hhyo commented on sql/utils/ding_api.py
> +        ding_user_id = rs.execute_command('GET {}'.format(username.upper()))
redis存储信息时是没有username.upper()的，会导致两边不一致，获取不到数据