Archeryk8s
hhyo/archer pull request #462
Opened 2019-09-28 13:34 UTC by jerryhu1234

添加archery helm 在src目录下

2019-09-28 13:59 UTC, LeoQuote requested changes
怎么是个sub module，可以改成直接提交吗？

2019-09-29 02:22 UTC, jerryhu1234 commented
> 怎么是个sub module，可以改成直接提交吗？
不好意思，去掉了.git目录，已重新提交。

2019-09-29 09:02 UTC, LeoQuote commented
没想到这么大, redis 和 mysql 的可以使用 stable/redis, stable/mysql 吗, 然后只在values 中写value

goinception 的可以暂时放项目里, 也建议直接提到goinception 里 @huanchuanchuan

建议结构是这样:

```
└── src
    └── charts
        ├── archery
        │   ├── Chart.yaml
        │   ├── README.md
        │   ├── requirements.yaml
        │   ├── templates
        │   └── values.yaml
        ├── goinception
        └── inception
```

2019-09-29 09:45 UTC, jerryhu1234 commented
> stable/redis, stable/m

redis的可以直接不用写chart，其他的需要了要一些初化始用户名和密码的环境变量

2019-09-29 09:57 UTC, LeoQuote commented
mysql 的也不用吧, 不就是管理员密码什么的吗.....

2019-09-29 10:24 UTC, jerryhu1234 commented
> 没想到这么大, redis 和 mysql 的可以使用 stable/redis, stable/mysql 吗, 然后只在values 中写value
> 
> goinception 的可以暂时放项目里, 也建议直接提到goinception 里 @huanchuanchuan
> 
> 建议结构是这样:
> 
> ```
> └── src
>     └── charts
>         ├── archery
>         │   ├── Chart.yaml
>         │   ├── README.md
>         │   ├── requirements.yaml
>         │   ├── templates
>         │   └── values.yaml
>         ├── goinception
>         └── inception
> ```
如果是这种结构的话，redis,mysql要么单独创建pod，要么在archery的pods跑多个容器了（redis,mysql），但inception,goinception也是需要连mysql；
如果在redis,mysql在chart内，就直接可以在创建mysql容器时，把mysql的用户名和密码给创建了。

2019-09-29 10:45 UTC, LeoQuote commented
对, 就多个pod, mysql 用root 连, 不要暴露端口就行, goinception 可以加一个chart , 不能再多了, inception 应该已经没用了 @hhyo 确认一下? 

文件结构有其他问题要商量吗?

mysql redis 用dependency 做.

2019-09-29 12:07 UTC, hhyo commented
> 对, 就多个pod, mysql 用root 连, 不要暴露端口就行, goinception 可以加一个chart , 不能再多了, inception 应该已经没用了 @hhyo 确认一下?
> 
> 文件结构有其他问题要商量吗?
> 
> mysql redis 用dependency 做.

用倒还是在用，脱敏和表权限依赖语法解析，同时mysql的端口不暴露还是不能写入慢日志吧

2019-09-29 13:28 UTC, jerryhu1234 commented
> 对, 就多个pod, mysql 用root 连, 不要暴露端口就行, goinception 可以加一个chart , 不能再多了, inception 应该已经没用了 @hhyo 确认一下?
> 
> 文件结构有其他问题要商量吗?
> 
> mysql redis 用dependency 做.

如果用helm 里的redis，mysql太重，有pvc,psp等资源对象，并且产生的密码，一些定制化的配置没有其他地方配置吧？我再研究一下看看吧。

2019-09-29 15:43 UTC, LeoQuote commented
密码生成出来会放在secret里面，用secret生成configmap，再挂载到pod里就可以了，应该问题不大，如果不能生成就提前指定root密码然后填进去也可以。

由于inception现在还在用，inception也需要一个chart...

不过inception和goinception都是写在数据库里的，确实有些蛋疼，可以考虑一下有一个prestart脚本，如果有某些文件就提前注入一些配置，这样就比较完美。

感谢你的支持和贡献，希望能继续改进一下！

2019-09-29 15:44 UTC, LeoQuote commented
🤔头疼，那还要暴露mysql.....

2019-09-29 23:51 UTC, hhyo commented
不大了解，不过建议mysql和redis这些数据库服务可以由用户配置外部地址，一般这种也是单独部署和维护的

2019-09-30 03:02 UTC, jerryhu1234 commented
> 密码生成出来会放在secret里面，用secret生成configmap，再挂载到pod里就可以了，应该问题不大，如果不能生成就提前指定root密码然后填进去也可以。
> 
> 由于inception现在还在用，inception也需要一个chart...
> 
> 不过inception和goinception都是写在数据库里的，确实有些蛋疼，可以考虑一下有一个prestart脚本，如果有某些文件就提前注入一些配置，这样就比较完美。
> 
> 感谢你的支持和贡献，希望能继续改进一下！



> 不大了解，不过建议mysql和redis这些数据库服务可以由用户配置外部地址，一般这种也是单独部署和维护的

现在的做法为，把redis,mysql从helm repo中直接获取，再从根目录下的values.yaml传参过去：
1）启了redis,mysql的deployment和svc，redis,mysql的svc使用的是clusterIP，也只能是集群内访问；
2）helm repo下的mysql倒是有一个network policy，但对flannel网络无效，有局取性，原来的做法是用headless，不暴露svc IP，但现在用别人的charts就不能灵活配置  clusterIP: None。

2019-09-30 03:06 UTC, LeoQuote commented
嗯, 用values 传参是好的. svc 暂时不用暴露, 后续可以再想办法暴露, kubeproxy 或者nodeport 都行.

注意一下目录结构, 现在的目录结构太复杂了, 而且你好像加了两个文件夹

2019-09-30 04:53 UTC, closed without merging