Archery charts
hhyo/archer pull request #467
Opened 2019-09-30 05:17 UTC by jerryhu1234

1、优化目录；
2、因rule.json放根目录的values.yaml有问题，改为使用helm install ./ --set-file runJson=run.json传参，如有可能，看能否直接把放打包到archery的image中；
3、使用helm 的repo下的stable/mysql,如果不传入mysql.cnf，则会存在字符集问题，导入sql时会报错，但把mysql.cnf放到根目录下的values.yaml中时，则在helm install时，会有warnings提示，但不会影响使用。
4、msyql的数据存储使用emptyDIrs，没有使用pv和hostPath,到时候再优化。

2019-09-30 13:36 UTC, LeoQuote requested changes
感谢你的贡献！我在上面标记了一些review，尽量按照我说的修改一下。

主要是以下几点：

1. 层级考虑调整一下，charts下面三个chart 
* archery
* inception
* goinception
各个文件夹里面有chart.yaml，templates文件夹等，charts文件夹下一个readme，大概说明使用方式，一个values.yaml 作为archery的范例values
2. 直接往分支上推送就可以更新代码，请不要再关pr，我在上一个pr里写的层级建议都没了，这很烦的，我写了半天的。
3. 有一个误提交的大文件请删除
4. 考虑使用 git rebase 合并一下提交，精简版本历史，具体教程可以百度一下 git rebase

如果有什么不明白或者不同意的可以直接在pr里回复。

2019-09-30 13:36 UTC, LeoQuote commented on src/charts/Chart.yaml
> +name: archeryk8s
叫 archery 或者 Archery

2019-09-30 13:36 UTC, LeoQuote commented on src/charts/README.txt
> +kubectl port-forward pods/archery-xxxxxx 9123:9123
这里可以考虑ingress暴露吗？

2019-09-30 13:36 UTC, LeoQuote commented on src/charts/charts/goinception/Chart.yaml
> +description: A Helm chart for Kubernetes
层级调整一下？ charts 下面两个chart 一个archery，一个goinception

2019-09-30 13:36 UTC, LeoQuote commented on src/charts/charts/goinception/templates/configMap.yaml
> +{{- end }}
文件末尾换行

2019-09-30 13:36 UTC, LeoQuote commented on src/charts/charts/inception/templates/ingress.yaml
> +	{{- range $ingressPaths }}
tab改空格

2019-09-30 13:36 UTC, LeoQuote commented on src/charts/rule.json
> +    "_id" : ObjectId("5b61644153cc7e049902d11b"),
这个文件没用，可以删除

2019-09-30 13:40 UTC, LeoQuote commented
补充一点，mysql的持久化必须要做，emptydir绝对不能接受，在mysql chart 里设置开启持久化就可以。

2019-09-30 13:44 UTC, LeoQuote commented
建议层级

```
└── src
    └── charts
        ├── archery
        │   ├── Chart.yaml
        │   ├── README.md
        │   ├── requirements.yaml
        │   ├── templates
        │   └── values.yaml
        ├── goinception
        └── inception
```

2019-10-03 06:36 UTC, jerryhu1234 commented on src/charts/README.txt
> +kubectl port-forward pods/archery-xxxxxx 9123:9123
可以考虑，但可以修改svc为nodeport或loadblance的，也可以自由修改的。

2019-10-03 06:36 UTC, jerryhu1234 commented on src/charts/Chart.yaml
> +name: archeryk8s
文件名叫archery,或Archery不可取，这个都尝试过了，并且k8s资源对象只能用小写或加“-”表示，并且，你说的，inception,goinception是他们的subcharts，一般都是这样放的。

2019-10-03 06:37 UTC, jerryhu1234 commented on src/charts/rule.json
> +    "_id" : ObjectId("5b61644153cc7e049902d11b"),
好的。

2019-10-03 06:37 UTC, jerryhu1234 commented on src/charts/charts/inception/templates/ingress.yaml
> +	{{- range $ingressPaths }}
好，可能是vscode问题。

2019-10-03 06:40 UTC, jerryhu1234 commented on src/charts/charts/goinception/Chart.yaml
> +description: A Helm chart for Kubernetes
两个chart,一个是archery是主，一个依赖是goinception.一般层级也可以这样放的。

2019-10-03 06:41 UTC, jerryhu1234 commented on src/charts/charts/goinception/templates/configMap.yaml
> +{{- end }}
> 文件末尾换行
好。

2019-10-03 06:52 UTC, jerryhu1234 commented on src/charts/Chart.yaml
> +name: archeryk8s
文件名Archery不可取，k8s资源对象只能用小写或加“-”表示，inception,goinception是他们的subcharts，这样放应该没有什么问题的。

2019-10-03 06:55 UTC, jerryhu1234 commented on src/charts/charts/goinception/templates/configMap.yaml
> +{{- end }}
> 文件末尾换行
好。


> 感谢你的贡献！我在上面标记了一些review，尽量按照我说的修改一下。
> 
> 主要是以下几点：
> 
> 1. 层级考虑调整一下，charts下面三个chart
> 
> * archery
> * inception
> * goinception
>   各个文件夹里面有chart.yaml，templates文件夹等，charts文件夹下一个readme，大概说明使用方式，一个values.yaml 作为archery的范例values
> 
> 1. 直接往分支上推送就可以更新代码，请不要再关pr，我在上一个pr里写的层级建议都没了，这很烦的，我写了半天的。
> 2. 有一个误提交的大文件请删除
> 3. 考虑使用 git rebase 合并一下提交，精简版本历史，具体教程可以百度一下 git rebase
> 
> 如果有什么不明白或者不同意的可以直接在pr里回复。

好的，不好意思，不会再切分支了。

2019-10-03 07:05 UTC, jerryhu1234 commented
> 补充一点，mysql的持久化必须要做，emptydir绝对不能接受，在mysql chart 里设置开启持久化就可以。
 mysql的持久化，先用hostPath,如果使用者条件允许可以开启pv,这个有配置的。
因为默认开启了也用不了。

2019-10-03 17:01 UTC, LeoQuote commented
持久化必须做，用k8s内置mysql又不开启持久化的人不是我们的目标群体， 重启一下数据就没了，这绝对不行啊。

k8s开启持久化就设置一个默认storageclass就可以的

2019-10-07 00:32 UTC, LeoQuote commented
清除stale tag

2019-10-08 01:48 UTC, jerryhu1234 commented
> 持久化必须做，用k8s内置mysql又不开启持久化的人不是我们的目标群体， 重启一下数据就没了，这绝对不行啊。
> 
> k8s开启持久化就设置一个默认storageclass就可以的

这个本身有的，提交版本时有修改的。

2019-10-08 02:47 UTC, LeoQuote commented on src/charts/charts/goinception/templates/ingress.yaml
> +	{{- range $ingressPaths }}
tab 换成空格

2019-10-08 02:47 UTC, LeoQuote commented on src/charts/charts/inception/templates/ingress.yaml
> +	{{- end }}
tab换成空格

2019-10-08 02:51 UTC, LeoQuote commented on src/charts/values.yaml
> +    storageClass: "alicloud-disk-efficiency"
这里暂时不要填, 一般会用默认的storageClass , 这样填了之后有些用户是没法初始化, 建议删除这一行

2019-10-08 03:01 UTC, LeoQuote commented on src/charts/README.md
> +
(可选) 可以考虑把这几步放在 init container里做

2019-10-08 03:02 UTC, LeoQuote submitted a review, later dismissed
层级不改的话也行, 后续有空再看吧. 上面几个改完就可以merge了

2019-10-08 10:07 UTC, hhyo commented
@LeoQuote 确认合适直接合并就行

2019-10-08 10:15 UTC, LeoQuote commented
@hhyo 嗯, 这个我来合

2019-10-11 05:54 UTC, jerryhu1234 commented on src/charts/charts/goinception/templates/ingress.yaml
> +	{{- range $ingressPaths }}
已处理

2019-10-11 05:54 UTC, jerryhu1234 commented on src/charts/charts/inception/templates/ingress.yaml
> +	{{- end }}
已处理

2019-10-11 05:56 UTC, jerryhu1234 commented on src/charts/values.yaml
> +    storageClass: "alicloud-disk-efficiency"
好的。

2019-10-11 05:57 UTC, jerryhu1234 commented on src/charts/README.md
> +
好的，我尝试一下，主要是创建用户这个，需要自动输入用户和我密码。

2019-10-11 06:46 UTC, LeoQuote approved these changes
有个叫commit_id 的文件又被提上来了, 我帮你删除掉了, 这个暂时合了, 后续的更新欢迎再提pr

2019-10-11 07:03 UTC, merged

2019-10-11 08:30 UTC, jerryhu1234 commented on src/charts/README.md
> +
好的，python3 manage.py createsuperuser这里创建用户和密码时，存在交互，我用expect弄了一个，但需要安装exxpect包，刚跑了是可以成功的，但最好是在images里有expect的命令。

2019-10-11 08:44 UTC, jerryhu1234 commented on src/charts/README.md
> +
或者有初始化sql脚本的时候，直接写入superuser，就应该好办了。