增加脚本一键初始化脚本
hhyo/archer pull request #475
Opened 2019-10-11 12:45 UTC by jerryhu1234

增加脚本一键初始化脚本
还是使用了expect命令，因django目前还是没有找到相关生成密码的方法，创建用户，密码为空时不能登录；
expect需要安装，因没有在 images中打包好，当用户离线安装时，会生成问题。
如果有其他生成superuser的密码的方式，请告之。

2019-10-11 14:25 UTC, hhyo commented
感谢贡献，方便的话可以添加微信 `rtttte` 进开发群

2019-10-11 14:47 UTC, hhyo commented
还有不要关闭PR，否则整个功能的沟通和讨论过程涉及多个PR，不便于追溯和检索

可以在PR对应分支强制推送来覆盖以前的提交

2019-10-11 14:50 UTC, jerryhu1234 commented
> 还有不要关闭PR，否则整个功能的沟通和讨论过程涉及多个PR，不便于追溯和检索
> 
> 可以在PR对应分支强制推送来覆盖以前的提交

好的。

2019-10-11 15:06 UTC, LeoQuote commented
又关pr了 ，我很无语。

为什么要关掉 mysql 的持久化？

createsuperuser可以做非交互式的，你查一下django文档，里面有，在values里面填 superuser password，不要在脚本里写死。

初始脚本可以考虑用 init containers吗？ 对 postStart 不算特别了解，这个有日志吗？

2019-10-12 07:13 UTC, jerryhu1234 commented
> 又关pr了 ，我很无语。
> 
> 为什么要关掉 mysql 的持久化？
> 
> createsuperuser可以做非交互式的，你查一下django文档，里面有，在values里面填 superuser password，不要在脚本里写死。
> 
> 初始脚本可以考虑用 init containers吗？ 对 postStart 不算特别了解，这个有日志吗？

用了initcontainer，这个只能去等mysql,redis是否准备好，还只能是在postStart里执行，在pod准备好的时间，先执行初始化脚本。

2019-10-12 07:15 UTC, jerryhu1234 commented
> > 又关pr了 ，我很无语。
> > 为什么要关掉 mysql 的持久化？
> > createsuperuser可以做非交互式的，你查一下django文档，里面有，在values里面填 superuser password，不要在脚本里写死。
> > 初始脚本可以考虑用 init containers吗？ 对 postStart 不算特别了解，这个有日志吗？
> 
> 用了initcontainer，这个只能去等mysql,redis是否准备好，还只能是在postStart里执行，在pod准备好的时间，先执行初始化脚本。

mysql持久化，可能对有些人来说，需要创建一个pv或，sc，就多操作了一步，如果不配置就会mysql启不起来。。所以默认是不开启的，你们确定一下？如果需要，可以开启。

2019-11-02 10:11 UTC, LeoQuote requested changes
麻烦参考review进行修改

2019-11-02 10:11 UTC, LeoQuote commented on src/charts/values.yaml
> +    enabled: false
请开启持久化

2019-11-02 10:11 UTC, LeoQuote commented on src/charts/README.md
> +ii 集群外访问 将svc配置为nodePort或loadBalance，或开启ingress
麻烦增加一些ingress的配置吧。

2019-11-02 10:11 UTC, LeoQuote commented on src/charts/values.yaml
> +        exit(0)
这里可以考虑 exit(127) 之类的吗？ exit 0会认为是正常退出。

2019-11-04 09:02 UTC, jerryhu1234 commented on src/charts/values.yaml
> +        exit(0)
好的。

2019-11-04 09:02 UTC, jerryhu1234 commented on src/charts/README.md
> +ii 集群外访问 将svc配置为nodePort或loadBalance，或开启ingress
好的。

2019-11-04 09:03 UTC, jerryhu1234 commented on src/charts/values.yaml
> +    enabled: false
好的。

2019-11-04 14:58 UTC, jerryhu1234 commented on src/charts/values.yaml
> +        exit(0)
目前暂时没有环境进行测试，当有已创建用户的异常时，应该是允许pod给正常ready,因没有分别捕捉出来，所以弄了一个0返回正常，这个到时候有环境了再修改。

2019-11-05 06:59 UTC, merged