Feature/dockerfile
hhyo/archer pull request #516
Opened 2019-11-12 14:20 UTC by sunnywalden

拆分Dockerfile为基础镜像与服务镜像，加速构建速度。主要修改：
1）分拆Dockerfile为Dockerfile-base与Dockerfile，生成hhyo/archery:base镜像与主版本镜像；
2）合并多个RUN，提高容器镜像构建速度，节省资源消耗。

2019-11-12 15:51 UTC, LeoQuote reviewed
感谢贡献，@hhyo 看看这个base怎么样，有没有办法把base也加到ci中去。

2019-11-12 15:51 UTC, LeoQuote commented on src/docker/Dockerfile
> +COPY ../.. /opt/archery/
这里不要这么写吧，正常写 copy . . 就行， build 的时候会在主目录build， 指定这里的dockerfile

2019-11-13 01:24 UTC, hhyo commented
> 感谢贡献，@hhyo 看看这个base怎么样，有没有办法把base也加到ci中去。

以前没拆就是ci的问题，现在打tag可以自动build完整镜像。拆成两个，base也需要做版本管理，因为难免会有变动，server的镜像要在base构建成功后再触发，这个不清楚有没有实现方式

2019-11-13 02:35 UTC, sunnywalden commented
> se也需要做版本管理，因为难免会有变动，server的镜像要在base构建成功后再触发，这个不清楚有没有实现

ci需要看实现技术栈，dockerhub的话是没有问题的，可以设置设置多个build，也可以自定义Dockerfile路径。

2019-11-13 02:36 UTC, sunnywalden commented
> > 感谢贡献，@hhyo 看看这个base怎么样，有没有办法把base也加到ci中去。
> 
> 以前没拆就是ci的问题，现在打tag可以自动build完整镜像。拆成两个，base也需要做版本管理，因为难免会有变动，server的镜像要在base构建成功后再触发，这个不清楚有没有实现方式

base的变动是可以预见的，比较少，把它的触发模式设置为手动就可以了。

2019-11-13 06:08 UTC, hhyo requested changes

2019-11-13 06:08 UTC, hhyo commented on src/docker/Dockerfile-base
> +ENV PYTHON_VERSION 3.7.5
各个依赖模块针对3.7.5的兼容性如何？目前case覆盖也不是特别全面

2019-11-13 06:08 UTC, hhyo commented on src/docker/Dockerfile
> +FROM hhyo/archery:base
base增加版本管理吧，单独的版本控制，先从1.0开始

2019-11-13 09:53 UTC, sunnywalden commented on src/docker/Dockerfile-base
> +ENV PYTHON_VERSION 3.7.5
测试中未发现兼容性问题

2019-11-13 10:00 UTC, sunnywalden commented on src/docker/Dockerfile
> +FROM hhyo/archery:base
> base增加版本管理吧，单独的版本控制，先从1.0开始

base tag采用哪种？archery:base-v[version]？还是archery-base:[version]？感觉archery:base-v[version]放在一个项目下更方便。

2019-11-13 12:51 UTC, LeoQuote commented on src/docker/Dockerfile
> +FROM hhyo/archery:base
hhyo/archery-base:1.71

应该是这样的。

2019-11-13 14:43 UTC, hhyo commented on src/docker/Dockerfile
> +FROM hhyo/archery:base
archery:base-v[version]，放在一个项目下，不然还要再起一个项目
@LeoQuote 不建议用和Archery统一的版本号，独立版本更合适

2019-11-13 15:49 UTC, LeoQuote commented on src/docker/Dockerfile-base
> +ENV PYTHON_VERSION 3.7.5
可以直接在travic ci里加上一个python版本号就可以。

2019-11-14 08:35 UTC, hhyo commented on src/docker/Dockerfile
> +FROM hhyo/archery:base
这个有时间修改后提交下，我合并后添加ci任务构建一下

2019-11-20 13:08 UTC, closed without merging

2019-11-21 01:37 UTC, hhyo commented on .travis.yml
> +  - "3.7.5"
不用修改，增加一行就行，ci测试两个版本

2019-11-21 01:37 UTC, hhyo commented on requirements.txt
> +mo-future==2.48.19205
新依赖可以在后续PR再加

2019-11-21 01:37 UTC, hhyo commented on src/docker/Dockerfile-base
> +    && yum -y install openldap-devel gettext nginx
Nginx放在上一层能正常启动不？以前测试不行所以放在最后，倒是想把Nginx单独独立部署

2019-11-21 01:37 UTC, hhyo commented on src/docker/Q-Dockerfile
>  COPY . /opt/archery/
我倒是一直没有使用过Django-Q的docker，Archery启动时会启动docker-q，如果可以拆出来单独部署更好，但实际上需要公用代码和配置文件