快速初始化安装
hhyo/archer pull request #644
Opened 2020-02-26 09:12 UTC by Alenx58

1.降低初始化难度
2.配置外置化，降低配置出错率
3.新增admin.sh自动化脚本

2020-02-26 16:01 UTC, hhyo requested changes
首先感谢你的贡献
因为文档不全的缘故，项目确实缺一个系统化的管理脚本，包括初始化和升级重启等，具体实现可以在pr讨论，也可以通过我的个人微信加入开发者群，谢谢

2020-02-27 00:24 UTC, Alenx58 commented on admin.sh
> +    kill -9 $(ps -ef | grep "python" | grep -v grep | awk '{print $2}')
ok ，这块我在修改下

2020-02-27 00:26 UTC, Alenx58 commented on admin.sh
> +    source ./venv/bin/activate
建议直接升级方式，因为你不知道会遇到专不专业运维，他有可能不是运维，对用户来说是有点难度

2020-02-27 00:29 UTC, Alenx58 commented on sql/fixtures/auth_group.sql
> +INSERT INTO sql_users(password, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, display, failed_login_count, last_login_failed_at)
嗯，加了salt会出现这样的问题，如果是这样那么建议修改加密方式

2020-02-27 00:31 UTC, Alenx58 commented on nginx.conf
> +    server_name 0.0.0.0;
这个是方便快速配置NGINX

2020-02-27 00:34 UTC, Alenx58 commented on archery/settings.py
> +#!/usr/bin/env python3
这个是多方面考虑，有些不熟悉Python的运维，开发部署好，修改配置时出现其他问题，Python对格式要求严格，我维护过其他的开源项目，在微信讨论群里，会有各种各样的问题出现

2020-02-27 02:57 UTC, Alenx58 commented on admin.sh
> +    kill -9 $(ps -ef | grep "python" | grep -v grep | awk '{print $2}')
问题已解决

2020-02-27 02:57 UTC, Alenx58 commented on admin.sh
> +    source ./venv/bin/activate
问题已解决

2020-02-28 15:12 UTC, hhyo commented on requirements.txt
> +supervisor==4.1.0
依赖重复了

2020-02-28 15:14 UTC, hhyo commented on admin.sh
> +    source ./venv/bin/activate
前期几个版本数据修改比较大，也没有很好的去看migrate，目前确实做不了直升

2020-02-28 15:24 UTC, hhyo commented on archery/settings.py
> +#!/usr/bin/env python3
这个暂时先不单列出来，配置中还有其他挺多配置项也是需要调整，这个PR先单独提交一个admin脚本吧，其他的revert，谢谢了

2020-02-29 01:02 UTC, closed without merging