修复不传入sleep值报错的bug
hhyo/archer pull request #686
Opened 2020-03-25 09:53 UTC by falcondance

修复不传入sleep值报错的bug，如不传入，默认为0

2020-03-25 10:13 UTC, LeoQuote commented
相关issue 是这个吧 #679

2020-03-25 10:17 UTC, LeoQuote requested changes

2020-03-25 10:17 UTC, LeoQuote commented on sql/archiver.py
> +        sleep = 0
这里加一下参数校验吧.

```python
try:
    sleep = int(request.POST.get('sleep', 0))
except ValueError:
    # 报错
```

2020-03-25 10:19 UTC, LeoQuote commented
最好前端也加一下参数校验, 后端的报错比较傻.

2020-03-25 10:21 UTC, LeoQuote commented
@hhyo 这个用django forms 或者什么做参数校验会不会好一点, 那种参数校验好像直接在model层写就行了.

2020-03-27 13:14 UTC, hhyo commented
> @hhyo 这个用django forms 或者什么做参数校验会不会好一点, 那种参数校验好像直接在model层写就行了.

没用过，现在都人工check确实很麻烦

2020-03-27 14:23 UTC, merged

2020-03-27 19:11 UTC, LeoQuote commented
这个取值不对吧，如果前端传字符串过来还是会出问题的。

还有那种一个空格的情况，都会有问题，最好做个参数校验。

2020-03-28 01:21 UTC, hhyo commented
前端非要传字符串的话，这种场景目前其他地方也是没有检验的，目前都会在前端把input换成number，后面找个参数检验的库？