添加跳板机连接数据库功能
hhyo/archer pull request #736
Opened 2020-05-11 03:39 UTC by EliasChiang

你好：
       我在项目上添加了通过ssh隧道连接，实现跳板机连接数据库功能。
       实现是通过sshtunnel包，连通跳板机之后映射目标端口到本地，这个方案在我之前的项目中使用过。在本项目中我只测试了MySQL连接，但是理论上其他数据库也是可行的。
       我主要做了以下修改：
              1.新增了ssh_tunnel模型，并且修改instance，增加到ssh_tunnel的外键字段。
              2.新增了ssh_tunnel.py，但是需要通过类的方式实现。
              3.修改 sql/engines/mysql.py 增加了__del__(self)函数，需要注意其他引擎可能也都需要增加该函数，否则隧道无法关闭。
       需要注意的是：
              1.初始化需要增加步骤：python3 manage.py dbshell<src/init_sql/ssh_tunnel.sql，添加无隧道初始化信息，无隧道是根据ssh_tunnel.tunnel_name == 'None'判断，这部分我写死在了代码里。
              2.我不会做界面，所以没有做“添加ssh隧道界面”以及相关的界面，因此如果实际使用还需要额外新增界面部分代码。
       如有疑问，请随时联系 QQ362424547

2020-05-11 04:51 UTC, LeoQuote requested changes
感谢提交，问题不大，单元测试看一下

2020-05-11 04:51 UTC, LeoQuote commented on sql/engines/__init__.py
> +            if self.instance.tunnel.tunnel_name != 'None':
改成 if self.instance.tunnel 应该就可以，不用判断name，如果没有关联就会是None

2020-05-11 04:51 UTC, LeoQuote commented on sql/models.py
> +    password = fields.EncryptedCharField(verbose_name='密码', max_length=300, default='', blank=True)
能不能加个密钥对的认证？

2020-05-11 04:51 UTC, LeoQuote commented on sql/engines/__init__.py
> +                self.ssh = SSHConnection(
这个连接建立之后需要close吗？还是自动close？

2020-05-11 04:51 UTC, LeoQuote commented on src/init_sql/ssh_tunnel.sql
> +insert into ssh_tunnel (tunnel_name, host, port, user, password, create_time, update_time) values ('None', '127.0.0.1', 22, 'user', 'password', now(), now()) ;
更名成其它文件一样的类似版本号的sql

2020-05-18 01:49 UTC, EliasChiang commented on sql/engines/__init__.py
> +            if self.instance.tunnel.tunnel_name != 'None':
我发现Django在关联时如果为空，则会导致类的报错。其实一开始我就用了你说的方式，但是报错始终解决不了，于是就写入了一条空数据解决这个问题。

2020-05-18 01:53 UTC, EliasChiang commented on sql/engines/__init__.py
> +                self.ssh = SSHConnection(
在隧道类清理的时候会调用close

2020-05-18 01:55 UTC, EliasChiang commented on src/init_sql/ssh_tunnel.sql
> +insert into ssh_tunnel (tunnel_name, host, port, user, password, create_time, update_time) values ('None', '127.0.0.1', 22, 'user', 'password', now(), now()) ;
好的，另外有关单元测试的部分，是因为我在数据库实例中添加了隧道属性，所以导致单元测试失败，这个问题可能需要修改测试用例生成部分来解决。

2020-05-18 02:05 UTC, EliasChiang commented on sql/models.py
> +    password = fields.EncryptedCharField(verbose_name='密码', max_length=300, default='', blank=True)
好的，我会在后续添加密钥认证的方式，但可能需要等比较长的时间。

2020-05-20 06:37 UTC, LeoQuote commented on sql/engines/tests.py
> +                                           port=3306, user='ins_user', password='some_str', tunnel = 'None')
嗯? tunnel 不是可选的吗?

2020-05-20 06:51 UTC, EliasChiang commented on sql/engines/tests.py
> +                                           port=3306, user='ins_user', password='some_str', tunnel = 'None')
这里是因为我发现如果tunnel设置为可为空，那么为空时会导致Django Models报错，所以我强行写了一个值，当tunnel_name='None' 时，不会调用通道，通过这种方式实现tunnel可选。

2020-05-20 07:36 UTC, LeoQuote commented on sql/engines/tests.py
> +                                           port=3306, user='ins_user', password='some_str', tunnel = 'None')
这样不行, 你这样不止用例要改, 所有engine 都要改, 也不合理, 为什么一个可选选项还一定要强行写一个值, 你得把这个问题解决一下.

2020-05-20 07:37 UTC, LeoQuote commented on sql/engines/tests.py
> +                                           port=3306, user='ins_user', password='some_str', tunnel = 'None')
传字符串`None`进去也太变态了吧😂, 后面看会很困惑的.

2020-05-20 07:40 UTC, LeoQuote commented on sql/models.py
> +    tunnel = models.ForeignKey(Tunnel, on_delete=models.CASCADE)
我刚搜到, 这个可能要加两个选项`blank=True, null=True`, 你试一下

2020-05-20 07:42 UTC, EliasChiang commented on sql/models.py
> +    tunnel = models.ForeignKey(Tunnel, on_delete=models.CASCADE)
其实我一开始就是用了这2个选项，然后就出现报错了~

2020-05-20 07:43 UTC, EliasChiang commented on sql/engines/tests.py
> +                                           port=3306, user='ins_user', password='some_str', tunnel = 'None')
engine 是不需要修改的，只需要在 engine/__init__.py 里面进行判断就可以了

2020-05-20 07:44 UTC, LeoQuote commented on sql/models.py
> +    tunnel = models.ForeignKey(Tunnel, on_delete=models.CASCADE)
报什么错呢, 分享一下, 看看有没有相关的问题

2020-05-20 07:46 UTC, EliasChiang commented on sql/models.py
> +    tunnel = models.ForeignKey(Tunnel, on_delete=models.CASCADE)
报错是在使用的时候，比如我在进行数据查询时，选择对应的实例（无隧道）后报错
AttributeError: 'NoneType' object has no attribute 'host'
有隧道的实例则不会报错

2020-05-20 07:49 UTC, LeoQuote commented on sql/models.py
> +    tunnel = models.ForeignKey(Tunnel, on_delete=models.CASCADE)
完整的traceback 贴一下, 看看能不能定位到代码.

2020-05-20 09:06 UTC, EliasChiang commented on sql/models.py
> +    tunnel = models.ForeignKey(Tunnel, on_delete=models.CASCADE)
我找到traceback之后解决了错误~现在可以正常的实现0对多了

2020-05-20 09:09 UTC, LeoQuote commented on sql/models.py
> +    tunnel = models.ForeignKey(Tunnel, on_delete=models.CASCADE)
nice, 这样就不用改测试用例了

2020-05-20 09:12 UTC, LeoQuote commented on sql/engines/__init__.py
> +                self.ssh = SSHConnection(
尴尬, 好像实际用的时候, 都不会用到 del engine 方法, 可能需要你改一下用engine 的地方看看

2020-05-20 09:46 UTC, LeoQuote commented
初始化脚本还是要的, 要用sql语句改一下库的

2020-05-20 09:47 UTC, EliasChiang commented on sql/engines/__init__.py
> +                self.ssh = SSHConnection(
我刚刚测试了一下，确实存在这个问题，我争取在近期解决，顺便实现密钥连接的方式，大概要1-2周

2020-05-20 09:51 UTC, LeoQuote commented on sql/engines/__init__.py
> +                self.ssh = SSHConnection(
感谢贡献🙏

2020-05-20 09:54 UTC, EliasChiang commented
> 初始化脚本还是要的, 要用sql语句改一下库的

我在此处是删除了我新增的一个初始化sql，因为原先是一对多所以必须写一条初始化数据，现在已经不需要就删除了。

2020-05-20 09:55 UTC, LeoQuote commented
哦哦, 那后续还是要加一下tunnel 表以及instance 表 的改表建表语句

2020-05-27 05:43 UTC, EliasChiang commented
已添加tunnel 表以及instance 表 的改表建表语句，文件为 v1.7.8_v1.7.9.sql
并新增了密钥认证隧道的方式，默认会使用密钥，密钥地址为空时使用密码。

2020-05-27 06:28 UTC, LeoQuote commented on sql/utils/ssh_tunnel.py
> +            self.private_key = RSAKey.from_private_key_file(pkey_address, password=pkey_password)
这个只能传一个物理路径吗? 传物理路径部署起来会比较麻烦啊.....能不能把私钥存数据库呢?

2020-05-27 06:48 UTC, EliasChiang commented on sql/utils/ssh_tunnel.py
> +            self.private_key = RSAKey.from_private_key_file(pkey_address, password=pkey_password)
是这样，这里是传递私钥的路径，一般来说私钥出于安全性只有root用户可以访问，所以也不算很麻烦，在界面上设置私钥路径即可。
如果直接把私钥存储到数据库，这样一来设计加密转换的问题，二来会产生一个一对多的私钥-通道关系，数据录入和数据管理会变得更加复杂。
我们在实际操作的时候会用脚本直接刷入隧道数据+实例数据，所以我认为这种直接写路径的方式会更加优秀一点，更容易保护私钥的安全，同时录入数据也不会很麻烦。

2020-05-29 05:56 UTC, LeoQuote commented on sql/utils/ssh_tunnel.py
> +            self.private_key = RSAKey.from_private_key_file(pkey_address, password=pkey_password)
emmm 我仔细想了想是有一定道理的. 这个方案也挺好

2020-05-29 06:03 UTC, LeoQuote requested changes
问题不大, 几个小点修改完就能merge了

2020-06-01 07:43 UTC, EliasChiang commented on sql/utils/ssh_tunnel.py
> +            self.private_key = RSAKey.from_private_key_file(pkey_address, password=pkey_password)
已经修改了非空判断，和pkey_address 改成 pkey_path

2020-06-01 08:32 UTC, LeoQuote commented on sql/engines/__init__.py
> +                self.ssh = SSHConnection(
实在不好意思，上次审的时候没注意这个点，就是ssh tunnel 关闭，回收端口的问题，这个你是不是忘记提交上来了？

2020-06-01 08:37 UTC, EliasChiang commented on sql/engines/__init__.py
> +                self.ssh = SSHConnection(
这个我在本地测试的时候，发现端口会自动回收，于是就没有添加代码了，建议测试mysql连接看看。

2020-06-01 10:21 UTC, LeoQuote commented on sql/engines/__init__.py
> +                self.ssh = SSHConnection(
了解🆗

2020-06-01 10:22 UTC, LeoQuote requested changes
😅 不好意思, 还有两个问题

1. requirements 冲突
2. 现在最新的已经到了 1.7.11 所以这个sql 语句还要变一下, 建议merge 下最新代码, 根据最新的版本更名一下.

2020-06-02 08:20 UTC, EliasChiang commented
已修改了冲突部分

2020-06-03 02:58 UTC, LeoQuote approved these changes
👏

2020-06-03 02:59 UTC, merged

2020-06-03 02:59 UTC, LeoQuote commented
merge 了, cc @hhyo

2020-08-26 06:49 UTC, starDemo commented
所以这个功能没有界面可以配置么？

2020-08-26 06:51 UTC, EliasChiang commented
> 所以这个功能没有界面可以配置么？

已添加管理页面，在 管理后台>隧道配置 ，可以进行界面配置

2020-08-26 07:03 UTC, EliasChiang commented
> 所以这个功能没有界面可以配置么？

我想起来隧道配置的界面还没有realase，可以先参考：
https://github.com/hhyo/Archery/pull/844

2020-08-26 07:22 UTC, starDemo commented
```
ERROR   | Could not establish connection from ('127.0.0.1', 34510) to remote side of the tunnel
```
容器部署的，连接就出现这个错误

2020-08-26 07:26 UTC, EliasChiang commented
> ```
> ERROR   | Could not establish connection from ('127.0.0.1', 34510) to remote side of the tunnel
> ```
> 
> 容器部署的，连接就出现这个错误

可能是由于gunicorn工作模式造成的，需要修改为sync模式
可以参考
https://github.com/hhyo/archery/wiki/FAQ
配置SSH隧道后无法连接
需要在supervisord.conf 文件中 ，修改并发方式为sync模式，如下所示：
command=gunicorn -w 4 -k sync-b 127.0.0.1:8000 --timeout 600 archery.wsgi:application

2020-08-26 07:26 UTC, starDemo commented
修为为sync还是有问题，我再看看

2020-09-17 05:32 UTC, starDemo commented
确定到问题了，docker模式启动的使用脚本是`startup.sh `
我修改启动模式是改了项目里的`supervisord.conf`
 改了`startup.sh`的脚本可以用了