insert all语法支持
hhyo/archer pull request #740
Opened 2020-05-14 14:32 UTC by jan-song

insert all语法支持

2020-05-15 06:30 UTC, LeoQuote commented on sql/engines/oracle.py
> +        elif re.match(r"^insert\s+into\s", sql):
我理解是不是这里直接改一下正则就行, 不用这样又匹配一次吧? 里面要做的事情完全一样的

2020-05-16 05:34 UTC, hhyo requested changes

2020-05-16 05:34 UTC, hhyo commented on sql/engines/oracle.py
> +        elif re.match(r"^insert\s+into\s", sql):
是的，提取的group没变，正则修改下可以匹配两个场景就可以

2020-05-20 16:08 UTC, jan-song commented on sql/engines/oracle.py
> +        elif re.match(r"^insert\s+into\s", sql):
好的，最近有空调整测试验证一下这边，顺便把备份未判断工单是否需要备份的bug修复一下

2020-05-20 16:08 UTC, jan-song commented on sql/engines/oracle.py
> +        elif re.match(r"^insert\s+into\s", sql):
好的，最近有空调整测试验证一下这边，顺便把备份未判断工单是否需要备份的bug修复一下

2020-05-21 03:19 UTC, LeoQuote commented on sql/engines/oracle.py
> +        elif re.match(r"^insert\s+into\s", sql):
建议一个pr只涉及一个问题

2020-05-21 16:12 UTC, LeoQuote approved these changes
很强👏

2020-05-22 00:46 UTC, hhyo requested changes

2020-05-22 00:46 UTC, hhyo commented on sql/engines/oracle.py
> +                    logger.error(f"Oracle工单备份异常，工单id：{workflow.id}， 错误信息：{traceback.format_exc()}")
备份异常可以标识一下备份状态，可以和mysql的执行结果一致

2020-05-24 03:53 UTC, hhyo commented on sql/engines/oracle.py
> +                    logger.error(f"Oracle工单备份异常，工单id：{workflow.id}， 错误信息：{traceback.format_exc()}")
看了下这个是全部执行完后的操作，不好标识，先这样吧

2020-05-24 03:53 UTC, hhyo approved these changes

2020-05-24 03:53 UTC, merged