加入mongodb审核，重写mongodb查询等
hhyo/archer pull request #900
Opened 2020-09-30 11:15 UTC by fancy-lee

1.加入mongodb审核，
2.重写mongodb查询支持原生查询语法
3.如果查询的实例名和db_name，tab_name不为空，但是sqlcontent为空时会自动创建生成一条查询语句;
4.查询编辑框加入缓存，避免刷新丢失
5.mongo审核时关闭备份下拉框等
6.优化mongodb查询显示效果

2020-09-30 12:34 UTC, LeoQuote requested changes
感谢提交pr
1. 单元测试一定要过

其他的事情看评论，另外不要重提pr，请直接在pr分支上提交，如果新开PR我就不再参与了。

2020-09-30 12:34 UTC, LeoQuote commented on sql/engines/mongo.py
> +__author__ = 'fancy_lee'
author要不直接去掉吧

2020-09-30 12:34 UTC, LeoQuote commented on sql/engines/mysql.py
> +        if sql == "":
这里的和mongo 不相关，删掉吧

2020-09-30 12:34 UTC, LeoQuote commented on sql/templates/sqlsubmit.html
> +                         if ($("#db_name").val()){
这里的更改没有必要吧

2020-09-30 12:34 UTC, LeoQuote commented on sql/engines/mongo.py
> +class JsonDecoder:
这个decoder有没有现成的模块可用？ 我们用的simplejson 能行吗？

2020-09-30 12:34 UTC, LeoQuote commented on sql/engines/mongo.py
> +    def exec_cmd(self, sql, db_name=None, slave_ok=''):
这里为什么要用os调用，现成的 mongodb sdk不能用吗？

2020-09-30 14:04 UTC, fancy-lee commented on sql/engines/mongo.py
> +    def exec_cmd(self, sql, db_name=None, slave_ok=''):
pymongo不能像mysql一样直接执行语句，它自己有自己的语法，所以需要转换，由于要转换的方法太多，所以就直接用os的mongo命令

2020-09-30 14:11 UTC, fancy-lee commented on sql/engines/mongo.py
> +class JsonDecoder:
自己写解析首先是为了解析类似ObjectId这样的对象，如果直接用simplejson，ObjectId就变得字符串了，其次就是为了更友好的提示用户输入的语句的错误位置

2020-09-30 14:16 UTC, fancy-lee commented on sql/engines/mysql.py
> +        if sql == "":
我在query.py中调用filter_sql()有加两个入参，querysql.html也修改了，主要是为了解决：如果查询的实例名和db_name，tab_name不为空，但是sqlcontent为空时，点击查询会自动创建生成一条查询语句，默认查询所有字段显示100行表数据

2020-09-30 14:16 UTC, fancy-lee commented on sql/engines/mongo.py
> +__author__ = 'fancy_lee'
ok

2020-09-30 16:24 UTC, LeoQuote commented
说实话这是我们第一个有自己的审核机制的engine，mysql的是调外部审查的，关于这些希望还是保持和之前一样有配套的单元测试，不然后续没人敢改，不好维护的。

2020-10-01 04:10 UTC, fancy-lee commented
> 说实话这是我们第一个有自己的审核机制的engine，mysql的是调外部审查的，关于这些希望还是保持和之前一样有配套的单元测试，不然后续没人敢改，不好维护的。

我把mysql的部分修改回来吧，第一次提pr不太熟悉流程，请多指教

2020-10-01 09:14 UTC, LeoQuote commented
不只是mysql的事情，mongo 的engine也是有单元测试的，mongo 的测试也得过

2020-10-01 16:45 UTC, fancy-lee commented
> 不只是mysql的事情，mongo 的engine也是有单元测试的，mongo 的测试也得过
请问Codacy/PR Quality Review 中的提示都得通过吗？Travis CI 测试mongo这块没有通过，但没有看出来问题，请帮忙看一下

2020-10-02 01:58 UTC, LeoQuote commented
checks 里travis 里可以点 this build 链接，然后你就可以看到日志

2020-10-02 02:34 UTC, fancy-lee commented
> checks 里travis 里可以点 this build 链接，然后你就可以看到日志

======================================================================
FAIL: test_query_check (sql.engines.tests.MongoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.6.5/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/hhyo/Archery/sql/engines/tests.py", line 1585, in test_query_check
    self.assertEqual(False, check_result.get('bad_query'))
AssertionError: False != True
======================================================================
FAIL: testCorrectSQL (sql.tests.TestQuery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.6.5/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/hhyo/Archery/sql/tests.py", line 918, in testCorrectSQL
    some_db, some_sql, some_limit, schema_name=None, tb_name=None, max_execution_time=60000)
  File "/opt/python/3.6.5/lib/python3.6/unittest/mock.py", line 825, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/opt/python/3.6.5/lib/python3.6/unittest/mock.py", line 814, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: Expected call: query('some_db', 'select some from some_table limit 100;', 100, max_execution_time=60000, schema_name=None, tb_name=None)
Actual call: query('some_db', 'select some from some_table limit 100;', 100)


第1个报错：Instance.objects.create(instance_name='some_ins', type='slave', db_type='mongo',host='some_host', port=3306, user='ins_user') 我看测试代码中的创建的mongo数据库实例是不是不存在？为什么端口号是3306，2.我用的db.job.find().count()做的测试，请问job这个文档存在吗？

第2个报错：怎么是mysql的测试？

2020-10-02 03:03 UTC, fancy-lee commented on sql/templates/sqlsubmit.html
> +                         if ($("#db_name").val()){
因为mongodb还不支持备份SQL，很多同学提交的时候以为可以备份，所以这块应该是为了把"是否备份"隐藏

2020-10-02 03:32 UTC, LeoQuote commented
我们的engine相关的测试除了mysql外，应该都是patch掉具体的调用，然后看内部逻辑的 #42  参考这个

2020-10-02 16:19 UTC, fancy-lee commented
> 我们的engine相关的测试除了mysql外，应该都是patch掉具体的调用，然后看内部逻辑的 #42 参考这个

请问Codacy/PR Quality Review中所有的问题都要修改吗？新加的每个方法都要写单元测试？

2020-10-02 16:42 UTC, LeoQuote commented
👏 恭喜测试全过了，你可以看到 codecov 的 覆盖率报告，里面可以看到哪些覆盖到哪些没覆盖，没有覆盖到的方法建议都写一下测试。

quality 的报告可以做参考，主要是风格方面的，也建议遵照改一下。

2020-10-04 14:20 UTC, LeoQuote commented
这些测试可以在本地跑的，不是一定要push上来才能测试

2020-10-04 17:23 UTC, fancy-lee commented
> 这些测试可以在本地跑的，不是一定要push上来才能测试

以前没有搞过单元测试，本地跑起来有问题，所以才push上来的，写的这个单元测试主要的流程应该都可以cover到了且已经通过，请看一下还有哪里要补充的？

2020-10-05 02:06 UTC, LeoQuote commented
这样调试太辛苦了，本地跑测试有两点，一个是需要redis，一个是settings里的sync 要改成false

2020-10-05 02:30 UTC, fancy-lee commented
> 这样调试太辛苦了，本地跑测试有两点，一个是需要redis，一个是settings里的sync 要改成false

我修改得差不多了，看一下下一步应该怎么走？

2020-10-05 08:34 UTC, LeoQuote commented
看一下覆盖率稍微降了一点点，最好是能持平或者涨一点，非常建议做，实在没时间精力就也行。

其他的留给我或者 @hhyo 看就行了。

2020-10-05 08:35 UTC, LeoQuote commented
@hhyo 要求的check 改成这个吧 Travis CI - Pull Request

2020-10-05 09:43 UTC, hhyo approved these changes

2020-10-05 09:49 UTC, hhyo reviewed
非常感谢你的贡献，可以的话最好能够完善一下相关的文档，添加到对应的wiki页面就好，因为查询的写法有比较大的改动，wiki地址 https://github.com/hhyo/archery/wiki/

2020-10-05 09:51 UTC, hhyo commented
> @hhyo 要求的check 改成这个吧 Travis CI - Pull Request

已调整，这个pr你来合并吧

2020-10-05 13:10 UTC, fancy-lee commented
> 非常感谢你的贡献，可以的话最好能够完善一下相关的文档，添加到对应的wiki页面就好，因为查询的写法有比较大的改动，wiki地址 https://github.com/hhyo/archery/wiki/

已经加完了

2020-10-06 04:27 UTC, hhyo requested changes

2020-10-06 04:27 UTC, hhyo commented on sql/engines/mongo.py
> +    def exec_cmd(self, sql, db_name=None, slave_ok=''):
审核执行依赖mongo，那dockerfile也需要调整一下

2020-10-06 08:04 UTC, LeoQuote commented on sql/engines/mongo.py
> +        self.db_name = 'admin'
??? 是不是多了一行? 
```suggestion
```

2020-10-06 08:06 UTC, LeoQuote commented on sql/engines/mongo.py
> +            sql = sql.replace("explain", "")+".explain()"
这两句是不是重复了? filter_sql 似乎已经 cover 了

2020-10-06 08:12 UTC, LeoQuote commented on sql/templates/sqlsubmit.html
> +                         }
缩进建议和之前保持一致
```suggestion
                        $("#db_name").selectpicker('val', sessionStorage.getItem('editDbname'));
                        if ($("#db_name").val()){
                            $("#db_name").selectpicker().trigger("change");
                        }
```

2020-10-06 08:17 UTC, LeoQuote commented on sql/templates/sqlsubmit.html
> +{% endblock %}
这里是没有必要的修改, 可以回滚一下

2020-10-06 08:17 UTC, LeoQuote commented on sql/templates/sqlsubmit.html
> +                            }  else if (result[i]['db_type'] === 'phoenix') {
这个修改没有必要, 回滚一下

2020-10-06 08:18 UTC, LeoQuote commented on sql/templates/sqlsubmit.html
> -                                escape: true,                       // 转义HTML字符串，替换 &, <, >, ", \`, 和 ' 字符。
这个修改的目的是什么?  https://github.com/hhyo/Archery/pull/721 之前的pr 是这个

2020-10-06 08:20 UTC, LeoQuote commented on sql/templates/sqlsubmit.html
> -                                <input id="demand_url" type="text" autocomplete="off" name="demand_url" class="form-control"
这个功能为什么去掉了?

2020-10-06 08:20 UTC, LeoQuote commented on sql/templates/sqlquery.html
> +                },
缩进调整一下吧

2020-10-06 08:21 UTC, LeoQuote commented on sql/templates/sqlquery.html
> +                            }
缩进

```suggestion
                        if (optgroup == 'Mongo') {
                            isdetail = true
                        }
```

2020-10-06 08:31 UTC, LeoQuote commented
一是上面的提到的事情, 建议都看一下.
另外建议按照engine 设计的来做, 也就是 engine 中的 `query_check` 方法用来做语句的初检, 如果此时语句为空, 可以返回 bad check , 并且报错, 这部分是有现成的前端返回的, 不需要你在几乎所有的方法里都要校验语句是否为空, 即使校验也是在 `query_check` 里校验

https://github.com/hhyo/Archery/blob/20462a103d27e5d0d32c3aaec533b2f886d3c0be/sql/query.py#L58-L63

然后用 `filter_sql` 做查询时的语句改写 https://github.com/hhyo/Archery/blob/20462a103d27e5d0d32c3aaec533b2f886d3c0be/sql/query.py#L84

2020-10-06 08:34 UTC, LeoQuote commented on sql/engines/mongo.py
> +class JsonDecoder:
这个 decoder , 如果有现成的用现成的, 没有现成的所有方法尽量都加上测试. 不然除了作者基本不敢动

2020-10-06 08:36 UTC, LeoQuote commented on sql/query.py
> +
这里的修改没有必要, 回滚一下吧

2020-10-06 12:28 UTC, fancy-lee commented on sql/engines/mongo.py
> +        self.db_name = 'admin'
其实我没有太明白上一个版本的逻辑，为什么要指定非admin的库，因为我们后台正常配置用户是高权限用户，如果用高权限用户验证非admin库是会报错

2020-10-06 12:32 UTC, fancy-lee commented on sql/templates/sqlsubmit.html
> -                                escape: true,                       // 转义HTML字符串，替换 &, <, >, ", \`, 和 ' 字符。
我这边的新版本mongodb查询的语法是原生的了，不再是上一版本redsh语法，所以单元测试也修改了

2020-10-06 13:22 UTC, fancy-lee commented on sql/engines/mongo.py
> +            sql = sql.replace("explain", "")+".explain()"
query_check是为了验证，filter_sql才是真正的修改提交的语句

2020-10-06 13:23 UTC, fancy-lee commented on sql/templates/sqlsubmit.html
> +                         }
由于我本地的sqlsubmit.html版本比较旧，我用最新的版本做了替换

2020-10-06 13:40 UTC, fancy-lee commented on sql/query.py
> +
我对比了query.py这个文件和最新的githu中的是一模一样的

2020-10-06 13:51 UTC, fancy-lee commented on sql/engines/mongo.py
> +        self.db_name = 'admin'
如果只用普通用户访问非admin的库，那很多功能上会有制约？

2020-10-06 13:53 UTC, fancy-lee commented
> 一是上面的提到的事情, 建议都看一下.
> 另外建议按照engine 设计的来做, 也就是 engine 中的 `query_check` 方法用来做语句的初检, 如果此时语句为空, 可以返回 bad check , 并且报错, 这部分是有现成的前端返回的, 不需要你在几乎所有的方法里都要校验语句是否为空, 即使校验也是在 `query_check` 里校验
> 
> https://github.com/hhyo/Archery/blob/20462a103d27e5d0d32c3aaec533b2f886d3c0be/sql/query.py#L58-L63
> 
> 然后用 `filter_sql` 做查询时的语句改写
> 
> https://github.com/hhyo/Archery/blob/20462a103d27e5d0d32c3aaec533b2f886d3c0be/sql/query.py#L84

我把语句为空的这个校验去了

2020-10-06 15:09 UTC, fancy-lee commented on sql/engines/mongo.py
> +class JsonDecoder:
目前还没有找到现成好用的decoder,这个类可以单独拿出来做一下测试的，我这边本地的测试环境配置有点问题，辛苦你加一下？

2020-10-06 16:31 UTC, hhyo commented on sql/engines/mongo.py
> +        self.db_name = 'admin'
参考这个pr #618，具体功能限制是会有，不过一般的版本更新不要做太多不兼容的修改，需要考虑老用户的升级成本

2020-10-06 23:58 UTC, LeoQuote commented on sql/query.py
> +
哦可能是需要rebase 一下

2020-10-06 23:59 UTC, LeoQuote commented on sql/engines/mongo.py
> +class JsonDecoder:
我没有办法帮你加测试环境呀，你得自己看是什么问题然后解决

2020-10-07 00:00 UTC, LeoQuote commented on sql/engines/mongo.py
> +        self.db_name = 'admin'
这个点在于，你要么按之前的设计不动，要么按你的新方法，两个共存是没有意义的，第一行的那个语句是不会生效的。

2020-10-07 00:02 UTC, LeoQuote commented on sql/engines/mongo.py
> +        self.db_name = 'admin'
你要么不改，要么是 self.db = db or ‘admin’

2020-10-07 01:52 UTC, fancy-lee commented on sql/engines/mongo.py
> +        self.db_name = 'admin'
> 参考这个pr #618，具体功能限制是会有，不过一般的版本更新不要做太多不兼容的修改，需要考虑老用户的升级成本

这个逻辑可能只适用于没有审核的情况，如果开放非admin库的验证，会增加很多的判断和改动，不然会出现很多报错

2020-10-07 01:53 UTC, fancy-lee commented on sql/engines/mongo.py
> +        self.db_name = 'admin'
> 你要么不改，要么是 self.db = db or ‘admin’

那我就保留这一行，把上一行去了

2020-10-07 06:29 UTC, fancy-lee commented on sql/engines/mongo.py
> +class JsonDecoder:
> 我没有办法帮你加测试环境呀，你得自己看是什么问题然后解决

它只是一个独立的工具类，它的主要工功能是对语句中db.col.find({"id":123})的{}部分解析成dict,它可以单独拿出来做测试和修改，应该不会像你说的"除了作者不敢动”这么严重，因为我本地测试环境有问题，只能push上来做测试，所以希望你帮忙加一下测试

2020-10-07 09:33 UTC, LeoQuote requested changes
就这一个地方改了就可以m了，单元测试什么的没条件后续再补吧

2020-10-07 09:33 UTC, LeoQuote commented on sql/engines/mongo.py
> +        self.db_name = 'admin'
这个按照讨论改一下吧

2020-10-08 01:46 UTC, fancy-lee commented
> 就这一个地方改了就可以m了，单元测试什么的没条件后续再补吧
> 
> 如果新的审核需要安装mongo client ，也需要改一下 dockerfile

在容器中下载：https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel70-3.6.20.tgz，解压后在bin目录下把mongo命令复制到指定目录，然后配置下环境变量或软链接，保证在任何地方能执行mongo命令，最后删除原来的压缩包和解压目录。生成一个新的基础镜像就可以了

2020-10-08 01:49 UTC, fancy-lee commented on sql/engines/mongo.py
> +        self.db_name = 'admin'
我已经修改并提交了

2020-10-09 10:19 UTC, LeoQuote commented
https://github.com/fancy-lee/Archery/blob/archery-fancy/src/docker/Dockerfile-base 帮忙改一下 dockerfile 吧, 在最后面加上你说的那些步骤就可以了.

2020-10-11 06:34 UTC, fancy-lee commented
> https://github.com/fancy-lee/Archery/blob/archery-fancy/src/docker/Dockerfile-base 帮忙改一下 dockerfile 吧, 在最后面加上你说的那些步骤就可以了.

已经加完了

2020-10-12 06:25 UTC, LeoQuote approved these changes
👏 LGTM

2020-10-12 15:49 UTC, hhyo approved these changes

2020-10-12 15:50 UTC, hhyo commented
感谢两位

2020-10-13 00:54 UTC, merged

2020-10-16 00:22 UTC, hhyo commented on sql/templates/sqlsubmit.html
> +                            <li>[指定执行时间]用于定时任务，不是必选项</li>
执行时间可能理解有误，这个并不是用于定时，是用于错峰执行

2020-10-16 00:25 UTC, hhyo commented on sql/templates/sqlsubmit.html
> +            if (optgroup != "MySQL") {$("#div-backup").hide(); $("#is_backup").val("False");}
目前Oracle也支持备份，这块后面我处理一下