没有查询权限时，增加申请链接
hhyo/archer pull request #904
Opened 2020-10-09 09:58 UTC by dongqianzheng

2020-10-09 10:08 UTC, LeoQuote commented on sql/query_privileges.py
> +                    result['status'] = 2
为什么需要一个新的status, 原先的 1 不够用吗?

2020-10-09 12:44 UTC, hhyo commented on sql/query_privileges.py
> +                    result['status'] = 2
应该是目前所有的错误都用的1，为了区分是没有权限，增加了2

2020-10-10 01:57 UTC, hhyo requested changes
按照ci结果调整一下测试用例

2020-10-10 02:18 UTC, dongqianzheng commented on sql/query_privileges.py
> +                    result['status'] = 2
是的，只有在权限不够这种情况时，才会有这个链接。

2020-10-14 10:52 UTC, LeoQuote commented
麻烦 rebase 下master吧，master 有更新

2020-10-14 11:27 UTC, dongqianzheng commented
我要怎么操作呢？先把我的仓库删掉，然后再fork一个最新的，再修改，提pr吗？

2020-10-14 13:42 UTC, hhyo approved these changes

2020-10-14 13:44 UTC, merged